insert into acnl_bottom values(123, 0, 'Callie pants', 'unorderable', '(Welcome Amiibo) Cece''s RV', 'unknown', 'unknown');
insert into acnl_bottom values(124, 0, 'Ganondorf pants', 'unorderable', '(Welcome Amiibo) Ganon''s RV', 'unknown', 'unknown');
insert into acnl_bottom values(125, 0, 'green gingham shorts', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_bottom values(126, 0, 'high-spirits pants', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_bottom values(127, 0, 'Sheik pants', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_carpet values(119, 0, 'arched brick floor', 'unorderable', '(Welcome Amiibo) Olive''s RV');
insert into acnl_carpet values(120, 0, 'block flooring', 'unorderable', '(Welcome Amiibo) Cashmere''s RV, Huck''s RV, Mabel''s RV');
insert into acnl_carpet values(121, 0, 'Cinnamoroll floor', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)');
insert into acnl_carpet values(122, 0, 'convenient floor', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)');
insert into acnl_carpet values(123, 0, 'dirt floor', 'unorderable', '(Welcome Amiibo) Booker''s RV, Boots'' RV, Buzz''s RV');
insert into acnl_carpet values(124, 0, 'fancy tile floor', 'unorderable', '(Welcome Amiibo) Gonzo''s RV, Weber''s RV');
insert into acnl_carpet values(125, 0, 'field floor', 'unorderable', '(Welcome Amiibo) Tad''s RV');
insert into acnl_carpet values(126, 0, 'flagstone floor', 'unorderable', '(Welcome Amiibo) Maggie''s RV');
insert into acnl_carpet values(127, 0, 'fruit-panel floor', 'unorderable', '(Welcome Amiibo) Start Story Mode in Puzzle League');
insert into acnl_carpet values(128, 0, 'Fueki floor', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)');
insert into acnl_carpet values(129, 0, 'galaxy floor', 'unorderable', '(Welcome Amiibo) Villager''s RV');
insert into acnl_carpet values(130, 0, 'gallery floor', 'unorderable', '(Welcome Amiibo) Blathers'' RV');
insert into acnl_carpet values(131, 0, 'gray patterned floor', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)');
insert into acnl_carpet values(132, 0, 'Hello Kitty floor', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)');
insert into acnl_carpet values(133, 0, 'herringbone floor', 'unorderable', '(Welcome Amiibo) Digby''s RV, Julia''s RV, Stella''s RV');
insert into acnl_carpet values(134, 0, 'Inkopolis floor', 'unorderable', '(Welcome Amiibo) Cece''s RV, Viché''s RV');
insert into acnl_carpet values(135, 0, 'ink-splattered floor', 'unorderable', '(Welcome Amiibo) Inkwell''s RV');
insert into acnl_carpet values(136, 0, 'Kiki and Lala floor', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)');
insert into acnl_carpet values(137, 0, 'lava floor', 'unorderable', '(Welcome Amiibo) Felyne''s RV');
insert into acnl_carpet values(138, 0, 'lobby floor', 'unorderable', '(Welcome Amiibo) Bitty''s RV, Boris'' RV');
insert into acnl_carpet values(139, 0, 'monochrome floor', 'unorderable', '(Welcome Amiibo) Claude''s RV, Timmy & Tommy''s RV');
insert into acnl_carpet values(140, 0, 'My Melody floor', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)');
insert into acnl_carpet values(141, 0, 'natural wood floor', 'unorderable', '(Welcome Amiibo) Bea''s RV, Louie''s RV');
insert into acnl_carpet values(142, 0, 'observatory floor', 'unorderable', '(Welcome Amiibo) Celeste''s RV');
insert into acnl_carpet values(143, 0, 'oil-stained floor', 'unorderable', '(Welcome Amiibo) Cyrus'' RV, Dobie''s RV');
insert into acnl_carpet values(144, 0, 'panel carpet floor', 'unorderable', '(Welcome Amiibo) Cleo''s RV, Piper''s RV');
insert into acnl_carpet values(145, 0, 'parquet floor [Welcome amiibo]', 'unorderable', '(Welcome Amiibo) Billy''s RV, Copper''s RV, Vivian''s RV');
insert into acnl_carpet values(146, 0, 'pavement floor', 'unorderable', '(Welcome Amiibo) Ike''s RV, Stu''s RV');
insert into acnl_carpet values(147, 0, 'pink wood floor', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Lottie''s RV, Reese''s RV');
insert into acnl_carpet values(148, 0, 'Pompompurin floor', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)');
insert into acnl_carpet values(149, 0, 'sandy-beach floor', 'unorderable', '(Welcome Amiibo) Gulliver''s RV, Plucky''s RV');
insert into acnl_carpet values(150, 0, 'school-hall floor', 'unorderable', '(Welcome Amiibo) Raddle''s RV, Rover''s RV');
insert into acnl_carpet values(151, 0, 'stone-tile floor', 'unorderable', '(Welcome Amiibo) Murphy''s RV');
insert into acnl_carpet values(152, 0, 'tatami floor', 'unorderable', '(Welcome Amiibo) Snooty''s RV, Wade''s RV');
insert into acnl_carpet values(153, 0, 'terrace rug', 'unorderable', '(Welcome Amiibo) Spike''s RV');
insert into acnl_carpet values(154, 0, 'terra-cotta floor', 'unorderable', '(Welcome Amiibo) Ellie''s RV, Kicks'' RV, Tom Nook''s RV, Tybalt''s RV');
insert into acnl_carpet values(155, 0, 'water floor', 'unorderable', '(Welcome Amiibo) Unlock advanced levels in Desert Island Escape');
insert into acnl_carpet values(156, 0, 'white tile floor', 'unorderable', '(Welcome Amiibo) Paolo''s RV');
insert into acnl_carpet values(157, 0, 'white wood floor', 'unorderable', '(Welcome Amiibo) Jingle''s RV, June''s RV');
insert into acnl_carpet values(158, 0, 'wooden-deck floor', 'unorderable', '(Welcome Amiibo) Sylvana''s RV');
insert into acnl_carpet values(159, 0, 'yellow flooring', 'unorderable', '(Welcome Amiibo) Blanca''s RV, Hopkins'' RV');
insert into acnl_carpet values(160, 0, 'Zelda floor', 'unorderable', '(Welcome Amiibo) Epona''s RV, Ganon''s RV, Medli''s RV, Wolf Link''s RV');
insert into acnl_dress values(99, 0, 'blue ballet outfit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_dress values(100, 0, 'Flower Fairy dress', 'unorderable', '(Welcome Amiibo) Obtain at least 10,000 points in Score Attack on any difficulty in Puzzle League', 'unknown', 'unknown');
insert into acnl_dress values(101, 0, 'Hello Kitty dress', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_dress values(102, 0, 'Kiki and Lala dress', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_dress values(103, 0, 'Marie dress', 'unorderable', '(Welcome Amiibo) Viché''s RV', 'unknown', 'unknown');
insert into acnl_dress values(104, 0, 'musician''s outfit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_dress values(105, 0, 'My Melody dress', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_dress values(106, 0, 'Pompompurin dress', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_dress values(107, 0, 'Princess Zelda dress', 'unorderable', '(Welcome Amiibo) Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_feet values(99, 0, 'Callie shoes', 'unorderable', '(Welcome Amiibo) Cece''s RV', 'unknown', 'unknown');
insert into acnl_feet values(100, 0, 'Cinnamoroll shoes', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(101, 0, 'Flower Fairy boots', 'unorderable', '(Welcome Amiibo) Obtain at least 2,500 points in Time Attack on any difficulty in Puzzle League', 'unknown', 'unknown');
insert into acnl_feet values(102, 0, 'green loafers', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(103, 0, 'Hello Kitty shoes', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(104, 0, 'Kiki and Lala shoes', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(105, 0, 'Marie shoes', 'unorderable', '(Welcome Amiibo) Viché''s RV', 'unknown', 'unknown');
insert into acnl_feet values(106, 0, 'My Melody shoes', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(107, 0, 'Pompompurin shoes', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(108, 0, 'Callie tights', 'unorderable', '(Welcome Amiibo) Cece''s RV', 'unknown', 'unknown');
insert into acnl_feet values(109, 0, 'Kiki and Lala socks', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_feet values(110, 0, 'Marie tights', 'unorderable', '(Welcome Amiibo) Viché''s RV', 'unknown', 'unknown');
insert into acnl_feet values(111, 0, 'red striped socks', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1215, 0, '2017 cake', 'unorderable', '(Welcome Amiibo) DLC', 'unknown', 'unknown');
insert into acnl_furniture values(1216, 0, '24-hour-shop banner', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1217, 0, '24-hour-shop baskets', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1218, 0, '24-hour-shop clock', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1219, 0, 'accordion screen', 'unorderable', '(Welcome Amiibo) Resetti''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1220, 0, 'air pump', 'unorderable', '(Welcome Amiibo) Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1221, 0, 'air purifier', 'unorderable', '(Welcome Amiibo) Murphy''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1222, 0, 'alto saxophone', 'unorderable', '(Welcome Amiibo) Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1223, 0, 'amiibo shelf', 'unorderable', '(Welcome Amiibo) Complete every advanced level in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1224, 0, 'antique shelf', 'unorderable', '(Welcome Amiibo) Reese''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1225, 0, 'autograph cards', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1226, 0, 'balance beam', 'unorderable', '(Welcome Amiibo) Louie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1227, 0, 'ball', 'unorderable', '(Welcome Amiibo) Gulliver''s RV, Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1228, 0, 'bamboo bench', 'unorderable', '(Welcome Amiibo) Boots'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1229, 0, 'bamboo fence', 'unorderable', '(Welcome Amiibo) Tad''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1230, 0, 'banana flower basket', 'unorderable', '(Welcome Amiibo) Kapp''n''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1231, 0, 'barbecue spit', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1232, 0, 'barbell', 'unorderable', '(Welcome Amiibo) Louie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1233, 0, 'barrel planter', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1234, 0, 'baseball set', 'unorderable', '(Welcome Amiibo) Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1235, 0, 'basic display stand', 'unorderable', '(Welcome Amiibo) Candi''s RV, Ursala''s RV, Weber''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1236, 0, 'basic teacher''s desk', 'unorderable', '(Welcome Amiibo) Blathers'' RV, Leopold''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1237, 0, 'basic trash can', 'unorderable', '(Welcome Amiibo) Digby''s RV, Hornsby''s RV, Vivian''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1238, 0, 'basket chair', 'unorderable', '(Welcome Amiibo) Isabelle''s RV, Stella''s RV, Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1239, 0, 'bathroom shelf', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1240, 0, 'bath set', 'unorderable', '(Welcome Amiibo) Paolo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1241, 0, 'beauty salon cart', 'unorderable', '(Welcome Amiibo) Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1242, 0, 'big amp', 'unorderable', '(Welcome Amiibo) Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1243, 0, 'billboard', 'unorderable', '(Welcome Amiibo) Copper''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1244, 0, 'bistro table', 'unorderable', '(Welcome Amiibo) Olive''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1245, 0, 'black phone', 'unorderable', '(Welcome Amiibo) Billy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1246, 0, 'blowfish sashimi', 'unorderable', '(Welcome Amiibo) Chip''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1247, 0, 'blueprints', 'unorderable', '(Welcome Amiibo) Digby''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1248, 0, 'board game', 'unorderable', '(Welcome Amiibo) Claude''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1249, 0, 'bomb', 'unorderable', '(Welcome Amiibo) Ganon''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1250, 0, 'book stands', 'unorderable', '(Welcome Amiibo) Dobie''s RV, Leopold''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1251, 0, 'Boston bag', 'unorderable', '(Welcome Amiibo) Rex''s RV, Rover''s RV, Stu''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1252, 0, 'bowl sink', 'unorderable', '(Welcome Amiibo) Stella''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1253, 0, 'box-shaped seat', 'unorderable', '(Welcome Amiibo) Rex''s RV, Tad''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1254, 0, 'box with helmet', 'unorderable', '(Welcome Amiibo) Resetti''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1255, 0, 'bread basket', 'unorderable', '(Welcome Amiibo) Bea''s RV, Ellie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1256, 0, 'bread-making set', 'unorderable', '(Welcome Amiibo) Bea''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1257, 0, 'brick oven', 'unorderable', '(Welcome Amiibo) Ketchup''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1258, 0, 'brown seat', 'unorderable', '(Welcome Amiibo) Digby''s RV, K.K.''s RV, Spike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1259, 0, 'burger meal', 'unorderable', '(Welcome Amiibo) Huck''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1260, 0, 'busing station', 'unorderable', '(Welcome Amiibo) Huck''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1261, 0, 'bus-stop stand', 'unorderable', '(Welcome Amiibo) Boyd''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1262, 0, 'cable spool', 'unorderable', '(Welcome Amiibo) Rex''s RV, Tad''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1263, 0, 'cafeteria table', 'unorderable', '(Welcome Amiibo) Sylvana''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1264, 0, 'candelabra', 'unorderable', '(Welcome Amiibo) Billy''s RV, Julia''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1265, 0, '', 'unorderable', '(Welcome Amiibo) Obtained From', 'unknown', 'unknown');
insert into acnl_furniture values(1266, 0, 'cans', 'unorderable', '(Welcome Amiibo) Candi''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1267, 0, 'carpentry set', 'unorderable', '(Welcome Amiibo) Cyrus'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1268, 0, 'carriage', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1269, 0, 'cart return', 'unorderable', '(Welcome Amiibo) Timmy & Tommy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1270, 0, 'Casablanca lilies', 'unorderable', '(Welcome Amiibo) Ursala''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1271, 0, 'cash tray', 'unorderable', '(Welcome Amiibo) June''s RV, Ursala''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1272, 0, 'casual display stand', 'unorderable', '(Welcome Amiibo) Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1273, 0, 'chain divider', 'unorderable', '(Welcome Amiibo) Gonzo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1274, 0, 'changing room', 'unorderable', '(Welcome Amiibo) Bitty''s RV, Louie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1275, 0, 'cheese', 'unorderable', '(Welcome Amiibo) Norma''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1276, 0, 'Chihuahua ornament', 'unorderable', '(Welcome Amiibo) Fortune cookie #53', 'unknown', 'unknown');
insert into acnl_furniture values(1277, 0, 'Cinnamoroll parasol', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1278, 0, 'Cinnamoroll sign', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1279, 0, 'Cinnamoroll sofa', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1280, 0, 'Cinnamoroll stool', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1281, 0, 'Cinnamoroll table', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1282, 0, 'Cinnamoroll tray', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1283, 0, 'classic screen', 'unorderable', '(Welcome Amiibo) Stella''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1284, 0, 'cloud-making machine', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1285, 0, 'coconut juice', 'unorderable', '(Welcome Amiibo) Plucky''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1286, 0, 'coin locker', 'unorderable', '(Welcome Amiibo) Stu''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1287, 0, 'compact car', 'unorderable', '(Welcome Amiibo) Rex''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1288, 0, 'console table', 'unorderable', '(Welcome Amiibo) Digby''s RV, Dobie''s RV, Piper''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1289, 0, 'conveyor belt', 'unorderable', '(Welcome Amiibo) Murphy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1290, 0, 'cornstalks', 'unorderable', '(Welcome Amiibo) Tad''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1291, 0, 'counter seat', 'unorderable', '(Welcome Amiibo) Kicks'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1292, 0, 'counter table', 'unorderable', '(Welcome Amiibo) Bea''s RV, Ellie''s RV, Kicks'' RV, Mabel''s RV, Sylvana''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1293, 0, 'crayons', 'unorderable', '(Welcome Amiibo) Blanca''s RV, Carrie''s RV, Wendell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1294, 0, 'cruiser bike', 'unorderable', '(Welcome Amiibo) Maddie''s RV, Stu''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1295, 0, 'Cucco ornament', 'unorderable', '(Welcome Amiibo) Medli''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1296, 0, 'cupcake', 'unorderable', '(Welcome Amiibo) Sandy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1297, 0, 'cup of tea', 'unorderable', '(Welcome Amiibo) Boris'' RV, Claude''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1298, 0, 'curry plate', 'unorderable', '(Welcome Amiibo) Cashmere''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1299, 0, 'cutting-board set', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Cashmere''s RV, Ketchup''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1300, 0, 'cypress plant', 'unorderable', '(Welcome Amiibo) Candi''s RV, Olive''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1301, 0, 'Dachshund ornament', 'unorderable', '(Welcome Amiibo) Fortune cookie #55', 'unknown', 'unknown');
insert into acnl_furniture values(1302, 0, 'daimyo''s tray', 'unorderable', '(Welcome Amiibo) Billy''s RV, Joan''s RV, Kapp''n''s RV, Wade''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1303, 0, 'Dalmatian ornament', 'unorderable', '(Welcome Amiibo) Fortune cookie #54', 'unknown', 'unknown');
insert into acnl_furniture values(1304, 0, 'decorative plate', 'unorderable', '(Welcome Amiibo) Snooty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1305, 0, 'decoy duck', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1306, 0, 'Desert Island map', 'unorderable', '(Welcome Amiibo) Obtain high scores in the beginner levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1307, 0, 'Desert Island stool', 'unorderable', '(Welcome Amiibo) Obtain high scores in the advanced levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1308, 0, 'Desert Island table', 'unorderable', '(Welcome Amiibo) Obtain high scores in the intermediate levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1309, 0, 'desk bell', 'unorderable', '(Welcome Amiibo) Julia''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1310, 0, 'desk mirror', 'unorderable', '(Welcome Amiibo) Vivian''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1311, 0, 'desktop mic', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1312, 0, 'desktop TV', 'unorderable', '(Welcome Amiibo) Spike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1313, 0, 'dinnerware', 'unorderable', '(Welcome Amiibo) Admiral''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1314, 0, 'Disk Writer', 'unorderable', '(Welcome Amiibo) Hopkins'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1315, 0, '', 'unorderable', '(Welcome Amiibo) Obtained From', 'unknown', 'unknown');
insert into acnl_furniture values(1316, 0, 'doctor''s desk', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1317, 0, 'document stack', 'unorderable', '(Welcome Amiibo) Cleo''s RV, Digby''s RV, Dobie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1318, 0, 'donburi', 'unorderable', '(Welcome Amiibo) Sylvana''s RV, Zipper T. Bunny''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1319, 0, 'do-not-enter sign', 'unorderable', '(Welcome Amiibo) Stu''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1320, 0, 'donut box', 'unorderable', '(Welcome Amiibo) Claude''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1321, 0, 'donut cushion', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1322, 0, 'drafting table', 'unorderable', '(Welcome Amiibo) Lottie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1323, 0, 'drink machine', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Huck''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1324, 0, 'durian flower basket', 'unorderable', '(Welcome Amiibo) Kapp''n''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1325, 0, 'EKG machine', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1326, 0, 'electric bass', 'unorderable', '(Welcome Amiibo) Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1327, 0, 'electric sign', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1328, 0, 'elegant bench', 'unorderable', '(Welcome Amiibo) Claude''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1329, 0, 'elegant chair', 'unorderable', '(Welcome Amiibo) Claude''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1330, 0, 'espresso machine', 'unorderable', '(Welcome Amiibo) Ellie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1331, 0, 'exam table', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1332, 0, 'exercise ball', 'unorderable', '(Welcome Amiibo) Louie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1333, 0, 'fairy bottle', 'unorderable', '(Welcome Amiibo) Medli''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1334, 0, 'fancy display case', 'unorderable', '(Welcome Amiibo) Bitty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1335, 0, 'fancy display stand', 'unorderable', '(Welcome Amiibo) Bitty''s RV, June''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1336, 0, 'fancy tea set', 'unorderable', '(Welcome Amiibo) Sandy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1337, 0, 'Felyne Guardian', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1338, 0, 'file cabinet (L)', 'unorderable', '(Welcome Amiibo) Blathers'' RV, Cleo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1339, 0, 'file cabinet (M)', 'unorderable', '(Welcome Amiibo) Murphy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1340, 0, 'firewood', 'unorderable', '(Welcome Amiibo) Ketchup''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1341, 0, 'first-aid kit', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1342, 0, 'fish and chips', 'unorderable', '(Welcome Amiibo) Piper''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1343, 0, 'fish on a board', 'unorderable', '(Welcome Amiibo) Chip''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1344, 0, 'floor light', 'unorderable', '(Welcome Amiibo) Boris'' RV, Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1345, 0, 'floor monitor', 'unorderable', '(Welcome Amiibo) Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1346, 0, 'floor seat', 'unorderable', '(Welcome Amiibo) Joan''s RV, Kapp''n''s RV, Wade''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1347, 0, 'flower bed', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1348, 0, 'flower display case', 'unorderable', '(Welcome Amiibo) Ursala''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1349, 0, 'flower wreath', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1350, 0, 'forklift', 'unorderable', '(Welcome Amiibo) Boyd''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1351, 0, 'fruit drink', 'unorderable', '(Welcome Amiibo) Ellie''s RV, Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1352, 0, 'fruit-panel cushion', 'unorderable', '(Welcome Amiibo) Complete Story Mode in Puzzle League', 'unknown', 'unknown');
insert into acnl_furniture values(1353, 0, 'frying pan', 'unorderable', '(Welcome Amiibo) Clear six advanced levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1354, 0, 'Fueki chair', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_furniture values(1355, 0, 'Fueki drawers', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_furniture values(1356, 0, 'Fueki pot', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_furniture values(1357, 0, 'Fueki stereo', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_furniture values(1358, 0, 'Fueki table', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_furniture values(1359, 0, 'futon mattress', 'unorderable', '(Welcome Amiibo) Hornsby''s RV, Kapp''n''s RV, Wade''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1360, 0, 'gadget shelf', 'unorderable', '(Welcome Amiibo) Celeste''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1361, 0, 'GameCube drawer', 'unorderable', '(Welcome Amiibo) Villager''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1362, 0, 'garbage bin', 'unorderable', '(Welcome Amiibo) Boyd''s RV, Jacob''s RV, Stu''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1363, 0, 'garden chair', 'unorderable', '(Welcome Amiibo) Maddie''s RV, Olive''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1364, 0, 'garden faucet', 'unorderable', '(Welcome Amiibo) Maddie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1365, 0, 'garden lantern', 'unorderable', '(Welcome Amiibo) Maddie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1366, 0, 'garden rock', 'unorderable', '(Welcome Amiibo) Boots'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1367, 0, 'garden table', 'unorderable', '(Welcome Amiibo) Maddie''s RV, Olive''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1368, 0, 'garden tools', 'unorderable', '(Welcome Amiibo) Maggie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1369, 0, 'giant ant', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1370, 0, 'giant Game Boy', 'unorderable', '(Welcome Amiibo) Hopkins'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1371, 0, 'giant stew pot', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1372, 0, 'giant teddy bear', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1373, 0, 'gift pile', 'unorderable', '(Welcome Amiibo) Jingle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1374, 0, 'glass partition', 'unorderable', '(Welcome Amiibo) Gonzo''s RV, Paolo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1375, 0, 'glass screen', 'unorderable', '(Welcome Amiibo) Cashmere''s RV, Kicks'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1376, 0, 'glass teapot', 'unorderable', '(Welcome Amiibo) Claude''s RV, Ketchup''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1377, 0, 'good-luck charm', 'unorderable', '(Welcome Amiibo) Complete every level in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1378, 0, 'Gossip Stone', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1379, 0, 'greenhouse box', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1380, 0, 'green net', 'unorderable', '(Welcome Amiibo) Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1381, 0, 'guitar case', 'unorderable', '(Welcome Amiibo) K.K.''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1382, 0, 'half-eaten pizza', 'unorderable', '(Welcome Amiibo) Resetti''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1383, 0, 'handbag', 'unorderable', '(Welcome Amiibo) Vivian''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1384, 0, 'handwashing area', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1385, 0, 'hanger rack', 'unorderable', '(Welcome Amiibo) Bitty''s RV, Spike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1386, 0, 'hanging chair', 'unorderable', '(Welcome Amiibo) Vivian''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1387, 0, 'hanging strap', 'unorderable', '(Welcome Amiibo) Rover''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1388, 0, 'Heart', 'unorderable', '(Welcome Amiibo) Medli''s RV, Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1389, 0, 'Heart Container', 'unorderable', '(Welcome Amiibo) Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1390, 0, 'hearty breakfast', 'unorderable', '(Welcome Amiibo) Reese''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1391, 0, 'heavy tome', 'unorderable', '(Welcome Amiibo) Blathers'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1392, 0, 'Hello Kitty bed', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1393, 0, 'Hello Kitty chair', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1394, 0, 'Hello Kitty clock', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1395, 0, 'Hello Kitty drawers', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1396, 0, 'Hello Kitty planter', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1397, 0, 'Hello Kitty table', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1398, 0, 'Hero of Time scroll', 'unorderable', '(Welcome Amiibo) Medli''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1399, 0, 'hose reel', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1400, 0, 'hot-snack case', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1401, 0, 'hunter', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1402, 0, 'hunter''s cart', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1403, 0, 'hunter''s hive', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1404, 0, 'Hylian shield', 'unorderable', '(Welcome Amiibo) Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1405, 0, 'Hyrulean treasure', 'unorderable', '(Welcome Amiibo) Ganon''s RV, Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1406, 0, 'iceberg', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1407, 0, 'ice-cream display', 'unorderable', '(Welcome Amiibo) Olive''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1408, 0, 'Ikada trophy', 'unorderable', '(Welcome Amiibo) Obtain high scores in all levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1409, 0, 'ikebana display', 'unorderable', '(Welcome Amiibo) Snooty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1410, 0, 'imperial chair', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1411, 0, 'imperial pot', 'unorderable', '(Welcome Amiibo) Admiral''s RV, Zipper T. Bunny''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1412, 0, 'inflatable Resetti', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1413, 0, 'Inkopolis chair', 'unorderable', '(Welcome Amiibo) Cece''s RV, Viché''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1414, 0, 'Inkopolis sign', 'unorderable', '(Welcome Amiibo) Cece''s RV, Viché''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1415, 0, '', 'unorderable', '(Welcome Amiibo) Obtained From', 'unknown', 'unknown');
insert into acnl_furniture values(1416, 0, 'instruction manual', 'unorderable', '(Welcome Amiibo) 420 ', 'unknown', 'unknown');
insert into acnl_furniture values(1417, 0, 'iron garden chair', 'unorderable', '(Welcome Amiibo) Ellie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1418, 0, 'iron garden table', 'unorderable', '(Welcome Amiibo) Ellie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1419, 0, 'Isabelle scooter', 'unorderable', '(Welcome Amiibo) Isabelle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1420, 0, 'item box', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1421, 0, 'ivy partition', 'unorderable', '(Welcome Amiibo) Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1422, 0, 'jail bars', 'unorderable', '(Welcome Amiibo) Gonzo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1423, 0, 'jewelry case', 'unorderable', '(Welcome Amiibo) Bitty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1424, 0, 'kaiseki meal', 'unorderable', '(Welcome Amiibo) Wade''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1425, 0, 'Kerokerokeroppi cake', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1426, 0, 'Kerokerokeroppi doll', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1427, 0, 'Kerokerokeroppi tray', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1428, 0, 'kick scooter', 'unorderable', '(Welcome Amiibo) Stu''s RV, Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1429, 0, 'Kicks mat', 'unorderable', '(Welcome Amiibo) Kicks'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1430, 0, 'kiddie meal', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1431, 0, 'Kiki and Lala bed', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1432, 0, 'Kiki and Lala clock', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1433, 0, 'Kiki and Lala sofa', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1434, 0, 'Kiki and Lala table', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1435, 0, 'kitchen counter', 'unorderable', '(Welcome Amiibo) Admiral''s RV, Cashmere''s RV, Chip''s RV, Olive''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1436, 0, 'kitchen dishwasher', 'unorderable', '(Welcome Amiibo) Admiral''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1437, 0, 'kitchen refrigerator', 'unorderable', '(Welcome Amiibo) Admiral''s RV, Franklin''s RV, Norma''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1438, 0, 'kitchen stove', 'unorderable', '(Welcome Amiibo) Admiral''s RV, Cashmere''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1439, 0, 'laboratory capsule', 'unorderable', '(Welcome Amiibo) Murphy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1440, 0, 'Labrador ornament', 'unorderable', '(Welcome Amiibo) Fortune cookie #56', 'unknown', 'unknown');
insert into acnl_furniture values(1441, 0, 'large egg', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1442, 0, 'large tea table', 'unorderable', '(Welcome Amiibo) Resetti''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1443, 0, 'lectern with mic', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1444, 0, 'lecture-hall bench', 'unorderable', '(Welcome Amiibo) Leopold''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1445, 0, 'lecture-hall desk', 'unorderable', '(Welcome Amiibo) Leopold''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1446, 0, 'left Splatfest sign', 'unorderable', '(Welcome Amiibo) Cece''s RV, Viché''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1447, 0, 'light breakfast', 'unorderable', '(Welcome Amiibo) Cyrus'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1448, 0, 'locker stack', 'unorderable', '(Welcome Amiibo) Louie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1449, 0, 'Lon Lon milk', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1450, 0, 'lotus pond', 'unorderable', '(Welcome Amiibo) DLC (JP)', 'unknown', 'unknown');
insert into acnl_furniture values(1451, 0, 'lucky doll', 'unorderable', '(Welcome Amiibo) Billy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1452, 0, 'lunch box', 'unorderable', '(Welcome Amiibo) Rex''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1453, 0, 'lunch pack', 'unorderable', '(Welcome Amiibo) Kicks'' RV, Maddie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1454, 0, 'luxury car', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1455, 0, 'massage recliner', 'unorderable', '(Welcome Amiibo) Louie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1456, 0, 'massive cake', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1457, 0, 'medicine cabinet', 'unorderable', '(Welcome Amiibo) June''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1458, 0, 'meeting-room chair', 'unorderable', '(Welcome Amiibo) Huck''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1459, 0, 'meeting-room table', 'unorderable', '(Welcome Amiibo) Cleo''s RV, Gonzo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1460, 0, 'menu chalkboard', 'unorderable', '(Welcome Amiibo) Bea''s RV, Sandy''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1461, 0, 'merchandise table', 'unorderable', '(Welcome Amiibo) Candi''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1462, 0, 'metal-and-wood chair', 'unorderable', '(Welcome Amiibo) Ketchup''s RV, Tasha''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1463, 0, 'metal-and-wood table', 'unorderable', '(Welcome Amiibo) Ketchup''s RV, Plucky''s RV, Tasha''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1464, 0, 'metal box', 'unorderable', '(Welcome Amiibo) Admiral''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1465, 0, 'metal can', 'unorderable', '(Welcome Amiibo) Boyd''s RV, Ike''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1466, 0, 'metal flagpole', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1467, 0, 'metal-rim table', 'unorderable', '(Welcome Amiibo) Boris'' RV, K.K.''s RV, Rover''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1468, 0, 'milk canister', 'unorderable', '(Welcome Amiibo) Norma''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1469, 0, 'milk carton', 'unorderable', '(Welcome Amiibo) Hopkins'' RV, Jacob''s RV, Norma''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1470, 0, 'minifridge', 'unorderable', '(Welcome Amiibo) Hornsby''s RV, Piper''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1471, 0, 'model bus', 'unorderable', '(Welcome Amiibo) Kapp''n''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1472, 0, 'model sailor', 'unorderable', '(Welcome Amiibo) Kapp''n''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1473, 0, 'modern cash register', 'unorderable', '(Welcome Amiibo) Candi''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1474, 0, 'modern hospital bed', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1475, 0, 'modern office chair', 'unorderable', '(Welcome Amiibo) Cleo''s RV, Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1476, 0, 'modern wash station', 'unorderable', '(Welcome Amiibo) Paolo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1477, 0, 'money box', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Gonzo''s RV, Timmy & Tommy''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1478, 0, 'monitor tower', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1479, 0, 'moss ball', 'unorderable', '(Welcome Amiibo) Snooty''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1480, 0, 'mountain', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1481, 0, 'mountain of money', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1482, 0, 'mug', 'unorderable', '(Welcome Amiibo) Norma''s RV, Rex''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1483, 0, 'museum clock', 'unorderable', '(Welcome Amiibo) Blathers'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1484, 0, 'museum mat', 'unorderable', '(Welcome Amiibo) Blathers'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1485, 0, 'My Melody bed', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1486, 0, 'My Melody chair', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1487, 0, 'My Melody clock', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1488, 0, 'My Melody dresser', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1489, 0, 'My Melody table', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1490, 0, 'Nabiru ornament', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1491, 0, 'narrow clock', 'unorderable', '(Welcome Amiibo) DLC (JP)', 'unknown', 'unknown');
insert into acnl_furniture values(1492, 0, 'natural bench', 'unorderable', '(Welcome Amiibo) Reese''s RV, Sandy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1493, 0, 'natural chair', 'unorderable', '(Welcome Amiibo) Cyrus'' RV, Sandy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1494, 0, 'natural lamp', 'unorderable', '(Welcome Amiibo) Claude''s RV, Isabelle''s RV, Vivian''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1495, 0, 'natural low table', 'unorderable', '(Welcome Amiibo) Cyrus'' RV, Reese''s RV, Sandy''s RV, Stella''s RV, Vivian''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1496, 0, 'natural table', 'unorderable', '(Welcome Amiibo) Claude''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1497, 0, 'NDS Lite bench', 'unorderable', '(Welcome Amiibo) Villager''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1498, 0, 'New 3DS - Isabelle', 'unorderable', '(Welcome Amiibo) Isabelle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1499, 0, 'New 3DS - K.K.', 'unorderable', '(Welcome Amiibo) K.K''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1500, 0, 'New 3DS - Mabel', 'unorderable', '(Welcome Amiibo) Mabel''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1501, 0, 'New 3DS - Sable', 'unorderable', '(Welcome Amiibo) Mabel''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1502, 0, 'New 3DS - T&T', 'unorderable', '(Welcome Amiibo) Timmy & Tommy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1503, 0, 'New 3DS XL - HHD', 'unorderable', '(Welcome Amiibo) Lottie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1504, 0, 'New Nintendo 3DS', 'unorderable', '(Welcome Amiibo) Blathers'' RV, Celeste''s RV, Cyrus'' RV, Digby''s RV, Kapp''n''s RV, Kicks'' RV, Reese''s RV, Resetti''s RV, Rover''s RV, Tom Nook''s RV, Fortune cookie #57', 'unknown', 'unknown');
insert into acnl_furniture values(1505, 0, 'New Nintendo 3DS XL', 'unorderable', '(Welcome Amiibo) Hopkins'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1506, 0, 'Nintendo 3DS shelf', 'unorderable', '(Welcome Amiibo) Clear a combo of 10 in Puzzle League', 'unknown', 'unknown');
insert into acnl_furniture values(1507, 0, 'Nintendo 3DS station', 'unorderable', '(Welcome Amiibo) Get a chain of at least 5 in Puzzle League', 'unknown', 'unknown');
insert into acnl_furniture values(1508, 0, 'Nintendo bench', 'unorderable', '(Welcome Amiibo) Villager''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1509, 0, 'Nintendo DSI bench', 'unorderable', '(Welcome Amiibo) Villager''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1510, 0, 'Nook''s Homes car', 'unorderable', '(Welcome Amiibo) Tom Nook''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1511, 0, 'Nook''s Homes mat', 'unorderable', '(Welcome Amiibo) Tom Nook''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1512, 0, 'Nook''s Homes model', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1513, 0, 'office cabinet', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1514, 0, 'office clock', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1515, 0, 'office phone', 'unorderable', '(Welcome Amiibo) Cleo''s RV, Murphy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1516, 0, 'omelet', 'unorderable', '(Welcome Amiibo) Zipper T. Bunny''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1517, 0, 'operating-room cart', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1518, 0, 'operating table', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1519, 0, 'organ', 'unorderable', '(Welcome Amiibo) Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1520, 0, 'Otomon egg', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1521, 0, 'outdoor sign', 'unorderable', '(Welcome Amiibo) Huck''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1522, 0, 'overflowing trash', 'unorderable', '(Welcome Amiibo) Resetti''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1523, 0, 'paella', 'unorderable', '(Welcome Amiibo) Cashmere''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1524, 0, 'Palico board', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1525, 0, 'pancakes', 'unorderable', '(Welcome Amiibo) Franklin''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1526, 0, 'pasta', 'unorderable', '(Welcome Amiibo) Wendell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1527, 0, 'pastel low table', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Hopkins'' RV, Lottie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1528, 0, 'PA system', 'unorderable', '(Welcome Amiibo) Isabelle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1529, 0, 'pen-case chair', 'unorderable', '(Welcome Amiibo) DLC (JP)', 'unknown', 'unknown');
insert into acnl_furniture values(1530, 0, 'perfume bottles', 'unorderable', '(Welcome Amiibo) Bitty''s RV, Lottie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1531, 0, 'Piece of Heart', 'unorderable', '(Welcome Amiibo) Epona''s RV, Medli''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1532, 0, 'pile of cash', 'unorderable', '(Welcome Amiibo) Gonzo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1533, 0, 'pitcher plant', 'unorderable', '(Welcome Amiibo) Kicks'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1534, 0, 'plant partition', 'unorderable', '(Welcome Amiibo) Ursala''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1535, 0, 'plastic canister', 'unorderable', '(Welcome Amiibo) Booker''s RV, Boyd''s RV, Copper''s RV, Ike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1536, 0, 'plastic file box', 'unorderable', '(Welcome Amiibo) Dobie''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1537, 0, 'platform', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1538, 0, 'Pompompurin bed', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1539, 0, 'Pompompurin chair', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1540, 0, 'Pompompurin pudding', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1541, 0, 'Pompompurin rack', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1542, 0, 'Pompompurin table', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1543, 0, 'Pompompurin TV', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1544, 0, 'Poogie', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1545, 0, 'popcorn', 'unorderable', '(Welcome Amiibo) Boris'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1546, 0, 'potato gratin', 'unorderable', '(Welcome Amiibo) Franklin''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1547, 0, 'propane tanks', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1548, 0, 'propeller plane', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1549, 0, 'public telephone', 'unorderable', '(Welcome Amiibo) June''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1550, 0, 'pylon set', 'unorderable', '(Welcome Amiibo) Boyd''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1551, 0, 'quilted tapestry', 'unorderable', '(Welcome Amiibo) Mabel''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1552, 0, 'ramen', 'unorderable', '(Welcome Amiibo) Admiral''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1553, 0, 'ramen cup', 'unorderable', '(Welcome Amiibo) Hornsby''s RV, Jacob''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1554, 0, 'reception chair', 'unorderable', '(Welcome Amiibo) Julia''s RV, Piper''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1555, 0, 'reception counter', 'unorderable', '(Welcome Amiibo) June''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1556, 0, 'reception window', 'unorderable', '(Welcome Amiibo) June''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1557, 0, 'record box', 'unorderable', '(Welcome Amiibo) Hornsby''s RV, Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1558, 0, 'red cash register', 'unorderable', '(Welcome Amiibo) Ursala''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1559, 0, 'Red Wing', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1560, 0, 'Re-Tail clock', 'unorderable', '(Welcome Amiibo) Reese''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1561, 0, 'Re-Tail mat', 'unorderable', '(Welcome Amiibo) Reese''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1562, 0, 'retro screen', 'unorderable', '(Welcome Amiibo) Billy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1563, 0, 'retro sign', 'unorderable', '(Welcome Amiibo) Timmy & Tommy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1564, 0, 'retro sink', 'unorderable', '(Welcome Amiibo) Timmy & Tommy''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1565, 0, 'rice bales', 'unorderable', '(Welcome Amiibo) Boots'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1566, 0, 'rice balls', 'unorderable', '(Welcome Amiibo) Tad''s RV, Wendell''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1567, 0, 'right Splatfest sign', 'unorderable', '(Welcome Amiibo) Cece''s RV, Viché''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1568, 0, 'ring', 'unorderable', '(Welcome Amiibo) Bitty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1569, 0, 'ringtoss', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1570, 0, 'roasted dino meat', 'unorderable', '(Welcome Amiibo) Wendell''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1571, 0, 'robot hero', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1572, 0, 'rolling cart', 'unorderable', '(Welcome Amiibo) Cleo''s RV, Cyrus'' RV, Murphy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1573, 0, 'rolling closet', 'unorderable', '(Welcome Amiibo) Cashmere''s RV, Copper''s RV, Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1574, 0, 'rolling file cart', 'unorderable', '(Welcome Amiibo) Cleo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1575, 0, 'round-cloth table', 'unorderable', '(Welcome Amiibo) Julia''s RV, Piper''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1576, 0, 'round cushion', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Hopkins'' RV, Vivian''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1577, 0, 'round electric sign', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1578, 0, 'round pillow', 'unorderable', '(Welcome Amiibo) Jacob''s RV, Stella''s RV, Wade''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1579, 0, 'Rover suitcase', 'unorderable', '(Welcome Amiibo) Rover''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1580, 0, 'Rupee', 'unorderable', '(Welcome Amiibo) Ganon''s RV, Medli''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1581, 0, 'sacks of money', 'unorderable', '(Welcome Amiibo) Tom Nook''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1582, 0, 'sales graph', 'unorderable', '(Welcome Amiibo) Tom Nook''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1583, 0, 'salon chair', 'unorderable', '(Welcome Amiibo) Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1584, 0, 'salon mirror stand', 'unorderable', '(Welcome Amiibo) Tasha''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1585, 0, 'sample case', 'unorderable', '(Welcome Amiibo) Sylvana''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1586, 0, 'sandbox', 'unorderable', '(Welcome Amiibo) DLC (JP)', 'unknown', 'unknown');
insert into acnl_furniture values(1587, 0, 'sapling clock', 'unorderable', '(Welcome Amiibo) Town anniversary gift', 'unknown', 'unknown');
insert into acnl_furniture values(1588, 0, 'sausage', 'unorderable', '(Welcome Amiibo) Julia''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1589, 0, 'scattered papers', 'unorderable', '(Welcome Amiibo) Dobie''s RV, Jacob''s RV, Murphy''s RV, Wendell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1590, 0, 'school locker', 'unorderable', '(Welcome Amiibo) Leopold''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1591, 0, 'scooter', 'unorderable', '(Welcome Amiibo) Stu''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1592, 0, 'serving cart', 'unorderable', '(Welcome Amiibo) Ellie''s RV, Sandy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1593, 0, 'set lunch', 'unorderable', '(Welcome Amiibo) Sylvana''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1594, 0, 'sewing kit', 'unorderable', '(Welcome Amiibo) Mabel''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1595, 0, 'shaved ice', 'unorderable', '(Welcome Amiibo) Olive''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1596, 0, 'shoe boxes', 'unorderable', '(Welcome Amiibo) Kicks'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1597, 0, 'shoe locker', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1598, 0, 'shoe-polishing set', 'unorderable', '(Welcome Amiibo) Kicks'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1599, 0, 'shoji bench', 'unorderable', '(Welcome Amiibo) Toby''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1600, 0, 'shop coffee machine', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1601, 0, 'shop ice-cream case', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1602, 0, 'shop mat', 'unorderable', '(Welcome Amiibo) Timmy & Tommy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1603, 0, 'shopping bag', 'unorderable', '(Welcome Amiibo) Bea''s RV, Candi''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1604, 0, 'silver mic', 'unorderable', '(Welcome Amiibo) Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1605, 0, 'silver teapot', 'unorderable', '(Welcome Amiibo) Ellie''s RV, Piper''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1606, 0, 'simple panel', 'unorderable', '(Welcome Amiibo) Spike''s RV, Timmy & Tommy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1607, 0, 'single rose', 'unorderable', '(Welcome Amiibo) Piper''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1608, 0, 'skateboard rack', 'unorderable', '(Welcome Amiibo) Spike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1609, 0, 'slipper rack', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Mabel''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1610, 0, 'snack machine', 'unorderable', '(Welcome Amiibo) Huck''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1611, 0, 'snare drum', 'unorderable', '(Welcome Amiibo) Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1612, 0, 'soccer goal', 'unorderable', '(Welcome Amiibo) DLC (JP)', 'unknown', 'unknown');
insert into acnl_furniture values(1613, 0, 'sound mixer', 'unorderable', '(Welcome Amiibo) Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1614, 0, 'sparrow''s nest', 'unorderable', '(Welcome Amiibo) Nat''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1615, 0, 'speaker', 'unorderable', '(Welcome Amiibo) Boris'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1616, 0, 'Splatoon spawn point', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1617, 0, 'Splatoon tower', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1618, 0, 'Splattershot', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1619, 0, 'sports car', 'unorderable', '(Welcome Amiibo) Ike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1620, 0, 'square minitable', 'unorderable', '(Welcome Amiibo) Huck''s RV, Spike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1621, 0, 'squid bumper', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1622, 0, 'stacked magazines', 'unorderable', '(Welcome Amiibo) Candi''s RV, Hornsby''s RV, Jacob''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1623, 0, 'stack of books', 'unorderable', '(Welcome Amiibo) Blathers'' RV, Dobie''s RV, Jacob''s RV, Pascal''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1624, 0, 'stack of clothes', 'unorderable', '(Welcome Amiibo) Stella''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1625, 0, 'standing sink', 'unorderable', '(Welcome Amiibo) Cashmere''s RV, Paolo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1626, 0, 'standing TV', 'unorderable', '(Welcome Amiibo) Boris'' RV, Hopkins'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1627, 0, 'steamed lobster', 'unorderable', '(Welcome Amiibo) Julia''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1628, 0, 'stone lantern', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1629, 0, 'store shelf', 'unorderable', '(Welcome Amiibo) Candi''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1630, 0, 'strapped books', 'unorderable', '(Welcome Amiibo) Hornsby''s RV, Leopold''s RV, Rover''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1631, 0, 'stretcher', 'unorderable', '(Welcome Amiibo) Raddle''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1632, 0, 'submarine', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1633, 0, 'succulent plant', 'unorderable', '(Welcome Amiibo) Kicks'' RV, Spike''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1634, 0, 'sun', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1635, 0, 'Super Sea Snail', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1636, 0, 'sushi bench', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)', 'unknown', 'unknown');
insert into acnl_furniture values(1637, 0, 'sushi container', 'unorderable', '(Welcome Amiibo) Chip''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1638, 0, 'sushi menu', 'unorderable', '(Welcome Amiibo) Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1639, 0, 'sushi tray', 'unorderable', '(Welcome Amiibo) Chip''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1640, 0, 'swinging bench', 'unorderable', '(Welcome Amiibo) Maddie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1641, 0, 'synthesizer', 'unorderable', '(Welcome Amiibo) Sprocket''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1642, 0, 'table with cloth', 'unorderable', '(Welcome Amiibo) Julia''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1643, 0, 'tacos', 'unorderable', '(Welcome Amiibo) Wendell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1644, 0, 'tall garden rock', 'unorderable', '(Welcome Amiibo) Boots'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1645, 0, 'tart', 'unorderable', '(Welcome Amiibo) Olive''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1646, 0, 'teacup ride', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1647, 0, 'tennis racket', 'unorderable', '(Welcome Amiibo) Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1648, 0, 'tent', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1649, 0, 'teppanyaki grill', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1650, 0, 'Termina''s moon', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1651, 0, 'theater seat', 'unorderable', '(Welcome Amiibo) Boris'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1652, 0, 'tile screen', 'unorderable', '(Welcome Amiibo) Saharah''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1653, 0, 'tin watering can', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1654, 0, 'tire stack', 'unorderable', '(Welcome Amiibo) Ike''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1655, 0, 'tong-and-tray stand', 'unorderable', '(Welcome Amiibo) Bea''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1656, 0, 'toolbox', 'unorderable', '(Welcome Amiibo) Ike''s RV, Kicks'' RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1657, 0, 'tool cart', 'unorderable', '(Welcome Amiibo) Cyrus'' RV, Ike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1658, 0, 'tool shelf', 'unorderable', '(Welcome Amiibo) Ike''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1659, 0, 'tool stand', 'unorderable', '(Welcome Amiibo) Cyrus'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1660, 0, 'towel basket', 'unorderable', '(Welcome Amiibo) Paolo''s RV, Plucky''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1661, 0, 'towel rack', 'unorderable', '(Welcome Amiibo) Leopold''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1662, 0, 'toy piano', 'unorderable', '(Welcome Amiibo) Carrie''s RV, Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1663, 0, 'tractor', 'unorderable', '(Welcome Amiibo) Tad''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1664, 0, 'train seat', 'unorderable', '(Welcome Amiibo) Rover''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1665, 0, 'tranquil bridge', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_furniture values(1666, 0, 'trash bags', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Hornsby''s RV, Jacob''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1667, 0, 'trellis', 'unorderable', '(Welcome Amiibo) Boots'' RV', 'unknown', 'unknown');
insert into acnl_furniture values(1668, 0, 'trumpet', 'unorderable', '(Welcome Amiibo) Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1669, 0, 'udon soup', 'unorderable', '(Welcome Amiibo) Sylvana''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1670, 0, 'UFO', 'unorderable', '(Welcome Amiibo) Happy Home Designer save data', 'unknown', 'unknown');
insert into acnl_furniture values(1671, 0, 'umbrella stand', 'unorderable', '(Welcome Amiibo) June''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1672, 0, 'unicycle', 'unorderable', '(Welcome Amiibo) Tybalt''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1673, 0, 'video camera', 'unorderable', '(Welcome Amiibo) Murphy''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1674, 0, 'villager statue', 'unorderable', '(Welcome Amiibo) Villager''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1675, 0, 'waiting-room bench', 'unorderable', '(Welcome Amiibo) June''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1676, 0, 'wall-mounted TV', 'unorderable', '(Welcome Amiibo) Resetti''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1677, 0, 'warming buffet', 'unorderable', '(Welcome Amiibo) Julia''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1678, 0, 'watermelon', 'unorderable', '(Welcome Amiibo) Plucky''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1679, 0, 'water pot', 'unorderable', '(Welcome Amiibo) Sylvana''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1680, 0, 'Wendell''s painting', 'unorderable', '(Welcome Amiibo) Wendell''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1681, 0, 'white festive tree', 'unorderable', '(Welcome Amiibo) DLC (JP)', 'unknown', 'unknown');
insert into acnl_furniture values(1682, 0, 'white office desk', 'unorderable', '(Welcome Amiibo) Cleo''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1683, 0, 'whole pizza', 'unorderable', '(Welcome Amiibo) Ketchup''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1684, 0, 'Wii remote cabinet', 'unorderable', '(Welcome Amiibo) Villager''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1685, 0, 'Wii U console', 'unorderable', '(Welcome Amiibo) Celeste''s RV, Cyrus'' RV, Digby''s RV, Hopkins'' RV, Isabelle''s RV, K.K''s RV, Kapp''n''s RV, Kicks'' RV, Lottie''s RV, Mabel''s RV, Reese''s RV, Resetti''s RV, Rover''s RV, Timmy & Tommy''s RV, Tom Nook''s RV, Villager''s RV, Fortune cookie #51, Fortune cookie #52', 'unknown', 'unknown');
insert into acnl_furniture values(1686, 0, 'Wii U game shelf', 'unorderable', '(Welcome Amiibo) Clear all intermediate levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1687, 0, 'Wii U station', 'unorderable', '(Welcome Amiibo) Clear all beginner levels in Desert Island Escape', 'unknown', 'unknown');
insert into acnl_furniture values(1688, 0, 'wood display stand', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Jack''s RV, Norma''s RV, Rex''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1689, 0, 'wooden bear', 'unorderable', '(Welcome Amiibo) Wade''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1690, 0, 'wooden bucket', 'unorderable', '(Welcome Amiibo) Maggie''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1691, 0, 'wooden counter', 'unorderable', '(Welcome Amiibo) Bea''s RV, Bitty''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1692, 0, 'wooden duckboards', 'unorderable', '(Welcome Amiibo) Louie''s RV, Paolo''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1693, 0, 'wood-plank table', 'unorderable', '(Welcome Amiibo) Kapp''n''s RV, Snooty''s RV, Ursala''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1694, 0, 'worktable', 'unorderable', '(Welcome Amiibo) Buzz''s RV, Cyrus'' RV, Ketchup''s RV, Norma''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1695, 0, 'Wyvern eggs', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1696, 0, 'xylophone', 'unorderable', '(Welcome Amiibo) Weber''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1697, 0, 'yarn basket', 'unorderable', '(Welcome Amiibo) Mabel''s RV, Stella''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1698, 0, 'zen backpack', 'unorderable', '(Welcome Amiibo) Leopold''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1699, 0, 'zen barrel', 'unorderable', '(Welcome Amiibo) Boots'' RV, Tad''s RV, Harvey''s shop', 'unknown', 'unknown');
insert into acnl_furniture values(1700, 0, 'zen chair', 'unorderable', '(Welcome Amiibo) Blathers'' RV, Sylvana''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1701, 0, 'zen cupboard', 'unorderable', '(Welcome Amiibo) Snooty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1702, 0, 'zen cushion', 'unorderable', '(Welcome Amiibo) Snooty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1703, 0, 'zen desk', 'unorderable', '(Welcome Amiibo) Hornsby''s RV, Snooty''s RV', 'unknown', 'unknown');
insert into acnl_furniture values(1704, 0, 'zen low table', 'unorderable', '(Welcome Amiibo) Billy''s RV, Timmy & Tommy''s RV, Wade''s RV', 'unknown', 'unknown');
insert into acnl_hat values(213, 0, 'Callie wig', 'unorderable', '(Welcome Amiibo) Cece''s RV', 'unknown', 'unknown');
insert into acnl_hat values(214, 0, 'Celeste ribbon', 'unorderable', '(Welcome Amiibo) Celeste''s RV', 'unknown', 'unknown');
insert into acnl_hat values(215, 0, 'Cinnamoroll hat', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_hat values(216, 0, 'driver''s hat', 'unorderable', '(Welcome Amiibo) Kapp''n''s RV', 'unknown', 'unknown');
insert into acnl_hat values(217, 0, 'Flower Fairy wig', 'unorderable', '(Welcome Amiibo) Obtain at least 10,000 points in Garbage Attack on any difficulty in Puzzle League', 'unknown', 'unknown');
insert into acnl_hat values(218, 0, 'Ganondorf wig', 'unorderable', '(Welcome Amiibo) Ganon''s RV', 'unknown', 'unknown');
insert into acnl_hat values(219, 0, 'Hello Kitty hat', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_hat values(220, 0, 'high-spirits hat', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_hat values(221, 0, 'Kerokerokeroppi pins', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_hat values(222, 0, 'Kiki and Lala pin', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_hat values(223, 0, 'Link hat', 'unorderable', '(Welcome Amiibo) Ganon''s RV, Epona''s RV, Medli''s RV, Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_hat values(224, 0, 'Lottie''s bun', 'unorderable', '(Welcome Amiibo) Lottie''s RV', 'unknown', 'unknown');
insert into acnl_hat values(225, 0, 'Marie wig', 'unorderable', '(Welcome Amiibo) Viché''s RV', 'unknown', 'unknown');
insert into acnl_hat values(226, 0, 'My Melody hat', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_hat values(227, 0, 'Nabiru mask', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_hat values(228, 0, 'new hero wig', 'unorderable', '(Welcome Amiibo) Ganon''s RV, Epona''s RV, Medli''s RV, Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_hat values(229, 0, 'pilot goggles', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_hat values(230, 0, 'Pompompurin hat', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_hat values(231, 0, 'Sheik mask', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_hat values(232, 0, 'studio headphones', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_hat values(233, 0, 'Takoroka mesh', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_hat values(234, 0, 'Zelda wig', 'unorderable', '(Welcome Amiibo) Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(450, 0, 'black anchor tee', 'unorderable', '(Welcome Amiibo) Inkwell''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(451, 0, 'blue nurse''s uniform', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(452, 0, 'Callie fashion top', 'unorderable', '(Welcome Amiibo) Cece''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(453, 0, 'Callie shirt', 'unorderable', '(Welcome Amiibo) Cece''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(454, 0, 'Cinnamoroll jacket', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(455, 0, 'Cinnamoroll outfit', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(456, 0, 'comedian''s outfit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(457, 0, 'Epona outfit', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(458, 0, 'Felyne outfit', 'unorderable', '(Welcome Amiibo) Felyne''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(459, 0, 'flashy suit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(460, 0, 'frilly apron', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(461, 0, 'Ganondorf outfit', 'unorderable', '(Welcome Amiibo) Ganon''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(462, 0, 'Ganon outfit', 'unorderable', '(Welcome Amiibo) Ganon''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(463, 0, 'good-fortune clothes', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(464, 0, 'Hello Kitty outfit', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(465, 0, 'HHA raincoat', 'unorderable', '(Welcome Amiibo) Digby''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(466, 0, 'HHA women''s jacket', 'unorderable', '(Welcome Amiibo) Lottie''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(467, 0, 'high-spirits shirt', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)', 'unknown', 'unknown');
insert into acnl_shirt values(468, 0, 'jacquard fleece', 'unorderable', '(Welcome Amiibo) Lottie''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(469, 0, 'Kerokerokeroppi top', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(470, 0, 'Kiki and Lala outfit', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(471, 0, 'Link outfit', 'unorderable', '(Welcome Amiibo) Ganon''s RV, Epona''s RV, Medli''s RV, Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(472, 0, 'Marie shirt', 'unorderable', '(Welcome Amiibo) Viché''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(473, 0, 'Medli outfit', 'unorderable', '(Welcome Amiibo) Medli''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(474, 0, 'men''s recruit suit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(475, 0, 'My Melody outfit', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(476, 0, 'new hero''s outfit', 'unorderable', '(Welcome Amiibo) Ganon''s RV, Epona''s RV, Medli''s RV, Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(477, 0, 'polo shirt', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(478, 0, 'Pompompurin outfit', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(479, 0, 'rubber apron', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(480, 0, 'Sheik outfit', 'unorderable', '(Welcome Amiibo) Epona''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(481, 0, 'stylish suit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(482, 0, 'sushi chef''s outfit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(483, 0, 'suspenders shirt', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)', 'unknown', 'unknown');
insert into acnl_shirt values(484, 0, 'town-hall spring top', 'unorderable', '(Welcome Amiibo) Isabelle''s RV (Summer outfit amiibo)', 'unknown', 'unknown');
insert into acnl_shirt values(485, 0, 'town-hall winter top', 'unorderable', '(Welcome Amiibo) Isabelle''s RV (Winter outfit amiibo)', 'unknown', 'unknown');
insert into acnl_shirt values(486, 0, 'Wolf Link outfit', 'unorderable', '(Welcome Amiibo) Wolf Link''s RV', 'unknown', 'unknown');
insert into acnl_shirt values(487, 0, 'women''s office suit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_shirt values(488, 0, 'women''s recruit suit', 'unorderable', '(Welcome Amiibo) Able Sisters', 'unknown', 'unknown');
insert into acnl_tool values(121, 0, 'fruit-panel umbrella', '(Welcome Amiibo) Complete Story Mode on Slightly Harder difficulty in Puzzle League');
insert into acnl_wallpaper values(125, 0, 'bamboo-grove wall', 'unorderable', '(Welcome Amiibo) Boots'' RV');
insert into acnl_wallpaper values(126, 0, 'basic wall', 'unorderable', '(Welcome Amiibo) Louie''s RV');
insert into acnl_wallpaper values(127, 0, 'café-curtain wall', 'unorderable', '(Welcome Amiibo) Ellie''s RV');
insert into acnl_wallpaper values(128, 0, 'Cinnamoroll wall', 'unorderable', '(Welcome Amiibo) Chai''s RV (Sanrio)');
insert into acnl_wallpaper values(129, 0, 'convenient wall', 'unorderable', '(Welcome Amiibo) Filly''s RV (7-Eleven)');
insert into acnl_wallpaper values(130, 0, 'fruit-panel wall', 'unorderable', '(Welcome Amiibo) Play more Story Mode in Puzzle League');
insert into acnl_wallpaper values(131, 0, 'Fueki wall', 'unorderable', '(Welcome Amiibo) Holden''s RV (Fueki)');
insert into acnl_wallpaper values(132, 0, 'hallway wall', 'unorderable', '(Welcome Amiibo) Boris'' RV, Gonzo''s RV');
insert into acnl_wallpaper values(133, 0, 'Hello Kitty wall', 'unorderable', '(Welcome Amiibo) Rilla''s RV (Sanrio)');
insert into acnl_wallpaper values(134, 0, 'Hyrule wall', 'unorderable', '(Welcome Amiibo) Epona''s RV, Ganon''s RV, Medli''s RV, Wolf Link''s RV');
insert into acnl_wallpaper values(135, 0, 'Inkopolis wall', 'unorderable', '(Welcome Amiibo) Cece''s RV, Viché''s RV');
insert into acnl_wallpaper values(136, 0, 'ink-splattered wall', 'unorderable', '(Welcome Amiibo) Inkwell''s RV');
insert into acnl_wallpaper values(137, 0, 'Kerokerokeroppi wall', 'unorderable', '(Welcome Amiibo) Toby''s RV (Sanrio)');
insert into acnl_wallpaper values(138, 0, 'Kiki and Lala wall', 'unorderable', '(Welcome Amiibo) Étoile''s RV (Sanrio)');
insert into acnl_wallpaper values(139, 0, 'magma-cavern wall', 'unorderable', '(Welcome Amiibo) Felyne''s RV');
insert into acnl_wallpaper values(140, 0, 'My Melody wall', 'unorderable', '(Welcome Amiibo) Chelsea''s RV (Sanrio)');
insert into acnl_wallpaper values(141, 0, 'ocean-horizon wall', 'unorderable', '(Welcome Amiibo) Unlock intermediate levels in Desert Island Escape');
insert into acnl_wallpaper values(142, 0, 'polka-dot wall', 'unorderable', '(Welcome Amiibo) Lottie''s RV');
insert into acnl_wallpaper values(143, 0, 'Pompompurin wall', 'unorderable', '(Welcome Amiibo) Marty''s RV (Sanrio)');
insert into acnl_wallpaper values(144, 0, 'rice-paddy wall', 'unorderable', '(Welcome Amiibo) Tad''s RV');
insert into acnl_wallpaper values(145, 0, 'stadium wall', 'unorderable', '(Welcome Amiibo) Sprocket''s RV');
insert into acnl_wallpaper values(146, 0, 'steel-frame wall', 'unorderable', '(Welcome Amiibo) Ike''s RV');
insert into acnl_wallpaper values(147, 0, 'train-window wall', 'unorderable', '(Welcome Amiibo) Rover''s RV');
insert into acnl_wallpaper values(148, 0, 'waiting-room wall', 'unorderable', '(Welcome Amiibo) Huck''s RV, June''s RV');
insert into acnl_wallpaper values(149, 0, 'white brick wall', 'unorderable', '(Welcome Amiibo) Blanca''s RV, K.K.''s RV, Norma''s RV, Vivian''s RV');
insert into acnl_wallpaper values(150, 0, 'white tile wall', 'unorderable', '(Welcome Amiibo) Paolo''s RV');
