update acgc_insect set "Times" = 'April through September, 8am to 4pm' where "Index" = 3;
insert into acgc_may_insect values (3);
insert into acgc_jun_insect values (3);
insert into acgc_jul_insect values (3);
insert into acgc_aug1_insect values (3);
insert into acgc_aug2_insect values (3);
insert into acgc_sep1_insect values (3);
insert into acgc_sep2_insect values (3);
insert into acgc_shirt values(257, 0, 'Houndstooth Knit', 'orderable', '?', 'winter');
update acgc_shirt set "Name" = 'Toad Print' where "Index" = 242;
insert into acgc_wallpaper values(68, 0, 'Backyard Fence', 'orderable', '?');