drop table if exists acnh_table;
create table acnh_table ("Table" varchar(63));
insert into acnh_table values ('fish'), ('insect');
drop table if exists acnh_fish;
create table acnh_fish ("Index" int primary key, Selected int, Name varchar(50), Price varchar(50), "From" varchar(50), Shadow varchar(50), Times varchar(200));
insert into acnh_fish values(1, 0, 'Bitterling', '900', 'River', 'tiny', 'All day');
insert into acnh_fish values(2, 0, 'Pale chub', '160', 'River', 'tiny', '9 AM to 4 PM');
insert into acnh_fish values(3, 0, 'Crucian carp', '160', 'River', 'small', 'All day');
insert into acnh_fish values(4, 0, 'Dace', '240', 'River', 'medium', '4 PM to 9 AM');
insert into acnh_fish values(5, 0, 'Carp', '300', 'Pond', 'large', 'All day');
insert into acnh_fish values(6, 0, 'Koi', '4,000', 'Pond', 'large', '4 PM to 9 AM');
insert into acnh_fish values(7, 0, 'Goldfish', '1,300', 'Pond', 'tiny', 'All day');
insert into acnh_fish values(8, 0, 'Pop-eyed Goldfish', '1,300', 'Pond', 'tiny', '9 AM to 4 PM');
insert into acnh_fish values(9, 0, 'Ranchu Goldfish', '4,500', 'Pond', 'small', '9 AM to 4 PM');
insert into acnh_fish values(10, 0, 'Killifish', '?', 'Pond', 'tiny', 'All day');
insert into acnh_fish values(11, 0, 'Crawfish', '200', 'Pond', 'medium', 'All day');
insert into acnh_fish values(12, 0, 'Soft-shelled Turtle', '3,750', 'River', '?', '4 PM to 9 AM');
insert into acnh_fish values(13, 0, 'Snapping Turtle', '5,000', 'River', '?', '9 PM to 4 AM');
insert into acnh_fish values(14, 0, 'Tadpole', '100', 'Pond', 'tiny', 'All day');
insert into acnh_fish values(15, 0, 'Frog', '?', 'Pond', 'small', 'All day');
insert into acnh_fish values(16, 0, 'Freshwater Goby', '400', 'River', 'small', '4 PM to 9 AM');
insert into acnh_fish values(17, 0, 'Loach', '400', 'River', 'small', 'All day');
insert into acnh_fish values(18, 0, 'Catfish', '800', 'Pond', '?', '4 PM to 9 AM');
insert into acnh_fish values(19, 0, 'Giant snakehead', '?', 'Pond', 'very large', '9 AM to 4 PM');
insert into acnh_fish values(20, 0, 'Bluegill', '180', 'River', 'small', '9 AM to 4 PM');
insert into acnh_fish values(21, 0, 'Yellow perch', '300', 'River', 'medium', 'All day');
insert into acnh_fish values(22, 0, 'Black bass', '400', 'River', 'large', 'All day');
insert into acnh_fish values(23, 0, 'Tilapia', '800', 'River', '?', 'All day');
insert into acnh_fish values(24, 0, 'Pike', '1,800', 'River', 'very large', 'All day');
insert into acnh_fish values(25, 0, 'Pond smelt', '?', 'River', 'small', 'All day');
insert into acnh_fish values(26, 0, 'Sweetfish', '900', 'River', 'medium', 'All day');
insert into acnh_fish values(27, 0, 'Cherry Salmon', '1,000', 'River (Clifftop)/River', 'medium', '4 PM to 9 AM');
insert into acnh_fish values(28, 0, 'Char', '3,800', 'River (Clifftop) / River / Pond', 'medium', '4 PM to 9 AM');
insert into acnh_fish values(29, 0, 'Golden Trout', '15,000', 'River (Clifftop)', 'large', '4 PM to 9 AM');
insert into acnh_fish values(30, 0, 'Stringfish', '15,000', 'River (Clifftop)', 'huge', '4 PM to 9 AM');
insert into acnh_fish values(31, 0, 'Salmon', '700', 'River (Mouth)', 'large', 'All day');
insert into acnh_fish values(32, 0, 'King Salmon', '1,800', 'River (Mouth)', 'huge', 'All day');
insert into acnh_fish values(33, 0, 'Mitten Crab', '2,000', 'River', 'small', '4 PM to 9 AM');
insert into acnh_fish values(34, 0, 'Guppy', '?', 'River', 'tiny', '9 AM to 4 PM');
insert into acnh_fish values(35, 0, 'Nibble Fish', '1,500', 'River', 'small', '9 AM to 4 PM');
insert into acnh_fish values(36, 0, 'Angelfish', '3,000', 'River', 'small', '4 PM to 9 AM');
insert into acnh_fish values(37, 0, 'Betta', '2,500', 'River', 'small', '9 AM to 4 PM');
insert into acnh_fish values(38, 0, 'Neon tetra', '500', 'River', 'tiny', '9 AM to 4 PM');
insert into acnh_fish values(39, 0, 'Rainbowfish', '800', 'River', 'small', '9 AM to 4 PM');
insert into acnh_fish values(40, 0, 'Piranha', '2,500', 'River', 'small', '9 AM to 4 PM & 9 PM');
insert into acnh_fish values(41, 0, 'Arowana', '10,000', 'River', 'large', '4 PM');
insert into acnh_fish values(42, 0, 'Dorado', '15,000', 'River', 'very large', '4 AM');
insert into acnh_fish values(43, 0, 'Gar', '6,000', 'Pond', 'huge', '4 PM');
insert into acnh_fish values(44, 0, 'Arapaima', '10,000', 'River', '?', '4 PM');
insert into acnh_fish values(45, 0, 'Saddled Bichir', '4,000', 'River', 'large', '9 PM');
insert into acnh_fish values(46, 0, 'Sturgeon', '10,000', 'River (Mouth)', 'huge', 'All day');
insert into acnh_fish values(47, 0, 'Sea butterfly', '1,000', 'Sea', 'tiny', 'All day');
insert into acnh_fish values(48, 0, 'Seahorse', '1,100', 'Sea', 'tiny', 'All day');
insert into acnh_fish values(49, 0, 'Clownfish', '650', 'Sea', 'tiny', 'All day');
insert into acnh_fish values(50, 0, 'Surgeonfish', '1,000', 'Sea', 'small', 'All day');
insert into acnh_fish values(51, 0, 'Butterfly fish', '1,000', 'Sea', 'small', 'All day');
insert into acnh_fish values(52, 0, 'Napoleonfish', '10,000', 'Sea', 'huge', '4 AM to 9 PM');
insert into acnh_fish values(53, 0, 'Zebra turkeyfish', '500', 'Sea', 'medium', 'All day');
insert into acnh_fish values(54, 0, 'Blowfish', '?', 'Sea', 'medium', '6PM to 4AM');
insert into acnh_fish values(55, 0, 'Puffer fish', '250', 'Sea', 'medium', 'All day');
insert into acnh_fish values(56, 0, 'Anchovy', '200', 'Sea', 'small', '4 AM to 9 PM');
insert into acnh_fish values(57, 0, 'Horse mackerel', '150', 'Sea', 'small', 'All day');
insert into acnh_fish values(58, 0, 'Barred knifejaw', '5,000', 'Sea', 'medium', 'All day');
insert into acnh_fish values(59, 0, 'Sea bass', '400', 'Sea', 'very large', 'All day');
insert into acnh_fish values(60, 0, 'Red snapper', '3,000', 'Sea', 'medium', 'All day');
insert into acnh_fish values(61, 0, 'Dab', '300', 'Sea', 'medium', 'All day');
insert into acnh_fish values(62, 0, 'Olive Flounder', '800', 'Sea', 'large', 'All day');
insert into acnh_fish values(63, 0, 'Squid', '500', 'Sea', 'medium', 'All day');
insert into acnh_fish values(64, 0, 'Moray eel', '2,000', 'Sea', 'very large', 'All day');
insert into acnh_fish values(65, 0, 'Ribbon Eel', '600', 'Sea', 'Narrow', 'All day');
insert into acnh_fish values(66, 0, 'Tuna', '7,000', 'Pier', 'huge', 'All day');
insert into acnh_fish values(67, 0, 'Blue marlin', '10,000', 'Pier', 'huge', 'All day');
insert into acnh_fish values(68, 0, 'Giant Trevally', '?', 'Pier', 'very large', 'All day');
insert into acnh_fish values(69, 0, 'Mahi-mahi', '6,000', 'Pier', 'very large', 'All day');
insert into acnh_fish values(70, 0, 'Ocean Sunfish', '4,000', 'Sea', '? with fin', '4 AM to 9 PM');
insert into acnh_fish values(71, 0, 'Ray', '3,000', 'Sea', 'very large', '4 AM to 9 PM');
insert into acnh_fish values(72, 0, 'Saw Shark', '12,000', 'Sea', 'huge with fin', '4 PM to 9 AM');
insert into acnh_fish values(73, 0, 'Hammerhead Shark', '8,000', 'Sea', 'huge with fin', '4 PM to 9 AM');
insert into acnh_fish values(74, 0, 'Shark', '15,000', 'Sea', 'huge with fin', '4 PM to 9 AM');
insert into acnh_fish values(75, 0, 'Whale shark', '13,000', 'Sea', 'huge with fin', 'All day');
insert into acnh_fish values(76, 0, 'Suckerfish', '1,500', 'Sea', '? with fin', 'All day');
insert into acnh_fish values(77, 0, 'Football Fish', '2,500', 'Sea', 'large', '4 PM to 9 AM');
insert into acnh_fish values(78, 0, 'Oarfish', '9,000', 'Sea', 'huge', 'All day');
insert into acnh_fish values(79, 0, 'Barreleye', '15,000', 'Sea', 'small', '9 PM to 4 AM');
insert into acnh_fish values(80, 0, 'Coelacanth', '15,000', 'Sea (Raining)', 'huge', 'All day');
drop table if exists acnh_insect;
create table acnh_insect ("Index" int primary key, Selected int, Name varchar(50), Price varchar(15), "From" varchar(50), Times varchar(200));
insert into acnh_insect values(1, 0, 'Common butterfly', '160', 'Flying', '4 AM to 7 PM');
insert into acnh_insect values(2, 0, 'Yellow butterfly', '160', 'Flying', '4 AM to 7 PM');
insert into acnh_insect values(3, 0, 'Tiger butterfly', '240', 'Flying', '4 AM to 7 PM');
insert into acnh_insect values(4, 0, 'Peacock butterfly', '2,500', 'Flying', '4 AM to 7 PM');
insert into acnh_insect values(5, 0, 'Common bluebottle', '300', 'Flying', '4 AM to 7 PM');
insert into acnh_insect values(6, 0, 'Paper kite butterfly', '1,000', 'Flying', '8 AM to 7 PM');
insert into acnh_insect values(7, 0, 'Great purple emperor', '?', 'Flying', '4 AM to 7 PM');
insert into acnh_insect values(8, 0, 'Monarch butterfly', '140', 'Flying', '4 AM to 5 PM');
insert into acnh_insect values(9, 0, 'Emperor butterfly', '4000', 'Flying', '5 PM to 8 AM');
insert into acnh_insect values(10, 0, 'Agrias butterfly', '3000', 'Flying', '8 AM to 5 PM');
insert into acnh_insect values(11, 0, 'Rajah Brooke''s Birdwing', '2500', 'Flying', '8 AM to 5 PM');
insert into acnh_insect values(12, 0, 'Queen Alexandra''s birdwing', '4000', 'Flying', '8 AM to 4 PM');
insert into acnh_insect values(13, 0, 'Moth', '130', 'Flying by light', '7 PM to 4 AM');
insert into acnh_insect values(14, 0, 'Atlas moth', '3000', 'On Trees', '7 PM to 4 AM');
insert into acnh_insect values(15, 0, 'Madagascan sunset moth', '2500', 'Flying', '8 AM to 4 PM');
insert into acnh_insect values(16, 0, 'Long locust', '200', 'Hopping', '8 AM to 7 PM');
insert into acnh_insect values(17, 0, 'Migratory locust', '600', 'Hopping', '8 AM to 7 PM');
insert into acnh_insect values(18, 0, 'Rice grasshopper', '160', 'Hopping', '8 AM to 7 PM');
insert into acnh_insect values(19, 0, 'Grasshopper', '160', 'Hopping', '8 AM to 5 PM');
insert into acnh_insect values(20, 0, 'Cricket', '130', 'Hopping', '5 PM to 8 AM');
insert into acnh_insect values(21, 0, 'Bell cricket', '430', 'Hopping', '5 PM to 8 AM');
insert into acnh_insect values(22, 0, 'Mantis', '430', 'On Flowers', '8 AM to 5 PM');
insert into acnh_insect values(23, 0, 'Orchid mantis', '2400', 'On flowers (white)', '8 AM to 5 PM');
insert into acnh_insect values(24, 0, 'Honeybee', '200', 'Flying', '8 AM to 5 PM');
insert into acnh_insect values(25, 0, 'Wasp', '2,500', 'Shake tree', 'All day');
insert into acnh_insect values(26, 0, 'Brown cicada', '?', 'On Trees', '8 AM to 5 PM');
insert into acnh_insect values(27, 0, 'Robust cicada', '?', 'On Trees', '8 AM to 5 PM');
insert into acnh_insect values(28, 0, 'Giant cicada', '?', 'On Trees', '8 AM to 5 PM');
insert into acnh_insect values(29, 0, 'Walker cicada', '400', 'On Trees', '8 AM to 5 PM');
insert into acnh_insect values(30, 0, 'Evening cicada', '?', 'On Trees', '4 AM to 8 AM and 4 PM to 7 PM');
insert into acnh_insect values(31, 0, 'Cicada shell', '?', 'On Trees', 'All day');
insert into acnh_insect values(32, 0, 'Red dragonfly', '180', 'Flying', '8 AM to 7 PM');
insert into acnh_insect values(33, 0, 'Darner dragonfly', '230', 'Flying', '8 AM to 5 PM');
insert into acnh_insect values(34, 0, 'Banded dragonfly', '4,500', 'Flying', '8 AM to 5 PM');
insert into acnh_insect values(35, 0, 'Damselfly', '?', 'Flying', 'All day');
insert into acnh_insect values(36, 0, 'Firefly', '?', 'Flying', '7 PM to 4 AM');
insert into acnh_insect values(37, 0, 'Mole cricket', '500', 'Underground', 'All day');
insert into acnh_insect values(38, 0, 'Pondskater', '130', 'On Ponds', '8 AM to 7 PM');
insert into acnh_insect values(39, 0, 'Diving beetle', '800', 'On Ponds and Rivers', '8 AM to 7 PM');
insert into acnh_insect values(40, 0, 'Giant water bug', '2,000', 'On Ponds and Rivers', '7 PM to 8 AM');
insert into acnh_insect values(41, 0, 'Stinkbug', '120', 'On flowers', 'All day');
insert into acnh_insect values(42, 0, 'Man-faced stink bug', '1,000', 'On flowers', '7 PM to 8 AM');
insert into acnh_insect values(43, 0, 'Ladybug', '200', 'On flowers', '8 AM to 5 PM');
insert into acnh_insect values(44, 0, 'Tiger beetle', '1,500', 'On the ground', 'All day');
insert into acnh_insect values(45, 0, 'Jewel beetle', '2,400', 'On Trees', 'All day');
insert into acnh_insect values(46, 0, 'Violin beetle', '450', 'On a tree stump', 'All day');
insert into acnh_insect values(47, 0, 'Citrus Long-horned Beetle', '350', 'On a tree stump', 'All day');
insert into acnh_insect values(48, 0, 'Rosalia batesi beetle', 'o', 'o', 'All day');
insert into acnh_insect values(49, 0, 'Blue weevil beetle', '?', '?', 'All day');
insert into acnh_insect values(50, 0, 'Dung beetle', '?', '?', '?');
insert into acnh_insect values(51, 0, 'Earth-boring Dung Beetle', '300', 'On Ground', 'All day');
insert into acnh_insect values(52, 0, 'Scarab beetle', '?', 'On Tree', '11 PM to 8 AM');
insert into acnh_insect values(53, 0, 'Drone beetle', '?', 'On Tree', 'All day');
insert into acnh_insect values(54, 0, 'Goliath beetle', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(55, 0, 'Saw stag', '?', 'On Trees', 'All day');
insert into acnh_insect values(56, 0, 'Miyama stag', '?', 'On Trees', 'All day');
insert into acnh_insect values(57, 0, 'Giant stag', '?', 'On Trees', '11 PM to 8 AM');
insert into acnh_insect values(58, 0, 'Rainbow stag', '?', 'On Trees', '7 PM to 8 AM');
insert into acnh_insect values(59, 0, 'Cyclommatus stag', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(60, 0, 'Golden stag', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(61, 0, 'Giraffe stag', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(62, 0, 'Horned dynastid', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(63, 0, 'Horned atlas', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(64, 0, 'Horned elephant', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(65, 0, 'Horned hercules', '?', 'On Trees', '5 PM to 8 AM');
insert into acnh_insect values(66, 0, 'Walking stick', '?', 'Shaking Tree', '4 AM to 8 AM and 5 PM to 7 PM');
insert into acnh_insect values(67, 0, 'Walking leaf', '600', 'Under Trees Disguised as Leafs', 'All day');
insert into acnh_insect values(68, 0, 'Bagworm', '600', 'In trees', 'All day');
insert into acnh_insect values(69, 0, 'Ant', '?', 'On rotten food', 'All day');
insert into acnh_insect values(70, 0, 'Hermit crab', '1,000', 'Beach', '7 PM to 8 AM');
insert into acnh_insect values(71, 0, 'Wharf roach', '200', 'On beach rocks', 'All day');
insert into acnh_insect values(72, 0, 'Fly', '?', 'On trash items', 'All Day');
insert into acnh_insect values(73, 0, 'Mosquito', '130', 'Flying', '5 PM to 4 AM');
insert into acnh_insect values(74, 0, 'Flea', '?', 'Villager''s Heads', 'All day');
insert into acnh_insect values(75, 0, 'Snail', '250', 'On rocks when raining', 'All day');
insert into acnh_insect values(76, 0, 'Pill bug', '250', 'Hit a rock', '11 PM to 4 PM');
insert into acnh_insect values(77, 0, 'Centipede', '300', 'Hit a rock', '4 PM to 11 PM');
insert into acnh_insect values(78, 0, 'Spider', '480', 'Shake a tree', '7 PM to 8 AM');
insert into acnh_insect values(79, 0, 'Tarantula', '8,000', 'On the ground', '7 PM to 4 AM');
insert into acnh_insect values(80, 0, 'Scorpion', '8000', 'On the ground', '7 PM to 4 AM');
drop table if exists acnh_jan_fish;
drop table if exists acnh_feb_fish;
drop table if exists acnh_mar_fish;
drop table if exists acnh_apr_fish;
drop table if exists acnh_may_fish;
drop table if exists acnh_jun_fish;
drop table if exists acnh_jul_fish;
drop table if exists acnh_aug1_fish;
drop table if exists acnh_aug2_fish;
drop table if exists acnh_sep1_fish;
drop table if exists acnh_sep2_fish;
drop table if exists acnh_oct_fish;
drop table if exists acnh_nov_fish;
drop table if exists acnh_dec_fish;
create table acnh_jan_fish (id int);
create table acnh_feb_fish (id int);
create table acnh_mar_fish (id int);
create table acnh_apr_fish (id int);
create table acnh_may_fish (id int);
create table acnh_jun_fish (id int);
create table acnh_jul_fish (id int);
create table acnh_aug1_fish (id int);
create table acnh_aug2_fish (id int);
create table acnh_sep1_fish (id int);
create table acnh_sep2_fish (id int);
create table acnh_oct_fish (id int);
create table acnh_nov_fish (id int);
create table acnh_dec_fish (id int);
insert into acnh_jan_fish values (1);
insert into acnh_feb_fish values (1);
insert into acnh_mar_fish values (1);
insert into acnh_nov_fish values (1);
insert into acnh_dec_fish values (1);
insert into acnh_jan_fish values (2);
insert into acnh_feb_fish values (2);
insert into acnh_mar_fish values (2);
insert into acnh_apr_fish values (2);
insert into acnh_may_fish values (2);
insert into acnh_jun_fish values (2);
insert into acnh_jul_fish values (2);
insert into acnh_aug1_fish values (2);
insert into acnh_sep1_fish values (2);
insert into acnh_oct_fish values (2);
insert into acnh_nov_fish values (2);
insert into acnh_dec_fish values (2);
insert into acnh_jan_fish values (3);
insert into acnh_feb_fish values (3);
insert into acnh_mar_fish values (3);
insert into acnh_apr_fish values (3);
insert into acnh_may_fish values (3);
insert into acnh_jun_fish values (3);
insert into acnh_jul_fish values (3);
insert into acnh_aug1_fish values (3);
insert into acnh_sep1_fish values (3);
insert into acnh_oct_fish values (3);
insert into acnh_nov_fish values (3);
insert into acnh_dec_fish values (3);
insert into acnh_jan_fish values (4);
insert into acnh_feb_fish values (4);
insert into acnh_mar_fish values (4);
insert into acnh_apr_fish values (4);
insert into acnh_may_fish values (4);
insert into acnh_jun_fish values (4);
insert into acnh_jul_fish values (4);
insert into acnh_aug1_fish values (4);
insert into acnh_sep1_fish values (4);
insert into acnh_oct_fish values (4);
insert into acnh_nov_fish values (4);
insert into acnh_dec_fish values (4);
insert into acnh_jan_fish values (5);
insert into acnh_feb_fish values (5);
insert into acnh_mar_fish values (5);
insert into acnh_apr_fish values (5);
insert into acnh_may_fish values (5);
insert into acnh_jun_fish values (5);
insert into acnh_jul_fish values (5);
insert into acnh_aug1_fish values (5);
insert into acnh_sep1_fish values (5);
insert into acnh_oct_fish values (5);
insert into acnh_nov_fish values (5);
insert into acnh_dec_fish values (5);
insert into acnh_jan_fish values (6);
insert into acnh_feb_fish values (6);
insert into acnh_mar_fish values (6);
insert into acnh_apr_fish values (6);
insert into acnh_may_fish values (6);
insert into acnh_jun_fish values (6);
insert into acnh_jul_fish values (6);
insert into acnh_aug1_fish values (6);
insert into acnh_sep1_fish values (6);
insert into acnh_oct_fish values (6);
insert into acnh_nov_fish values (6);
insert into acnh_dec_fish values (6);
insert into acnh_jan_fish values (7);
insert into acnh_feb_fish values (7);
insert into acnh_mar_fish values (7);
insert into acnh_apr_fish values (7);
insert into acnh_may_fish values (7);
insert into acnh_jun_fish values (7);
insert into acnh_jul_fish values (7);
insert into acnh_aug1_fish values (7);
insert into acnh_sep1_fish values (7);
insert into acnh_oct_fish values (7);
insert into acnh_nov_fish values (7);
insert into acnh_dec_fish values (7);
insert into acnh_jan_fish values (8);
insert into acnh_feb_fish values (8);
insert into acnh_mar_fish values (8);
insert into acnh_apr_fish values (8);
insert into acnh_may_fish values (8);
insert into acnh_jun_fish values (8);
insert into acnh_jul_fish values (8);
insert into acnh_aug1_fish values (8);
insert into acnh_sep1_fish values (8);
insert into acnh_oct_fish values (8);
insert into acnh_nov_fish values (8);
insert into acnh_dec_fish values (8);
insert into acnh_jan_fish values (9);
insert into acnh_feb_fish values (9);
insert into acnh_mar_fish values (9);
insert into acnh_apr_fish values (9);
insert into acnh_may_fish values (9);
insert into acnh_jun_fish values (9);
insert into acnh_jul_fish values (9);
insert into acnh_aug1_fish values (9);
insert into acnh_sep1_fish values (9);
insert into acnh_oct_fish values (9);
insert into acnh_nov_fish values (9);
insert into acnh_dec_fish values (9);
insert into acnh_apr_fish values (10);
insert into acnh_may_fish values (10);
insert into acnh_jun_fish values (10);
insert into acnh_jul_fish values (10);
insert into acnh_aug1_fish values (10);
insert into acnh_apr_fish values (11);
insert into acnh_may_fish values (11);
insert into acnh_jun_fish values (11);
insert into acnh_jul_fish values (11);
insert into acnh_aug1_fish values (11);
insert into acnh_sep1_fish values (11);
insert into acnh_aug1_fish values (12);
insert into acnh_sep1_fish values (12);
insert into acnh_apr_fish values (13);
insert into acnh_may_fish values (13);
insert into acnh_jun_fish values (13);
insert into acnh_jul_fish values (13);
insert into acnh_aug1_fish values (13);
insert into acnh_sep1_fish values (13);
insert into acnh_oct_fish values (13);
insert into acnh_mar_fish values (14);
insert into acnh_apr_fish values (14);
insert into acnh_may_fish values (14);
insert into acnh_jun_fish values (14);
insert into acnh_jul_fish values (14);
insert into acnh_may_fish values (15);
insert into acnh_jun_fish values (15);
insert into acnh_jul_fish values (15);
insert into acnh_aug1_fish values (15);
insert into acnh_jan_fish values (16);
insert into acnh_feb_fish values (16);
insert into acnh_mar_fish values (16);
insert into acnh_apr_fish values (16);
insert into acnh_may_fish values (16);
insert into acnh_jun_fish values (16);
insert into acnh_jul_fish values (16);
insert into acnh_aug1_fish values (16);
insert into acnh_sep1_fish values (16);
insert into acnh_oct_fish values (16);
insert into acnh_nov_fish values (16);
insert into acnh_dec_fish values (16);
insert into acnh_mar_fish values (17);
insert into acnh_apr_fish values (17);
insert into acnh_may_fish values (17);
insert into acnh_may_fish values (18);
insert into acnh_jun_fish values (18);
insert into acnh_jul_fish values (18);
insert into acnh_aug1_fish values (18);
insert into acnh_sep1_fish values (18);
insert into acnh_oct_fish values (18);
insert into acnh_jun_fish values (19);
insert into acnh_jul_fish values (19);
insert into acnh_aug1_fish values (19);
insert into acnh_jan_fish values (20);
insert into acnh_feb_fish values (20);
insert into acnh_mar_fish values (20);
insert into acnh_apr_fish values (20);
insert into acnh_may_fish values (20);
insert into acnh_jun_fish values (20);
insert into acnh_jul_fish values (20);
insert into acnh_aug1_fish values (20);
insert into acnh_sep1_fish values (20);
insert into acnh_oct_fish values (20);
insert into acnh_nov_fish values (20);
insert into acnh_dec_fish values (20);
insert into acnh_jan_fish values (21);
insert into acnh_feb_fish values (21);
insert into acnh_mar_fish values (21);
insert into acnh_oct_fish values (21);
insert into acnh_nov_fish values (21);
insert into acnh_dec_fish values (21);
insert into acnh_jan_fish values (22);
insert into acnh_feb_fish values (22);
insert into acnh_mar_fish values (22);
insert into acnh_apr_fish values (22);
insert into acnh_may_fish values (22);
insert into acnh_jun_fish values (22);
insert into acnh_jul_fish values (22);
insert into acnh_aug1_fish values (22);
insert into acnh_sep1_fish values (22);
insert into acnh_oct_fish values (22);
insert into acnh_nov_fish values (22);
insert into acnh_dec_fish values (22);
insert into acnh_jun_fish values (23);
insert into acnh_jul_fish values (23);
insert into acnh_aug1_fish values (23);
insert into acnh_sep1_fish values (23);
insert into acnh_oct_fish values (23);
insert into acnh_sep1_fish values (24);
insert into acnh_oct_fish values (24);
insert into acnh_nov_fish values (24);
insert into acnh_dec_fish values (24);
insert into acnh_jan_fish values (25);
insert into acnh_feb_fish values (25);
insert into acnh_dec_fish values (25);
insert into acnh_jul_fish values (26);
insert into acnh_aug1_fish values (26);
insert into acnh_sep1_fish values (26);
insert into acnh_mar_fish values (27);
insert into acnh_apr_fish values (27);
insert into acnh_may_fish values (27);
insert into acnh_jun_fish values (27);
insert into acnh_sep1_fish values (27);
insert into acnh_oct_fish values (27);
insert into acnh_nov_fish values (27);
insert into acnh_mar_fish values (28);
insert into acnh_apr_fish values (28);
insert into acnh_may_fish values (28);
insert into acnh_jun_fish values (28);
insert into acnh_sep1_fish values (28);
insert into acnh_oct_fish values (28);
insert into acnh_nov_fish values (28);
insert into acnh_mar_fish values (29);
insert into acnh_apr_fish values (29);
insert into acnh_may_fish values (29);
insert into acnh_sep1_fish values (29);
insert into acnh_oct_fish values (29);
insert into acnh_nov_fish values (29);
insert into acnh_jan_fish values (30);
insert into acnh_feb_fish values (30);
insert into acnh_mar_fish values (30);
insert into acnh_dec_fish values (30);
insert into acnh_sep1_fish values (31);
insert into acnh_sep1_fish values (32);
insert into acnh_sep1_fish values (33);
insert into acnh_oct_fish values (33);
insert into acnh_nov_fish values (33);
insert into acnh_apr_fish values (34);
insert into acnh_may_fish values (34);
insert into acnh_jun_fish values (34);
insert into acnh_jul_fish values (34);
insert into acnh_aug1_fish values (34);
insert into acnh_sep1_fish values (34);
insert into acnh_oct_fish values (34);
insert into acnh_nov_fish values (34);
insert into acnh_may_fish values (35);
insert into acnh_jun_fish values (35);
insert into acnh_jul_fish values (35);
insert into acnh_aug1_fish values (35);
insert into acnh_sep1_fish values (35);
insert into acnh_may_fish values (36);
insert into acnh_jun_fish values (36);
insert into acnh_jul_fish values (36);
insert into acnh_aug1_fish values (36);
insert into acnh_sep1_fish values (36);
insert into acnh_oct_fish values (36);
insert into acnh_may_fish values (37);
insert into acnh_jun_fish values (37);
insert into acnh_jul_fish values (37);
insert into acnh_aug1_fish values (37);
insert into acnh_sep1_fish values (37);
insert into acnh_oct_fish values (37);
insert into acnh_apr_fish values (38);
insert into acnh_may_fish values (38);
insert into acnh_jun_fish values (38);
insert into acnh_jul_fish values (38);
insert into acnh_aug1_fish values (38);
insert into acnh_sep1_fish values (38);
insert into acnh_oct_fish values (38);
insert into acnh_nov_fish values (38);
insert into acnh_may_fish values (39);
insert into acnh_jun_fish values (39);
insert into acnh_jul_fish values (39);
insert into acnh_aug1_fish values (39);
insert into acnh_sep1_fish values (39);
insert into acnh_oct_fish values (39);
insert into acnh_jun_fish values (40);
insert into acnh_jul_fish values (40);
insert into acnh_aug1_fish values (40);
insert into acnh_sep1_fish values (40);
insert into acnh_jun_fish values (41);
insert into acnh_jul_fish values (41);
insert into acnh_aug1_fish values (41);
insert into acnh_sep1_fish values (41);
insert into acnh_jun_fish values (42);
insert into acnh_jul_fish values (42);
insert into acnh_aug1_fish values (42);
insert into acnh_sep1_fish values (42);
insert into acnh_jul_fish values (43);
insert into acnh_aug1_fish values (43);
insert into acnh_sep1_fish values (43);
insert into acnh_oct_fish values (43);
insert into acnh_jun_fish values (44);
insert into acnh_jul_fish values (44);
insert into acnh_aug1_fish values (44);
insert into acnh_sep1_fish values (44);
insert into acnh_jan_fish values (45);
insert into acnh_feb_fish values (45);
insert into acnh_mar_fish values (45);
insert into acnh_dec_fish values (45);
insert into acnh_jan_fish values (46);
insert into acnh_feb_fish values (46);
insert into acnh_mar_fish values (46);
insert into acnh_sep1_fish values (46);
insert into acnh_oct_fish values (46);
insert into acnh_nov_fish values (46);
insert into acnh_dec_fish values (46);
insert into acnh_jan_fish values (47);
insert into acnh_feb_fish values (47);
insert into acnh_mar_fish values (47);
insert into acnh_dec_fish values (47);
insert into acnh_apr_fish values (48);
insert into acnh_may_fish values (48);
insert into acnh_jun_fish values (48);
insert into acnh_jul_fish values (48);
insert into acnh_aug1_fish values (48);
insert into acnh_sep1_fish values (48);
insert into acnh_oct_fish values (48);
insert into acnh_nov_fish values (48);
insert into acnh_apr_fish values (49);
insert into acnh_may_fish values (49);
insert into acnh_jun_fish values (49);
insert into acnh_jul_fish values (49);
insert into acnh_aug1_fish values (49);
insert into acnh_sep1_fish values (49);
insert into acnh_apr_fish values (50);
insert into acnh_may_fish values (50);
insert into acnh_jun_fish values (50);
insert into acnh_jul_fish values (50);
insert into acnh_aug1_fish values (50);
insert into acnh_sep1_fish values (50);
insert into acnh_apr_fish values (51);
insert into acnh_may_fish values (51);
insert into acnh_jun_fish values (51);
insert into acnh_jul_fish values (51);
insert into acnh_aug1_fish values (51);
insert into acnh_sep1_fish values (51);
insert into acnh_jul_fish values (52);
insert into acnh_aug1_fish values (52);
insert into acnh_apr_fish values (53);
insert into acnh_may_fish values (53);
insert into acnh_jul_fish values (53);
insert into acnh_aug1_fish values (53);
insert into acnh_sep1_fish values (53);
insert into acnh_oct_fish values (53);
insert into acnh_nov_fish values (53);
insert into acnh_feb_fish values (54);
insert into acnh_mar_fish values (54);
insert into acnh_dec_fish values (54);
insert into acnh_jul_fish values (55);
insert into acnh_aug1_fish values (55);
insert into acnh_sep1_fish values (55);
insert into acnh_jan_fish values (56);
insert into acnh_feb_fish values (56);
insert into acnh_mar_fish values (56);
insert into acnh_apr_fish values (56);
insert into acnh_may_fish values (56);
insert into acnh_jun_fish values (56);
insert into acnh_jul_fish values (56);
insert into acnh_aug1_fish values (56);
insert into acnh_sep1_fish values (56);
insert into acnh_oct_fish values (56);
insert into acnh_nov_fish values (56);
insert into acnh_dec_fish values (56);
insert into acnh_jan_fish values (57);
insert into acnh_feb_fish values (57);
insert into acnh_mar_fish values (57);
insert into acnh_apr_fish values (57);
insert into acnh_may_fish values (57);
insert into acnh_jun_fish values (57);
insert into acnh_jul_fish values (57);
insert into acnh_aug1_fish values (57);
insert into acnh_sep1_fish values (57);
insert into acnh_oct_fish values (57);
insert into acnh_nov_fish values (57);
insert into acnh_dec_fish values (57);
insert into acnh_mar_fish values (58);
insert into acnh_apr_fish values (58);
insert into acnh_may_fish values (58);
insert into acnh_jun_fish values (58);
insert into acnh_jul_fish values (58);
insert into acnh_aug1_fish values (58);
insert into acnh_sep1_fish values (58);
insert into acnh_oct_fish values (58);
insert into acnh_nov_fish values (58);
insert into acnh_jan_fish values (59);
insert into acnh_feb_fish values (59);
insert into acnh_mar_fish values (59);
insert into acnh_apr_fish values (59);
insert into acnh_may_fish values (59);
insert into acnh_jun_fish values (59);
insert into acnh_jul_fish values (59);
insert into acnh_aug1_fish values (59);
insert into acnh_sep1_fish values (59);
insert into acnh_oct_fish values (59);
insert into acnh_nov_fish values (59);
insert into acnh_dec_fish values (59);
insert into acnh_jan_fish values (60);
insert into acnh_feb_fish values (60);
insert into acnh_mar_fish values (60);
insert into acnh_apr_fish values (60);
insert into acnh_may_fish values (60);
insert into acnh_jun_fish values (60);
insert into acnh_jul_fish values (60);
insert into acnh_aug1_fish values (60);
insert into acnh_sep1_fish values (60);
insert into acnh_oct_fish values (60);
insert into acnh_nov_fish values (60);
insert into acnh_dec_fish values (60);
insert into acnh_jan_fish values (61);
insert into acnh_feb_fish values (61);
insert into acnh_mar_fish values (61);
insert into acnh_apr_fish values (61);
insert into acnh_oct_fish values (61);
insert into acnh_nov_fish values (61);
insert into acnh_dec_fish values (61);
insert into acnh_jan_fish values (62);
insert into acnh_feb_fish values (62);
insert into acnh_mar_fish values (62);
insert into acnh_apr_fish values (62);
insert into acnh_may_fish values (62);
insert into acnh_jun_fish values (62);
insert into acnh_jul_fish values (62);
insert into acnh_aug1_fish values (62);
insert into acnh_sep1_fish values (62);
insert into acnh_oct_fish values (62);
insert into acnh_nov_fish values (62);
insert into acnh_dec_fish values (62);
insert into acnh_jan_fish values (63);
insert into acnh_feb_fish values (63);
insert into acnh_mar_fish values (63);
insert into acnh_apr_fish values (63);
insert into acnh_may_fish values (63);
insert into acnh_jun_fish values (63);
insert into acnh_jul_fish values (63);
insert into acnh_aug1_fish values (63);
insert into acnh_dec_fish values (63);
insert into acnh_aug1_fish values (64);
insert into acnh_sep1_fish values (64);
insert into acnh_oct_fish values (64);
insert into acnh_jun_fish values (65);
insert into acnh_jul_fish values (65);
insert into acnh_aug1_fish values (65);
insert into acnh_sep1_fish values (65);
insert into acnh_oct_fish values (65);
insert into acnh_jan_fish values (66);
insert into acnh_feb_fish values (66);
insert into acnh_mar_fish values (66);
insert into acnh_apr_fish values (66);
insert into acnh_nov_fish values (66);
insert into acnh_dec_fish values (66);
insert into acnh_jan_fish values (67);
insert into acnh_feb_fish values (67);
insert into acnh_mar_fish values (67);
insert into acnh_apr_fish values (67);
insert into acnh_jul_fish values (67);
insert into acnh_aug1_fish values (67);
insert into acnh_sep1_fish values (67);
insert into acnh_nov_fish values (67);
insert into acnh_dec_fish values (67);
insert into acnh_may_fish values (68);
insert into acnh_jun_fish values (68);
insert into acnh_jul_fish values (68);
insert into acnh_aug1_fish values (68);
insert into acnh_sep1_fish values (68);
insert into acnh_oct_fish values (68);
insert into acnh_may_fish values (69);
insert into acnh_jun_fish values (69);
insert into acnh_jul_fish values (69);
insert into acnh_aug1_fish values (69);
insert into acnh_sep1_fish values (69);
insert into acnh_oct_fish values (69);
insert into acnh_jul_fish values (70);
insert into acnh_aug1_fish values (70);
insert into acnh_sep1_fish values (70);
insert into acnh_aug1_fish values (71);
insert into acnh_sep1_fish values (71);
insert into acnh_oct_fish values (71);
insert into acnh_nov_fish values (71);
insert into acnh_jun_fish values (72);
insert into acnh_jul_fish values (72);
insert into acnh_aug1_fish values (72);
insert into acnh_sep1_fish values (72);
insert into acnh_jun_fish values (73);
insert into acnh_jul_fish values (73);
insert into acnh_aug1_fish values (73);
insert into acnh_sep1_fish values (73);
insert into acnh_jun_fish values (74);
insert into acnh_jul_fish values (74);
insert into acnh_aug1_fish values (74);
insert into acnh_sep1_fish values (74);
insert into acnh_jun_fish values (75);
insert into acnh_jul_fish values (75);
insert into acnh_aug1_fish values (75);
insert into acnh_sep1_fish values (75);
insert into acnh_jun_fish values (76);
insert into acnh_jul_fish values (76);
insert into acnh_aug1_fish values (76);
insert into acnh_sep1_fish values (76);
insert into acnh_jan_fish values (77);
insert into acnh_feb_fish values (77);
insert into acnh_mar_fish values (77);
insert into acnh_nov_fish values (77);
insert into acnh_dec_fish values (77);
insert into acnh_jan_fish values (78);
insert into acnh_feb_fish values (78);
insert into acnh_mar_fish values (78);
insert into acnh_apr_fish values (78);
insert into acnh_may_fish values (78);
insert into acnh_dec_fish values (78);
insert into acnh_jan_fish values (79);
insert into acnh_feb_fish values (79);
insert into acnh_mar_fish values (79);
insert into acnh_apr_fish values (79);
insert into acnh_may_fish values (79);
insert into acnh_jun_fish values (79);
insert into acnh_jul_fish values (79);
insert into acnh_aug1_fish values (79);
insert into acnh_sep1_fish values (79);
insert into acnh_oct_fish values (79);
insert into acnh_nov_fish values (79);
insert into acnh_dec_fish values (79);
insert into acnh_jan_fish values (80);
insert into acnh_feb_fish values (80);
insert into acnh_mar_fish values (80);
insert into acnh_apr_fish values (80);
insert into acnh_may_fish values (80);
insert into acnh_jun_fish values (80);
insert into acnh_jul_fish values (80);
insert into acnh_aug1_fish values (80);
insert into acnh_sep1_fish values (80);
insert into acnh_oct_fish values (80);
insert into acnh_nov_fish values (80);
insert into acnh_dec_fish values (80);
drop table if exists acnh_jan_insect;
drop table if exists acnh_feb_insect;
drop table if exists acnh_mar_insect;
drop table if exists acnh_apr_insect;
drop table if exists acnh_may_insect;
drop table if exists acnh_jun_insect;
drop table if exists acnh_jul_insect;
drop table if exists acnh_aug1_insect;
drop table if exists acnh_aug2_insect;
drop table if exists acnh_sep1_insect;
drop table if exists acnh_sep2_insect;
drop table if exists acnh_oct_insect;
drop table if exists acnh_nov_insect;
drop table if exists acnh_dec_insect;
create table acnh_jan_insect (id int);
create table acnh_feb_insect (id int);
create table acnh_mar_insect (id int);
create table acnh_apr_insect (id int);
create table acnh_may_insect (id int);
create table acnh_jun_insect (id int);
create table acnh_jul_insect (id int);
create table acnh_aug1_insect (id int);
create table acnh_aug2_insect (id int);
create table acnh_sep1_insect (id int);
create table acnh_sep2_insect (id int);
create table acnh_oct_insect (id int);
create table acnh_nov_insect (id int);
create table acnh_dec_insect (id int);
insert into acnh_jan_insect values (1);
insert into acnh_feb_insect values (1);
insert into acnh_mar_insect values (1);
insert into acnh_apr_insect values (1);
insert into acnh_may_insect values (1);
insert into acnh_jun_insect values (1);
insert into acnh_sep1_insect values (1);
insert into acnh_oct_insect values (1);
insert into acnh_nov_insect values (1);
insert into acnh_dec_insect values (1);
insert into acnh_mar_insect values (2);
insert into acnh_apr_insect values (2);
insert into acnh_may_insect values (2);
insert into acnh_jun_insect values (2);
insert into acnh_sep1_insect values (2);
insert into acnh_oct_insect values (2);
insert into acnh_mar_insect values (3);
insert into acnh_apr_insect values (3);
insert into acnh_may_insect values (3);
insert into acnh_jun_insect values (3);
insert into acnh_jul_insect values (3);
insert into acnh_aug1_insect values (3);
insert into acnh_sep1_insect values (3);
insert into acnh_mar_insect values (4);
insert into acnh_apr_insect values (4);
insert into acnh_may_insect values (4);
insert into acnh_jun_insect values (4);
insert into acnh_apr_insect values (5);
insert into acnh_may_insect values (5);
insert into acnh_jun_insect values (5);
insert into acnh_jul_insect values (5);
insert into acnh_aug1_insect values (5);
insert into acnh_jan_insect values (6);
insert into acnh_feb_insect values (6);
insert into acnh_mar_insect values (6);
insert into acnh_apr_insect values (6);
insert into acnh_may_insect values (6);
insert into acnh_jun_insect values (6);
insert into acnh_jul_insect values (6);
insert into acnh_aug1_insect values (6);
insert into acnh_sep1_insect values (6);
insert into acnh_oct_insect values (6);
insert into acnh_nov_insect values (6);
insert into acnh_dec_insect values (6);
insert into acnh_may_insect values (7);
insert into acnh_jun_insect values (7);
insert into acnh_jul_insect values (7);
insert into acnh_aug1_insect values (7);
insert into acnh_sep1_insect values (8);
insert into acnh_oct_insect values (8);
insert into acnh_nov_insect values (8);
insert into acnh_jan_insect values (9);
insert into acnh_feb_insect values (9);
insert into acnh_mar_insect values (9);
insert into acnh_jun_insect values (9);
insert into acnh_jul_insect values (9);
insert into acnh_aug1_insect values (9);
insert into acnh_sep1_insect values (9);
insert into acnh_dec_insect values (9);
insert into acnh_apr_insect values (10);
insert into acnh_may_insect values (10);
insert into acnh_jun_insect values (10);
insert into acnh_jul_insect values (10);
insert into acnh_aug1_insect values (10);
insert into acnh_sep1_insect values (10);
insert into acnh_jan_insect values (11);
insert into acnh_feb_insect values (11);
insert into acnh_apr_insect values (11);
insert into acnh_may_insect values (11);
insert into acnh_jun_insect values (11);
insert into acnh_jul_insect values (11);
insert into acnh_aug1_insect values (11);
insert into acnh_sep1_insect values (11);
insert into acnh_dec_insect values (11);
insert into acnh_may_insect values (12);
insert into acnh_jun_insect values (12);
insert into acnh_jul_insect values (12);
insert into acnh_aug1_insect values (12);
insert into acnh_sep1_insect values (12);
insert into acnh_jan_insect values (13);
insert into acnh_feb_insect values (13);
insert into acnh_mar_insect values (13);
insert into acnh_apr_insect values (13);
insert into acnh_may_insect values (13);
insert into acnh_jun_insect values (13);
insert into acnh_jul_insect values (13);
insert into acnh_aug1_insect values (13);
insert into acnh_sep1_insect values (13);
insert into acnh_oct_insect values (13);
insert into acnh_nov_insect values (13);
insert into acnh_dec_insect values (13);
insert into acnh_apr_insect values (14);
insert into acnh_may_insect values (14);
insert into acnh_jun_insect values (14);
insert into acnh_jul_insect values (14);
insert into acnh_aug1_insect values (14);
insert into acnh_sep1_insect values (14);
insert into acnh_apr_insect values (15);
insert into acnh_may_insect values (15);
insert into acnh_jun_insect values (15);
insert into acnh_jul_insect values (15);
insert into acnh_aug1_insect values (15);
insert into acnh_sep1_insect values (15);
insert into acnh_apr_insect values (16);
insert into acnh_may_insect values (16);
insert into acnh_jun_insect values (16);
insert into acnh_jul_insect values (16);
insert into acnh_aug1_insect values (16);
insert into acnh_sep1_insect values (16);
insert into acnh_oct_insect values (16);
insert into acnh_nov_insect values (16);
insert into acnh_aug1_insect values (17);
insert into acnh_sep1_insect values (17);
insert into acnh_oct_insect values (17);
insert into acnh_nov_insect values (17);
insert into acnh_aug1_insect values (18);
insert into acnh_sep1_insect values (18);
insert into acnh_oct_insect values (18);
insert into acnh_nov_insect values (18);
insert into acnh_jul_insect values (19);
insert into acnh_aug1_insect values (19);
insert into acnh_sep1_insect values (19);
insert into acnh_sep1_insect values (20);
insert into acnh_oct_insect values (20);
insert into acnh_nov_insect values (20);
insert into acnh_sep1_insect values (21);
insert into acnh_oct_insect values (21);
insert into acnh_mar_insect values (22);
insert into acnh_apr_insect values (22);
insert into acnh_may_insect values (22);
insert into acnh_jun_insect values (22);
insert into acnh_jul_insect values (22);
insert into acnh_aug1_insect values (22);
insert into acnh_sep1_insect values (22);
insert into acnh_oct_insect values (22);
insert into acnh_nov_insect values (22);
insert into acnh_mar_insect values (23);
insert into acnh_apr_insect values (23);
insert into acnh_may_insect values (23);
insert into acnh_jun_insect values (23);
insert into acnh_jul_insect values (23);
insert into acnh_aug1_insect values (23);
insert into acnh_sep1_insect values (23);
insert into acnh_oct_insect values (23);
insert into acnh_nov_insect values (23);
insert into acnh_mar_insect values (24);
insert into acnh_apr_insect values (24);
insert into acnh_may_insect values (24);
insert into acnh_jun_insect values (24);
insert into acnh_jul_insect values (24);
insert into acnh_jan_insect values (25);
insert into acnh_feb_insect values (25);
insert into acnh_mar_insect values (25);
insert into acnh_apr_insect values (25);
insert into acnh_may_insect values (25);
insert into acnh_jun_insect values (25);
insert into acnh_jul_insect values (25);
insert into acnh_aug1_insect values (25);
insert into acnh_sep1_insect values (25);
insert into acnh_oct_insect values (25);
insert into acnh_nov_insect values (25);
insert into acnh_dec_insect values (25);
insert into acnh_jul_insect values (26);
insert into acnh_aug1_insect values (26);
insert into acnh_jul_insect values (27);
insert into acnh_aug1_insect values (27);
insert into acnh_jul_insect values (28);
insert into acnh_aug1_insect values (28);
insert into acnh_aug1_insect values (29);
insert into acnh_sep1_insect values (29);
insert into acnh_jul_insect values (30);
insert into acnh_aug1_insect values (30);
insert into acnh_jul_insect values (31);
insert into acnh_aug1_insect values (31);
insert into acnh_sep1_insect values (32);
insert into acnh_oct_insect values (32);
insert into acnh_apr_insect values (33);
insert into acnh_may_insect values (33);
insert into acnh_jun_insect values (33);
insert into acnh_jul_insect values (33);
insert into acnh_aug1_insect values (33);
insert into acnh_sep1_insect values (33);
insert into acnh_oct_insect values (33);
insert into acnh_may_insect values (34);
insert into acnh_jun_insect values (34);
insert into acnh_jul_insect values (34);
insert into acnh_aug1_insect values (34);
insert into acnh_sep1_insect values (34);
insert into acnh_oct_insect values (34);
insert into acnh_jan_insect values (35);
insert into acnh_feb_insect values (35);
insert into acnh_nov_insect values (35);
insert into acnh_dec_insect values (35);
insert into acnh_jun_insect values (36);
insert into acnh_jan_insect values (37);
insert into acnh_feb_insect values (37);
insert into acnh_mar_insect values (37);
insert into acnh_apr_insect values (37);
insert into acnh_may_insect values (37);
insert into acnh_nov_insect values (37);
insert into acnh_dec_insect values (37);
insert into acnh_may_insect values (38);
insert into acnh_jun_insect values (38);
insert into acnh_jul_insect values (38);
insert into acnh_aug1_insect values (38);
insert into acnh_sep1_insect values (38);
insert into acnh_may_insect values (39);
insert into acnh_jun_insect values (39);
insert into acnh_jul_insect values (39);
insert into acnh_aug1_insect values (39);
insert into acnh_sep1_insect values (39);
insert into acnh_apr_insect values (40);
insert into acnh_may_insect values (40);
insert into acnh_jun_insect values (40);
insert into acnh_jul_insect values (40);
insert into acnh_aug1_insect values (40);
insert into acnh_sep1_insect values (40);
insert into acnh_mar_insect values (41);
insert into acnh_apr_insect values (41);
insert into acnh_may_insect values (41);
insert into acnh_jun_insect values (41);
insert into acnh_jul_insect values (41);
insert into acnh_aug1_insect values (41);
insert into acnh_sep1_insect values (41);
insert into acnh_oct_insect values (41);
insert into acnh_mar_insect values (42);
insert into acnh_apr_insect values (42);
insert into acnh_may_insect values (42);
insert into acnh_jun_insect values (42);
insert into acnh_jul_insect values (42);
insert into acnh_aug1_insect values (42);
insert into acnh_sep1_insect values (42);
insert into acnh_oct_insect values (42);
insert into acnh_mar_insect values (43);
insert into acnh_apr_insect values (43);
insert into acnh_may_insect values (43);
insert into acnh_jun_insect values (43);
insert into acnh_oct_insect values (43);
insert into acnh_feb_insect values (44);
insert into acnh_mar_insect values (44);
insert into acnh_apr_insect values (44);
insert into acnh_may_insect values (44);
insert into acnh_jun_insect values (44);
insert into acnh_jul_insect values (44);
insert into acnh_aug1_insect values (44);
insert into acnh_sep1_insect values (44);
insert into acnh_oct_insect values (44);
insert into acnh_apr_insect values (45);
insert into acnh_may_insect values (45);
insert into acnh_jun_insect values (45);
insert into acnh_jul_insect values (45);
insert into acnh_aug1_insect values (45);
insert into acnh_may_insect values (46);
insert into acnh_jun_insect values (46);
insert into acnh_sep1_insect values (46);
insert into acnh_oct_insect values (46);
insert into acnh_nov_insect values (46);
insert into acnh_jan_insect values (47);
insert into acnh_feb_insect values (47);
insert into acnh_mar_insect values (47);
insert into acnh_apr_insect values (47);
insert into acnh_may_insect values (47);
insert into acnh_jun_insect values (47);
insert into acnh_jul_insect values (47);
insert into acnh_aug1_insect values (47);
insert into acnh_sep1_insect values (47);
insert into acnh_oct_insect values (47);
insert into acnh_nov_insect values (47);
insert into acnh_dec_insect values (47);
insert into acnh_may_insect values (48);
insert into acnh_jun_insect values (48);
insert into acnh_jul_insect values (48);
insert into acnh_aug1_insect values (48);
insert into acnh_sep1_insect values (48);
insert into acnh_jul_insect values (49);
insert into acnh_aug1_insect values (49);
insert into acnh_jul_insect values (51);
insert into acnh_aug1_insect values (51);
insert into acnh_sep1_insect values (51);
insert into acnh_jul_insect values (52);
insert into acnh_aug1_insect values (52);
insert into acnh_jun_insect values (53);
insert into acnh_jul_insect values (53);
insert into acnh_aug1_insect values (53);
insert into acnh_jun_insect values (54);
insert into acnh_jul_insect values (54);
insert into acnh_aug1_insect values (54);
insert into acnh_sep1_insect values (54);
insert into acnh_jul_insect values (55);
insert into acnh_aug1_insect values (55);
insert into acnh_jul_insect values (56);
insert into acnh_aug1_insect values (56);
insert into acnh_jul_insect values (57);
insert into acnh_aug1_insect values (57);
insert into acnh_jun_insect values (58);
insert into acnh_jul_insect values (58);
insert into acnh_aug1_insect values (58);
insert into acnh_sep1_insect values (58);
insert into acnh_jul_insect values (59);
insert into acnh_aug1_insect values (59);
insert into acnh_jul_insect values (60);
insert into acnh_aug1_insect values (60);
insert into acnh_jul_insect values (61);
insert into acnh_aug1_insect values (61);
insert into acnh_jul_insect values (62);
insert into acnh_aug1_insect values (62);
insert into acnh_jul_insect values (63);
insert into acnh_aug1_insect values (63);
insert into acnh_jul_insect values (64);
insert into acnh_aug1_insect values (64);
insert into acnh_jul_insect values (65);
insert into acnh_aug1_insect values (65);
insert into acnh_jul_insect values (66);
insert into acnh_aug1_insect values (66);
insert into acnh_sep1_insect values (66);
insert into acnh_oct_insect values (66);
insert into acnh_nov_insect values (66);
insert into acnh_jul_insect values (67);
insert into acnh_aug1_insect values (67);
insert into acnh_sep1_insect values (67);
insert into acnh_jan_insect values (68);
insert into acnh_feb_insect values (68);
insert into acnh_mar_insect values (68);
insert into acnh_apr_insect values (68);
insert into acnh_may_insect values (68);
insert into acnh_jun_insect values (68);
insert into acnh_jul_insect values (68);
insert into acnh_aug1_insect values (68);
insert into acnh_sep1_insect values (68);
insert into acnh_oct_insect values (68);
insert into acnh_nov_insect values (68);
insert into acnh_dec_insect values (68);
insert into acnh_jan_insect values (69);
insert into acnh_feb_insect values (69);
insert into acnh_mar_insect values (69);
insert into acnh_apr_insect values (69);
insert into acnh_may_insect values (69);
insert into acnh_jun_insect values (69);
insert into acnh_jul_insect values (69);
insert into acnh_aug1_insect values (69);
insert into acnh_sep1_insect values (69);
insert into acnh_oct_insect values (69);
insert into acnh_nov_insect values (69);
insert into acnh_dec_insect values (69);
insert into acnh_jan_insect values (70);
insert into acnh_feb_insect values (70);
insert into acnh_mar_insect values (70);
insert into acnh_apr_insect values (70);
insert into acnh_may_insect values (70);
insert into acnh_jun_insect values (70);
insert into acnh_jul_insect values (70);
insert into acnh_aug1_insect values (70);
insert into acnh_sep1_insect values (70);
insert into acnh_oct_insect values (70);
insert into acnh_nov_insect values (70);
insert into acnh_dec_insect values (70);
insert into acnh_jan_insect values (71);
insert into acnh_feb_insect values (71);
insert into acnh_mar_insect values (71);
insert into acnh_apr_insect values (71);
insert into acnh_may_insect values (71);
insert into acnh_jun_insect values (71);
insert into acnh_jul_insect values (71);
insert into acnh_aug1_insect values (71);
insert into acnh_sep1_insect values (71);
insert into acnh_oct_insect values (71);
insert into acnh_nov_insect values (71);
insert into acnh_dec_insect values (71);
insert into acnh_jan_insect values (72);
insert into acnh_feb_insect values (72);
insert into acnh_mar_insect values (72);
insert into acnh_apr_insect values (72);
insert into acnh_may_insect values (72);
insert into acnh_jun_insect values (72);
insert into acnh_jul_insect values (72);
insert into acnh_aug1_insect values (72);
insert into acnh_sep1_insect values (72);
insert into acnh_oct_insect values (72);
insert into acnh_nov_insect values (72);
insert into acnh_dec_insect values (72);
insert into acnh_jun_insect values (73);
insert into acnh_jul_insect values (73);
insert into acnh_aug1_insect values (73);
insert into acnh_sep1_insect values (73);
insert into acnh_apr_insect values (74);
insert into acnh_may_insect values (74);
insert into acnh_jun_insect values (74);
insert into acnh_jul_insect values (74);
insert into acnh_aug1_insect values (74);
insert into acnh_sep1_insect values (74);
insert into acnh_oct_insect values (74);
insert into acnh_nov_insect values (74);
insert into acnh_jan_insect values (75);
insert into acnh_feb_insect values (75);
insert into acnh_mar_insect values (75);
insert into acnh_apr_insect values (75);
insert into acnh_may_insect values (75);
insert into acnh_jun_insect values (75);
insert into acnh_jul_insect values (75);
insert into acnh_aug1_insect values (75);
insert into acnh_sep1_insect values (75);
insert into acnh_oct_insect values (75);
insert into acnh_nov_insect values (75);
insert into acnh_dec_insect values (75);
insert into acnh_jan_insect values (76);
insert into acnh_feb_insect values (76);
insert into acnh_mar_insect values (76);
insert into acnh_apr_insect values (76);
insert into acnh_may_insect values (76);
insert into acnh_jun_insect values (76);
insert into acnh_sep1_insect values (76);
insert into acnh_oct_insect values (76);
insert into acnh_nov_insect values (76);
insert into acnh_dec_insect values (76);
insert into acnh_jan_insect values (77);
insert into acnh_feb_insect values (77);
insert into acnh_mar_insect values (77);
insert into acnh_apr_insect values (77);
insert into acnh_may_insect values (77);
insert into acnh_jun_insect values (77);
insert into acnh_sep1_insect values (77);
insert into acnh_oct_insect values (77);
insert into acnh_nov_insect values (77);
insert into acnh_dec_insect values (77);
insert into acnh_jan_insect values (78);
insert into acnh_feb_insect values (78);
insert into acnh_mar_insect values (78);
insert into acnh_apr_insect values (78);
insert into acnh_may_insect values (78);
insert into acnh_jun_insect values (78);
insert into acnh_jul_insect values (78);
insert into acnh_aug1_insect values (78);
insert into acnh_sep1_insect values (78);
insert into acnh_oct_insect values (78);
insert into acnh_nov_insect values (78);
insert into acnh_dec_insect values (78);
insert into acnh_jan_insect values (79);
insert into acnh_feb_insect values (79);
insert into acnh_mar_insect values (79);
insert into acnh_apr_insect values (79);
insert into acnh_nov_insect values (79);
insert into acnh_dec_insect values (79);
insert into acnh_may_insect values (80);
insert into acnh_jun_insect values (80);
insert into acnh_jul_insect values (80);
insert into acnh_aug1_insect values (80);
insert into acnh_sep1_insect values (80);
insert into acnh_oct_insect values (80);