insert into acnh_accessory values(232, 0, 'animal nose', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(233, 0, 'Santa beard', 'orderable', '1480', 'Able Sisters', 'Simple');
insert into acnh_bag values(97, 0, 'grape-harvest basket', 'unorderable', '200', 'Nook Shopping Seasonal', 'Simple');
insert into acnh_bag values(98, 0, 'impish wings (White)', 'orderable', '1000', 'Kicks', 'Cool');
insert into acnh_bag values(99, 0, 'impish wings (Black)', 'orderable', '1000', 'Kicks', 'Cool');
insert into acnh_bag values(100, 0, 'impish wings (Red)', 'orderable', '1000', 'Kicks', 'Cool');
insert into acnh_bag values(101, 0, 'impish wings (Orange)', 'orderable', '1000', 'Kicks', 'Cool');
insert into acnh_bag values(102, 0, 'impish wings (Green)', 'orderable', '1000', 'Kicks', 'Cool');
insert into acnh_bag values(103, 0, 'impish wings (Purple)', 'orderable', '1000', 'Kicks', 'Cool');
insert into acnh_bottom values(728, 0, 'Santa pants', 'orderable', '2150', 'Able Sisters', 'Simple');
insert into acnh_dress values(925, 0, 'flashy animal costume (White)', 'orderable', '1700', 'Able Sisters', 'Active');
insert into acnh_dress values(926, 0, 'flashy animal costume (Black)', 'orderable', '1700', 'Able Sisters', 'Active');
insert into acnh_dress values(927, 0, 'flashy animal costume (Red)', 'orderable', '1700', 'Able Sisters', 'Active');
insert into acnh_dress values(928, 0, 'flashy animal costume (Orange)', 'orderable', '1700', 'Able Sisters', 'Active');
insert into acnh_dress values(929, 0, 'flashy animal costume (Green)', 'orderable', '1700', 'Able Sisters', 'Active');
insert into acnh_dress values(930, 0, 'flashy animal costume (Purple)', 'orderable', '1700', 'Able Sisters', 'Active');
insert into acnh_dress values(931, 0, 'Hikoboshi outfit', 'unorderable', '625', 'Nook Shopping Seasonal', 'Elegant');
insert into acnh_dress values(932, 0, 'Jack''s robe', 'unorderable', '2000', 'Jack', 'Cool');
insert into acnh_dress values(933, 0, 'mage''s dress (White)', 'orderable', '2040', 'Able Sisters', 'Cute');
insert into acnh_dress values(934, 0, 'mage''s dress (Black)', 'orderable', '2040', 'Able Sisters', 'Cute');
insert into acnh_dress values(935, 0, 'mage''s dress (Red)', 'orderable', '2040', 'Able Sisters', 'Cute');
insert into acnh_dress values(936, 0, 'mage''s dress (Orange)', 'orderable', '2040', 'Able Sisters', 'Cute');
insert into acnh_dress values(937, 0, 'mage''s dress (Green)', 'orderable', '2040', 'Able Sisters', 'Cute');
insert into acnh_dress values(938, 0, 'mage''s dress (Purple)', 'orderable', '2040', 'Able Sisters', 'Cute');
insert into acnh_dress values(939, 0, 'magic-academy robe (White)', 'orderable', '2040', 'Able Sisters', 'Cool');
insert into acnh_dress values(940, 0, 'magic-academy robe (Black)', 'orderable', '2040', 'Able Sisters', 'Cool');
insert into acnh_dress values(941, 0, 'magic-academy robe (Red)', 'orderable', '2040', 'Able Sisters', 'Cool');
insert into acnh_dress values(942, 0, 'magic-academy robe (Orange)', 'orderable', '2040', 'Able Sisters', 'Cool');
insert into acnh_dress values(943, 0, 'magic-academy robe (Green)', 'orderable', '2040', 'Able Sisters', 'Cool');
insert into acnh_dress values(944, 0, 'magic-academy robe (Purple)', 'orderable', '2040', 'Able Sisters', 'Cool');
insert into acnh_dress values(945, 0, 'Orihime outfit', 'unorderable', '625', 'Nook Shopping Seasonal', 'Elegant');
insert into acnh_dress values(946, 0, 'raggedy outfit (White)', 'orderable', '1500', 'Able Sisters', 'Cool');
insert into acnh_dress values(947, 0, 'raggedy outfit (Black)', 'orderable', '1500', 'Able Sisters', 'Cool');
insert into acnh_dress values(948, 0, 'raggedy outfit (Red)', 'orderable', '1500', 'Able Sisters', 'Cool');
insert into acnh_dress values(949, 0, 'raggedy outfit (Orange)', 'orderable', '1500', 'Able Sisters', 'Cool');
insert into acnh_dress values(950, 0, 'raggedy outfit (Green)', 'orderable', '1500', 'Able Sisters', 'Cool');
insert into acnh_dress values(951, 0, 'raggedy outfit (Purple)', 'orderable', '1500', 'Able Sisters', 'Cool');
insert into acnh_dress values(952, 0, 'reindeer costume', 'orderable', '1700', 'Able Sisters', 'Cute');
insert into acnh_fencing values(20, 0, 'spooky fence', '585', 'Crafting');
insert into acnh_flooring values(179, 0, 'spooky flooring', 'unorderable', '3000', 'Villagers', 'horror', 'none', 'spooky');
insert into acnh_flooring values(180, 0, 'Turkey Day flooring', 'unorderable', '750', 'Franklin', 'party', 'none', 'none');
insert into acnh_headwear values(705, 0, 'bulb bopper', 'unorderable', '245', 'Isabelle', 'Cute');
insert into acnh_headwear values(706, 0, 'flashy pointy-ear animal hat (White)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(707, 0, 'flashy pointy-ear animal hat (Black)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(708, 0, 'flashy pointy-ear animal hat (Red)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(709, 0, 'flashy pointy-ear animal hat (Orange)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(710, 0, 'flashy pointy-ear animal hat (Green)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(711, 0, 'flashy pointy-ear animal hat (Purple)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(712, 0, 'flashy round-ear animal hat (White)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(713, 0, 'flashy round-ear animal hat (Black)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(714, 0, 'flashy round-ear animal hat (Red)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(715, 0, 'flashy round-ear animal hat (Orange)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(716, 0, 'flashy round-ear animal hat (Green)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(717, 0, 'flashy round-ear animal hat (Purple)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(718, 0, 'flower bopper', 'unorderable', '245', 'Isabelle', 'Cute');
insert into acnh_headwear values(719, 0, 'heart bopper', 'unorderable', '245', 'Isabelle', 'Cute');
insert into acnh_headwear values(720, 0, 'impish horns (White)', 'orderable', '800', 'Able Sisters', 'Cool');
insert into acnh_headwear values(721, 0, 'impish horns (Black)', 'orderable', '800', 'Able Sisters', 'Cool');
insert into acnh_headwear values(722, 0, 'impish horns (Red)', 'orderable', '800', 'Able Sisters', 'Cool');
insert into acnh_headwear values(723, 0, 'impish horns (Orange)', 'orderable', '800', 'Able Sisters', 'Cool');
insert into acnh_headwear values(724, 0, 'impish horns (Green)', 'orderable', '800', 'Able Sisters', 'Cool');
insert into acnh_headwear values(725, 0, 'impish horns (Purple)', 'orderable', '800', 'Able Sisters', 'Cool');
insert into acnh_headwear values(726, 0, 'Jack''s face', 'unorderable', '1000', 'Jack', 'Cool');
insert into acnh_headwear values(727, 0, 'King Tut mask', 'unorderable', '50000', 'Crafting', 'Gorgeous');
insert into acnh_headwear values(728, 0, 'mage''s striped hat (White)', 'orderable', '3440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(729, 0, 'mage''s striped hat (Black)', 'orderable', '3440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(730, 0, 'mage''s striped hat (Red)', 'orderable', '3440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(731, 0, 'mage''s striped hat (Orange)', 'orderable', '3440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(732, 0, 'mage''s striped hat (Green)', 'orderable', '3440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(733, 0, 'mage''s striped hat (Purple)', 'orderable', '3440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(734, 0, 'magic-academy hood (White)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(735, 0, 'magic-academy hood (Black)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(736, 0, 'magic-academy hood (Red)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(737, 0, 'magic-academy hood (Orange)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(738, 0, 'magic-academy hood (Green)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(739, 0, 'magic-academy hood (Purple)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(740, 0, 'reindeer hat', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(741, 0, 'Santa hat', 'orderable', '2000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(742, 0, 'star bopper', 'unorderable', '245', 'Isabelle', 'Cute');
insert into acnh_houseware values(1452, 0, '2021 celebratory arch', 'unorderable', '505', 'Nook Shopping Seasonal', 'party', 'None', 'None');
insert into acnh_houseware values(1453, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1454, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1455, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1456, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1457, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1458, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1459, 0, 'gift pile', 'unorderable', '660', 'Crafting', 'living room', 'party', 'festive');
insert into acnh_houseware values(1460, 0, 'kadomatsu', 'unorderable', '645', 'Nook Shopping Seasonal', 'zen-style', 'None', 'None');
insert into acnh_houseware values(1461, 0, 'kids'' tent (White)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1462, 0, 'kids'' tent (Pink)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1463, 0, 'kids'' tent (Black)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1464, 0, 'kids'' tent (Stripes)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1465, 0, 'kids'' tent (Floral)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1466, 0, 'kids'' tent (Blue)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1467, 0, 'kids'' tent (Brown)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1468, 0, 'kids'' tent (Colorful)', 'orderable', '4500', 'Nook''s Cranny', 'child''s room', 'outdoors', 'None');
insert into acnh_houseware values(1469, 0, 'Luna''s bed', 'unorderable', '900', 'Luna', 'expensive', 'zen-style', 'None');
insert into acnh_houseware values(1470, 0, 'RC helicopter (Blue)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1471, 0, 'RC helicopter (Red)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1472, 0, 'RC helicopter (Yellow)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1473, 0, 'RC helicopter (Green)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1474, 0, 'RC helicopter (Pink)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1475, 0, 'RC helicopter (Light blue)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1476, 0, 'RC helicopter (Purple)', 'orderable', '3600', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_houseware values(1477, 0, 'rodeo-style springy ride-on', 'unorderable', '500', 'Nook Shopping Seasonal', 'fancy', 'garden', 'None');
insert into acnh_houseware values(1478, 0, 'spooky arch', 'unorderable', '4500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1479, 0, 'spooky arch', 'unorderable', '4500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1480, 0, 'spooky arch', 'unorderable', '4500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1481, 0, 'spooky arch', 'unorderable', '4500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1482, 0, 'spooky carriage', 'unorderable', '35700', 'Crafting; Jack', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1483, 0, 'spooky carriage', 'unorderable', '35700', 'Crafting; Jack', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1484, 0, 'spooky carriage', 'unorderable', '35700', 'Crafting; Jack', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1485, 0, 'spooky carriage', 'unorderable', '35700', 'Crafting; Jack', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1486, 0, 'spooky chair', 'unorderable', '1250', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1487, 0, 'spooky chair', 'unorderable', '1250', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1488, 0, 'spooky chair', 'unorderable', '1250', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1489, 0, 'spooky chair', 'unorderable', '1250', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1490, 0, 'spooky lantern', 'unorderable', '1400', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1491, 0, 'spooky lantern', 'unorderable', '1400', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1492, 0, 'spooky lantern', 'unorderable', '1400', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1493, 0, 'spooky lantern', 'unorderable', '1400', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1494, 0, 'spooky lantern set', 'unorderable', '1475', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1495, 0, 'spooky lantern set', 'unorderable', '1475', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1496, 0, 'spooky lantern set', 'unorderable', '1475', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1497, 0, 'spooky lantern set', 'unorderable', '1475', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1498, 0, 'spooky scarecrow', 'unorderable', '1300', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1499, 0, 'spooky scarecrow', 'unorderable', '1300', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1500, 0, 'spooky scarecrow', 'unorderable', '1300', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1501, 0, 'spooky scarecrow', 'unorderable', '1300', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1502, 0, 'spooky standing lamp', 'unorderable', '1450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1503, 0, 'spooky standing lamp', 'unorderable', '1450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1504, 0, 'spooky standing lamp', 'unorderable', '1450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1505, 0, 'spooky standing lamp', 'unorderable', '1450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1506, 0, 'spooky table', 'unorderable', '5500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1507, 0, 'spooky table', 'unorderable', '5500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1508, 0, 'spooky table', 'unorderable', '5500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1509, 0, 'spooky table', 'unorderable', '5500', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1510, 0, 'spooky tower', 'unorderable', '2450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1511, 0, 'spooky tower', 'unorderable', '2450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1512, 0, 'spooky tower', 'unorderable', '2450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1513, 0, 'spooky tower', 'unorderable', '2450', 'Crafting; Nook''s Cranny', 'horror', 'None', 'spooky');
insert into acnh_houseware values(1514, 0, 'Toy Day sleigh', 'unorderable', '20000', 'Jingle', 'fancy', 'None', 'festive');
insert into acnh_houseware values(1515, 0, 'Turkey Day chair', 'unorderable', '550', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1516, 0, 'Turkey Day chair', 'unorderable', '550', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1517, 0, 'Turkey Day garden stand', 'unorderable', '900', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1518, 0, 'Turkey Day garden stand', 'unorderable', '900', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1519, 0, 'Turkey Day hearth', 'unorderable', '3250', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1520, 0, 'Turkey Day hearth', 'unorderable', '3250', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1521, 0, 'Turkey Day table', 'unorderable', '1125', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_houseware values(1522, 0, 'Turkey Day table', 'unorderable', '1125', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_misc values(875, 0, 'berliner', 'unorderable', '300', 'Nook Shopping Seasonal', 'living room', 'party', 'None');
insert into acnh_misc values(876, 0, 'cornucopia', 'unorderable', '2500', 'Franklin', 'party', 'None', 'Turkey Day');
insert into acnh_misc values(877, 0, 'dinosaur toy (Gray)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(878, 0, 'dinosaur toy (Brown)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(879, 0, 'dinosaur toy (Green)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(880, 0, 'dinosaur toy (Blue)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(881, 0, 'dinosaur toy (Red)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(882, 0, 'dollhouse (Red)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(883, 0, 'dollhouse (Brown)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(884, 0, 'dollhouse (Blue)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(885, 0, 'dollhouse (Orange)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(886, 0, 'dollhouse (Green)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(887, 0, 'dollhouse (Pink)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(888, 0, 'dollhouse (Purple)', 'orderable', '4000', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(889, 0, 'kagamimochi', 'unorderable', '450', 'Nook Shopping Seasonal', 'zen-style', 'None', 'None');
insert into acnh_misc values(890, 0, 'mini circuit (Red & white)', 'orderable', '3800', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(891, 0, 'mini circuit (Blue & yellow)', 'orderable', '3800', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(892, 0, 'mini circuit (Black & silver)', 'orderable', '3800', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(893, 0, 'mini circuit (Pink & purple)', 'orderable', '3800', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(894, 0, 'New Year''s noodles', 'unorderable', '325', 'Nook Shopping Seasonal', 'living room', 'kitchen', 'None');
insert into acnh_misc values(895, 0, 'Olivier salad', 'unorderable', '250', 'Nook Shopping Seasonal', 'living room', 'kitchen', 'None');
insert into acnh_misc values(896, 0, 'pop-up book (The ocean blue)', 'orderable', '2000', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(897, 0, 'pop-up book (The Mesozoic world)', 'orderable', '2000', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(898, 0, 'pop-up book (Savannah)', 'orderable', '2000', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(899, 0, 'pop-up book (Flowers)', 'orderable', '2000', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(900, 0, 'puppy plushie (Beige)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(901, 0, 'puppy plushie (Red)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(902, 0, 'puppy plushie (Lemon & white)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(903, 0, 'puppy plushie (Spotted)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(904, 0, 'puppy plushie (Black)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(905, 0, 'puppy plushie (Tricolored)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(906, 0, 'puppy plushie (Gray & white)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(907, 0, 'puppy plushie (Pink)', 'orderable', '2400', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_misc values(908, 0, 'Ring-Con', 'orderable', '4950', 'Nintendo; Nook Shopping Daily Selection', 'fitness', 'living room', 'None');
insert into acnh_misc values(909, 0, 'spooky candy set', 'unorderable', '875', 'Crafting; Nook''s Cranny', 'horror', 'party', 'spooky');
insert into acnh_misc values(910, 0, 'spooky candy set', 'unorderable', '875', 'Crafting; Nook''s Cranny', 'horror', 'party', 'spooky');
insert into acnh_misc values(911, 0, 'spooky candy set', 'unorderable', '875', 'Crafting; Nook''s Cranny', 'horror', 'party', 'spooky');
insert into acnh_misc values(912, 0, 'spooky candy set', 'unorderable', '875', 'Crafting; Nook''s Cranny', 'horror', 'party', 'spooky');
insert into acnh_misc values(913, 0, 'spooky table setting', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_misc values(914, 0, 'spooky table setting', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_misc values(915, 0, 'spooky table setting', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_misc values(916, 0, 'spooky table setting', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_misc values(917, 0, 'tin robot (Silver)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(918, 0, 'tin robot (Blue)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(919, 0, 'tin robot (Red)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(920, 0, 'tin robot (Orange)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(921, 0, 'tin robot (Yellow)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(922, 0, 'tin robot (Green)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(923, 0, 'tin robot (Pink)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(924, 0, 'tin robot (Black)', 'orderable', '3500', 'Nook''s Cranny', 'child''s room', 'None', 'None');
insert into acnh_misc values(925, 0, 'Turkey Day casserole', 'unorderable', '1750', 'Crafting; Nook''s Cranny; Franklin', 'kitchen', 'None', 'None');
insert into acnh_misc values(926, 0, 'Turkey Day casserole', 'unorderable', '1750', 'Crafting; Nook''s Cranny; Franklin', 'kitchen', 'None', 'None');
insert into acnh_misc values(927, 0, 'Turkey Day decorations', 'unorderable', '500', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_misc values(928, 0, 'Turkey Day decorations', 'unorderable', '500', 'Crafting; Nook''s Cranny; Franklin', 'living room', 'party', 'None');
insert into acnh_misc values(929, 0, 'Turkey Day table setting', 'unorderable', '1000', 'Crafting; Nook''s Cranny; Franklin', 'kitchen', 'party', 'None');
insert into acnh_misc values(930, 0, 'Turkey Day table setting', 'unorderable', '1000', 'Crafting; Nook''s Cranny; Franklin', 'kitchen', 'party', 'None');
insert into acnh_misc values(931, 0, 'Turkey Day wheat decor', 'unorderable', '200', 'Crafting; Nook''s Cranny; Franklin', 'party', 'None', 'None');
insert into acnh_misc values(932, 0, 'Turkey Day wheat decor', 'unorderable', '200', 'Crafting; Nook''s Cranny; Franklin', 'party', 'None', 'None');
insert into acnh_misc values(933, 0, 'twelve-grape dish', 'unorderable', '300', 'Nook Shopping Seasonal', 'living room', 'party', 'None');
insert into acnh_misc values(934, 0, 'Yule log (Chocolate)', 'orderable', '1200', 'Nintendo; Nook Shopping Daily Selection', 'living room', 'party', 'festive');
insert into acnh_misc values(935, 0, 'Yule log (Chestnut)', 'orderable', '1200', 'Nintendo; Nook Shopping Daily Selection', 'living room', 'party', 'festive');
insert into acnh_misc values(936, 0, 'Yule log (Whipped-cream topping)', 'orderable', '1200', 'Nintendo; Nook Shopping Daily Selection', 'living room', 'party', 'festive');
insert into acnh_misc values(937, 0, 'Yule log (Strawberry)', 'orderable', '1200', 'Nintendo; Nook Shopping Daily Selection', 'living room', 'party', 'festive');
insert into acnh_misc values(938, 0, 'Yule log (Green tea)', 'orderable', '1200', 'Nintendo; Nook Shopping Daily Selection', 'living room', 'party', 'festive');
insert into acnh_misc values(939, 0, 'Yut Nori', 'unorderable', '325', 'Nook Shopping Seasonal', 'living room', 'child''s room', 'None');
insert into acnh_misc values(940, 0, 'zodiac ox figurine', 'unorderable', '400', 'Nook Shopping Seasonal', 'zen-style', 'None', 'None');
insert into acnh_photo values(392, 0, 'Jingle''s photo', 'Check Toy Day stockings the day after Toy Day');
insert into acnh_recipe values(611, 0, 'falling-snow wall', '3 snowflake, 10 stone', 'snowflakes');
insert into acnh_recipe values(612, 0, 'festive rug', '5 red ornament, 5 blue ornament, 5 gold ornament', 'ornaments');
insert into acnh_recipe values(613, 0, 'festive wrapping paper', '1 red ornament, 1 blue ornament, 1 gold ornament', 'Toy Day');
insert into acnh_recipe values(614, 0, 'gift pile', '3 red wrapping paper, 1 wooden-block toy, 1 cardboard box', 'Toy Day');
insert into acnh_recipe values(615, 0, 'King Tut mask', '5 gold nugget', 'Pick up gold from hitting rocks');
insert into acnh_recipe values(616, 0, 'spooky arch', '10 orange pumpkin, 10 hardwood, 3 clay', 'Halloween');
insert into acnh_recipe values(617, 0, 'spooky candy set', '1 orange pumpkin, 3 candy', 'Halloween');
insert into acnh_recipe values(618, 0, 'spooky carriage', '30 orange pumpkin, 20 hardwood, 20 wood, 20 softwood, 10 iron nugget', 'Halloween');
insert into acnh_recipe values(619, 0, 'spooky chair', '3 orange pumpkin, 3 softwood', 'Halloween');
insert into acnh_recipe values(620, 0, 'spooky fence', '3 orange pumpkin, 5 iron nugget', 'Halloween');
insert into acnh_recipe values(621, 0, 'spooky garland', '1 orange pumpkin, 1 iron nugget, 1 clay', 'Halloween');
insert into acnh_recipe values(622, 0, 'spooky lantern', '4 orange pumpkin', 'Halloween');
insert into acnh_recipe values(623, 0, 'spooky lantern set', '4 orange pumpkin, 4 clump of weeds', 'Halloween');
insert into acnh_recipe values(624, 0, 'spooky scarecrow', '3 orange pumpkin, 4 wood', 'Halloween');
insert into acnh_recipe values(625, 0, 'spooky standing lamp', '3 orange pumpkin, 5 hardwood, 1 clay', 'Halloween');
insert into acnh_recipe values(626, 0, 'spooky table', '14 orange pumpkin, 10 softwood', 'Halloween');
insert into acnh_recipe values(627, 0, 'spooky table setting', '1 orange pumpkin, 1 iron nugget, 1 clay', 'Halloween');
insert into acnh_recipe values(628, 0, 'spooky tower', '7 orange pumpkin', 'Halloween');
insert into acnh_recipe values(629, 0, 'spooky wand', '1 spooky lantern, 3 star fragment', 'Halloween');
insert into acnh_recipe values(630, 0, 'summer-shell rug', '6 summer shell', 'summer shells');
insert into acnh_recipe values(631, 0, 'Turkey Day casserole', '5 iron nugget, 1 clay', 'Turkey Day');
insert into acnh_recipe values(632, 0, 'Turkey Day chair', '5 wood, 2 hardwood, 2 softwood', 'Turkey Day');
insert into acnh_recipe values(633, 0, 'Turkey Day decorations', '2 softwood, 5 clump of weeds, 2 clay', 'Turkey Day');
insert into acnh_recipe values(634, 0, 'Turkey Day garden stand', '8 stone, 3 clay', 'Turkey Day');
insert into acnh_recipe values(635, 0, 'Turkey Day hearth', '1 campfire, 30 stone, 10 clay', 'Turkey Day');
insert into acnh_recipe values(636, 0, 'Turkey Day table', '10 hardwood, 5 softwood', 'Turkey Day');
insert into acnh_recipe values(637, 0, 'Turkey Day table setting', '4 clay, 2 iron nugget', 'Turkey Day');
insert into acnh_recipe values(638, 0, 'Turkey Day wheat decor', '10 clump of weeds', 'Turkey Day');
insert into acnh_rug values(135, 0, 'festive rug', 'unorderable', '1500', 'Crafting', 'party', 'fancy', 'festive');
insert into acnh_rug values(136, 0, 'moon rug', 'unorderable', '500', 'Nook Shopping Seasonal', 'space', 'zen-style', 'None');
insert into acnh_rug values(137, 0, 'spooky rug', 'unorderable', '2000', 'Villagers', 'horror', 'None', 'spooky');
insert into acnh_rug values(138, 0, 'summer-shell rug', 'unorderable', '7200', 'Crafting', 'ocean', 'fancy', 'None');
insert into acnh_rug values(139, 0, 'sunflower rug', 'unorderable', '375', 'Nook Shopping Seasonal', 'fancy', 'child''s room', 'flowers');
insert into acnh_rug values(140, 0, 'Turkey Day rug', 'unorderable', '500', 'Franklin', 'party', 'None', 'None');
insert into acnh_shoe values(458, 0, 'flashy animal boots (White)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(459, 0, 'flashy animal boots (Black)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(460, 0, 'flashy animal boots (Red)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(461, 0, 'flashy animal boots (Orange)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(462, 0, 'flashy animal boots (Green)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(463, 0, 'flashy animal boots (Purple)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(464, 0, 'mage''s boots (White)', 'orderable', '1800', 'Able Sisters', 'Simple');
insert into acnh_shoe values(465, 0, 'mage''s boots (Black)', 'orderable', '1800', 'Able Sisters', 'Simple');
insert into acnh_shoe values(466, 0, 'mage''s boots (Red)', 'orderable', '1800', 'Able Sisters', 'Simple');
insert into acnh_shoe values(467, 0, 'mage''s boots (Orange)', 'orderable', '1800', 'Able Sisters', 'Simple');
insert into acnh_shoe values(468, 0, 'mage''s boots (Green)', 'orderable', '1800', 'Able Sisters', 'Simple');
insert into acnh_shoe values(469, 0, 'mage''s boots (Purple)', 'orderable', '1800', 'Able Sisters', 'Simple');
insert into acnh_sock values(351, 0, 'horizontal-striped tights (White)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(352, 0, 'horizontal-striped tights (Black)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(353, 0, 'horizontal-striped tights (Red)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(354, 0, 'horizontal-striped tights (Orange)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(355, 0, 'horizontal-striped tights (Green)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(356, 0, 'horizontal-striped tights (Purple)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_top values(1125, 0, 'Santa coat', 'orderable', '2600', 'Able Sisters', 'Simple');
insert into acnh_wall_mounted values(322, 0, 'festive wreath', 'unorderable', '375', 'All villagers', 'party', 'fancy', 'festive');
insert into acnh_wall_mounted values(323, 0, 'Jack''s portrait', 'unorderable', '2000', 'Jack', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(324, 0, 'New Year''s shimekazari', 'unorderable', '500', 'Nook Shopping Seasonal', 'zen-style', 'None', 'None');
insert into acnh_wall_mounted values(325, 0, 'set of stockings (Colorful)', 'orderable', '2000', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wall_mounted values(326, 0, 'set of stockings (Cute)', 'orderable', '2000', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wall_mounted values(327, 0, 'set of stockings (Cool)', 'orderable', '2000', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wall_mounted values(328, 0, 'set of stockings (Chic)', 'orderable', '2000', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wall_mounted values(329, 0, 'set of stockings (Elegant)', 'orderable', '2000', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wall_mounted values(330, 0, 'set of stockings (Natural)', 'orderable', '2000', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wall_mounted values(331, 0, 'spooky garland', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_wall_mounted values(332, 0, 'spooky garland', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_wall_mounted values(333, 0, 'spooky garland', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_wall_mounted values(334, 0, 'spooky garland', 'unorderable', '1650', 'Crafting; All villagers', 'horror', 'party', 'spooky');
insert into acnh_wall_mounted values(335, 0, 'Toy Day stockings', 'unorderable', '500', 'Jingle', 'child''s room', 'fancy', 'festive');
insert into acnh_wallpaper values(250, 0, 'aurora wall', 'unorderable', '1750', 'Nook Shopping Seasonal', 'freezing cold', 'fancy', 'None');
insert into acnh_wallpaper values(251, 0, 'falling-snow wall', 'unorderable', '2700', 'Crafting', 'freezing cold', 'None', 'None');
insert into acnh_wallpaper values(252, 0, 'fireworks-show wall', 'unorderable', '750', 'Saharah; Nintendo', 'outdoors', 'ocean', 'None');
insert into acnh_wallpaper values(253, 0, 'spooky wall', 'unorderable', '3000', 'All villagers', 'horror', 'None', 'spooky');
insert into acnh_wallpaper values(254, 0, 'Turkey Day wall', 'unorderable', '750', 'Franklin', 'party', 'None', 'None');