drop table if exists acnh_other_clothing;
create table acnh_other_clothing ("Index" int, Selected int, Name varchar(63), Status varchar(31), Price varchar(31), "From" varchar(63), Style varchar(31));
insert into acnh_other_clothing values(1, 0, 'horizontal-striped wet suit (Black)', 'orderable', '3000', 'Nook''s Cranny (Summer)', 'Active');
insert into acnh_other_clothing values(2, 0, 'horizontal-striped wet suit (Red)', 'orderable', '3000', 'Nook''s Cranny (Summer)', 'Active');
insert into acnh_other_clothing values(3, 0, 'horizontal-striped wet suit (Yellow)', 'orderable', '3000', 'Nook''s Cranny (Summer)', 'Active');
insert into acnh_other_clothing values(4, 0, 'horizontal-striped wet suit (Blue)', 'orderable', '3000', 'Nook''s Cranny (Summer)', 'Active');
insert into acnh_other_clothing values(5, 0, 'leaf-print wet suit (Yellow)', 'orderable', '3000', 'Nook Shopping Catalog (Summer)', 'Active');
insert into acnh_other_clothing values(6, 0, 'leaf-print wet suit (Green)', 'orderable', '3000', 'Nook Shopping Catalog (Summer)', 'Active');
insert into acnh_other_clothing values(7, 0, 'leaf-print wet suit (Light blue)', 'orderable', '3000', 'Nook Shopping Catalog (Summer)', 'Active');
insert into acnh_other_clothing values(8, 0, 'leaf-print wet suit (Purple)', 'orderable', '3000', 'Nook Shopping Catalog (Summer)', 'Active');
insert into acnh_other_clothing values(9, 0, 'Nook Inc. wet suit', 'unorderable', '4000', 'Nook Miles Shop (Summer)', 'Active');
drop table if exists acnh_sea_creature;
create table acnh_sea_creature ("Index" int, Selected int, Name varchar(63), Price varchar(15), Shadow varchar(15), "Catches to Unlock" varchar(7), "Times" varchar(127));
insert into acnh_sea_creature values(1, 0, 'seaweed', '600', 'Large', '0', 'All day');
insert into acnh_sea_creature values(2, 0, 'sea grapes', '900', 'Small', '0', 'All day');
insert into acnh_sea_creature values(3, 0, 'sea cucumber', '500', 'Medium', '0', 'All day');
insert into acnh_sea_creature values(4, 0, 'sea pig', '10000', 'Small', '80', '4 PM – 9 AM');
insert into acnh_sea_creature values(5, 0, 'sea star', '500', 'Small', '0', 'All day');
insert into acnh_sea_creature values(6, 0, 'sea urchin', '1700', 'Small', '0', 'All day');
insert into acnh_sea_creature values(7, 0, 'slate pencil urchin', '2000', 'Medium', '20', '4 PM – 9 AM');
insert into acnh_sea_creature values(8, 0, 'sea anemone', '500', 'Large', '0', 'All day');
insert into acnh_sea_creature values(9, 0, 'moon jellyfish', '600', 'Small', '0', 'All day');
insert into acnh_sea_creature values(10, 0, 'sea slug', '600', 'X-Small', '0', 'All day');
insert into acnh_sea_creature values(11, 0, 'pearl oyster', '2800', 'Small', '20', 'All day');
insert into acnh_sea_creature values(12, 0, 'mussel', '1500', 'Small', '0', 'All day');
insert into acnh_sea_creature values(13, 0, 'oyster', '1100', 'Small', '0', 'All day');
insert into acnh_sea_creature values(14, 0, 'scallop', '1200', 'Medium', '5', 'All day');
insert into acnh_sea_creature values(15, 0, 'whelk', '1000', 'Small', '0', 'All day');
insert into acnh_sea_creature values(16, 0, 'turban shell', '1000', 'Small', '0', 'All day');
insert into acnh_sea_creature values(17, 0, 'abalone', '2000', 'Medium', '20', '4 PM – 9 AM');
insert into acnh_sea_creature values(18, 0, 'gigas giant clam', '15000', 'X-Large', '80', 'All day');
insert into acnh_sea_creature values(19, 0, 'chambered nautilus', '1800', 'Medium', '20', '4 PM – 9 AM');
insert into acnh_sea_creature values(20, 0, 'octopus', '1200', 'Medium', '0', 'All day');
insert into acnh_sea_creature values(21, 0, 'umbrella octopus', '6000', 'Small', '40', 'All day');
insert into acnh_sea_creature values(22, 0, 'vampire squid', '10000', 'Medium', '80', '4 PM – 9 AM');
insert into acnh_sea_creature values(23, 0, 'firefly squid', '1400', 'X-Small', '0', '9 PM – 4 AM');
insert into acnh_sea_creature values(24, 0, 'gazami crab', '2200', 'Medium', '20', 'All day');
insert into acnh_sea_creature values(25, 0, 'Dungeness crab', '1900', 'Medium', '20', 'All day');
insert into acnh_sea_creature values(26, 0, 'snow crab', '6000', 'Large', '40', 'All day');
insert into acnh_sea_creature values(27, 0, 'red king crab', '8000', 'Large', '80', 'All day');
insert into acnh_sea_creature values(28, 0, 'acorn barnacle', '600', 'X-Small', '0', 'All day');
insert into acnh_sea_creature values(29, 0, 'spider crab', '12000', 'X-Large', '80', 'All day');
insert into acnh_sea_creature values(30, 0, 'tiger prawn', '3000', 'Small', '20', '4 PM – 9 AM');
insert into acnh_sea_creature values(31, 0, 'sweet shrimp', '1400', 'Small', '0', '4 PM – 9 AM');
insert into acnh_sea_creature values(32, 0, 'mantis shrimp', '2500', 'Small', '20', '4 PM – 9 AM');
insert into acnh_sea_creature values(33, 0, 'spiny lobster', '5000', 'Large', '40', '9 PM – 4 AM');
insert into acnh_sea_creature values(34, 0, 'lobster', '4500', 'Large', '40', 'All day');
insert into acnh_sea_creature values(35, 0, 'giant isopod', '12000', 'Medium', '80', '9 AM – 4 PM; 9 PM – 4 AM');
insert into acnh_sea_creature values(36, 0, 'horseshoe crab', '2500', 'Medium', '20', '9 PM – 4 AM');
insert into acnh_sea_creature values(37, 0, 'sea pineapple', '1500', 'Small', '0', 'All day');
insert into acnh_sea_creature values(38, 0, 'spotted garden eel', '1100', 'Small', '0', '4 AM – 9 PM');
insert into acnh_sea_creature values(39, 0, 'flatworm', '700', 'X-Small', '0', '4 PM – 9 AM');
insert into acnh_sea_creature values(40, 0, 'Venus'' flower basket', '5000', 'Medium', '40', 'All day');
drop table if exists acnh_jan_sea_creature;
drop table if exists acnh_feb_sea_creature;
drop table if exists acnh_mar_sea_creature;
drop table if exists acnh_apr_sea_creature;
drop table if exists acnh_may_sea_creature;
drop table if exists acnh_jun_sea_creature;
drop table if exists acnh_jul_sea_creature;
drop table if exists acnh_aug1_sea_creature;
drop table if exists acnh_aug2_sea_creature;
drop table if exists acnh_sep1_sea_creature;
drop table if exists acnh_sep2_sea_creature;
drop table if exists acnh_oct_sea_creature;
drop table if exists acnh_nov_sea_creature;
drop table if exists acnh_dec_sea_creature;
create table acnh_jan_sea_creature (id int);
create table acnh_feb_sea_creature (id int);
create table acnh_mar_sea_creature (id int);
create table acnh_apr_sea_creature (id int);
create table acnh_may_sea_creature (id int);
create table acnh_jun_sea_creature (id int);
create table acnh_jul_sea_creature (id int);
create table acnh_aug1_sea_creature (id int);
create table acnh_aug2_sea_creature (id int);
create table acnh_sep1_sea_creature (id int);
create table acnh_sep2_sea_creature (id int);
create table acnh_oct_sea_creature (id int);
create table acnh_nov_sea_creature (id int);
create table acnh_dec_sea_creature (id int);
insert into acnh_jan_sea_creature values (1);
insert into acnh_feb_sea_creature values (1);
insert into acnh_mar_sea_creature values (1);
insert into acnh_apr_sea_creature values (1);
insert into acnh_may_sea_creature values (1);
insert into acnh_jun_sea_creature values (1);
insert into acnh_jul_sea_creature values (1);
insert into acnh_oct_sea_creature values (1);
insert into acnh_nov_sea_creature values (1);
insert into acnh_dec_sea_creature values (1);
insert into acnh_jun_sea_creature values (2);
insert into acnh_jul_sea_creature values (2);
insert into acnh_aug1_sea_creature values (2);
insert into acnh_aug2_sea_creature values (2);
insert into acnh_sep1_sea_creature values (2);
insert into acnh_sep2_sea_creature values (2);
insert into acnh_jan_sea_creature values (3);
insert into acnh_feb_sea_creature values (3);
insert into acnh_mar_sea_creature values (3);
insert into acnh_apr_sea_creature values (3);
insert into acnh_nov_sea_creature values (3);
insert into acnh_dec_sea_creature values (3);
insert into acnh_jan_sea_creature values (4);
insert into acnh_feb_sea_creature values (4);
insert into acnh_nov_sea_creature values (4);
insert into acnh_dec_sea_creature values (4);
insert into acnh_jan_sea_creature values (5);
insert into acnh_feb_sea_creature values (5);
insert into acnh_mar_sea_creature values (5);
insert into acnh_apr_sea_creature values (5);
insert into acnh_may_sea_creature values (5);
insert into acnh_jun_sea_creature values (5);
insert into acnh_jul_sea_creature values (5);
insert into acnh_aug1_sea_creature values (5);
insert into acnh_aug2_sea_creature values (5);
insert into acnh_sep1_sea_creature values (5);
insert into acnh_sep2_sea_creature values (5);
insert into acnh_oct_sea_creature values (5);
insert into acnh_nov_sea_creature values (5);
insert into acnh_dec_sea_creature values (5);
insert into acnh_may_sea_creature values (6);
insert into acnh_jun_sea_creature values (6);
insert into acnh_jul_sea_creature values (6);
insert into acnh_aug1_sea_creature values (6);
insert into acnh_aug2_sea_creature values (6);
insert into acnh_sep1_sea_creature values (6);
insert into acnh_sep2_sea_creature values (6);
insert into acnh_may_sea_creature values (7);
insert into acnh_jun_sea_creature values (7);
insert into acnh_jul_sea_creature values (7);
insert into acnh_aug1_sea_creature values (7);
insert into acnh_aug2_sea_creature values (7);
insert into acnh_sep1_sea_creature values (7);
insert into acnh_sep2_sea_creature values (7);
insert into acnh_jan_sea_creature values (8);
insert into acnh_feb_sea_creature values (8);
insert into acnh_mar_sea_creature values (8);
insert into acnh_apr_sea_creature values (8);
insert into acnh_may_sea_creature values (8);
insert into acnh_jun_sea_creature values (8);
insert into acnh_jul_sea_creature values (8);
insert into acnh_aug1_sea_creature values (8);
insert into acnh_aug2_sea_creature values (8);
insert into acnh_sep1_sea_creature values (8);
insert into acnh_sep2_sea_creature values (8);
insert into acnh_oct_sea_creature values (8);
insert into acnh_nov_sea_creature values (8);
insert into acnh_dec_sea_creature values (8);
insert into acnh_jul_sea_creature values (9);
insert into acnh_aug1_sea_creature values (9);
insert into acnh_aug2_sea_creature values (9);
insert into acnh_sep1_sea_creature values (9);
insert into acnh_sep2_sea_creature values (9);
insert into acnh_jan_sea_creature values (10);
insert into acnh_feb_sea_creature values (10);
insert into acnh_mar_sea_creature values (10);
insert into acnh_apr_sea_creature values (10);
insert into acnh_may_sea_creature values (10);
insert into acnh_jun_sea_creature values (10);
insert into acnh_jul_sea_creature values (10);
insert into acnh_aug1_sea_creature values (10);
insert into acnh_aug2_sea_creature values (10);
insert into acnh_sep1_sea_creature values (10);
insert into acnh_sep2_sea_creature values (10);
insert into acnh_oct_sea_creature values (10);
insert into acnh_nov_sea_creature values (10);
insert into acnh_dec_sea_creature values (10);
insert into acnh_jan_sea_creature values (11);
insert into acnh_feb_sea_creature values (11);
insert into acnh_mar_sea_creature values (11);
insert into acnh_apr_sea_creature values (11);
insert into acnh_may_sea_creature values (11);
insert into acnh_jun_sea_creature values (11);
insert into acnh_jul_sea_creature values (11);
insert into acnh_aug1_sea_creature values (11);
insert into acnh_aug2_sea_creature values (11);
insert into acnh_sep1_sea_creature values (11);
insert into acnh_sep2_sea_creature values (11);
insert into acnh_oct_sea_creature values (11);
insert into acnh_nov_sea_creature values (11);
insert into acnh_dec_sea_creature values (11);
insert into acnh_jun_sea_creature values (12);
insert into acnh_jul_sea_creature values (12);
insert into acnh_aug1_sea_creature values (12);
insert into acnh_aug2_sea_creature values (12);
insert into acnh_sep1_sea_creature values (12);
insert into acnh_sep2_sea_creature values (12);
insert into acnh_oct_sea_creature values (12);
insert into acnh_nov_sea_creature values (12);
insert into acnh_dec_sea_creature values (12);
insert into acnh_jan_sea_creature values (13);
insert into acnh_feb_sea_creature values (13);
insert into acnh_sep1_sea_creature values (13);
insert into acnh_sep2_sea_creature values (13);
insert into acnh_oct_sea_creature values (13);
insert into acnh_nov_sea_creature values (13);
insert into acnh_dec_sea_creature values (13);
insert into acnh_jan_sea_creature values (14);
insert into acnh_feb_sea_creature values (14);
insert into acnh_mar_sea_creature values (14);
insert into acnh_apr_sea_creature values (14);
insert into acnh_may_sea_creature values (14);
insert into acnh_jun_sea_creature values (14);
insert into acnh_jul_sea_creature values (14);
insert into acnh_aug1_sea_creature values (14);
insert into acnh_aug2_sea_creature values (14);
insert into acnh_sep1_sea_creature values (14);
insert into acnh_sep2_sea_creature values (14);
insert into acnh_oct_sea_creature values (14);
insert into acnh_nov_sea_creature values (14);
insert into acnh_dec_sea_creature values (14);
insert into acnh_jan_sea_creature values (15);
insert into acnh_feb_sea_creature values (15);
insert into acnh_mar_sea_creature values (15);
insert into acnh_apr_sea_creature values (15);
insert into acnh_may_sea_creature values (15);
insert into acnh_jun_sea_creature values (15);
insert into acnh_jul_sea_creature values (15);
insert into acnh_aug1_sea_creature values (15);
insert into acnh_aug2_sea_creature values (15);
insert into acnh_sep1_sea_creature values (15);
insert into acnh_sep2_sea_creature values (15);
insert into acnh_oct_sea_creature values (15);
insert into acnh_nov_sea_creature values (15);
insert into acnh_dec_sea_creature values (15);
insert into acnh_mar_sea_creature values (16);
insert into acnh_apr_sea_creature values (16);
insert into acnh_may_sea_creature values (16);
insert into acnh_sep1_sea_creature values (16);
insert into acnh_sep2_sea_creature values (16);
insert into acnh_oct_sea_creature values (16);
insert into acnh_nov_sea_creature values (16);
insert into acnh_dec_sea_creature values (16);
insert into acnh_jan_sea_creature values (17);
insert into acnh_jun_sea_creature values (17);
insert into acnh_jul_sea_creature values (17);
insert into acnh_aug1_sea_creature values (17);
insert into acnh_aug2_sea_creature values (17);
insert into acnh_sep1_sea_creature values (17);
insert into acnh_sep2_sea_creature values (17);
insert into acnh_oct_sea_creature values (17);
insert into acnh_nov_sea_creature values (17);
insert into acnh_dec_sea_creature values (17);
insert into acnh_may_sea_creature values (18);
insert into acnh_jun_sea_creature values (18);
insert into acnh_jul_sea_creature values (18);
insert into acnh_aug1_sea_creature values (18);
insert into acnh_aug2_sea_creature values (18);
insert into acnh_sep1_sea_creature values (18);
insert into acnh_sep2_sea_creature values (18);
insert into acnh_mar_sea_creature values (19);
insert into acnh_apr_sea_creature values (19);
insert into acnh_may_sea_creature values (19);
insert into acnh_jun_sea_creature values (19);
insert into acnh_sep1_sea_creature values (19);
insert into acnh_sep2_sea_creature values (19);
insert into acnh_oct_sea_creature values (19);
insert into acnh_nov_sea_creature values (19);
insert into acnh_jan_sea_creature values (20);
insert into acnh_feb_sea_creature values (20);
insert into acnh_mar_sea_creature values (20);
insert into acnh_apr_sea_creature values (20);
insert into acnh_may_sea_creature values (20);
insert into acnh_jun_sea_creature values (20);
insert into acnh_jul_sea_creature values (20);
insert into acnh_aug1_sea_creature values (20);
insert into acnh_aug2_sea_creature values (20);
insert into acnh_sep1_sea_creature values (20);
insert into acnh_sep2_sea_creature values (20);
insert into acnh_oct_sea_creature values (20);
insert into acnh_nov_sea_creature values (20);
insert into acnh_dec_sea_creature values (20);
insert into acnh_mar_sea_creature values (21);
insert into acnh_apr_sea_creature values (21);
insert into acnh_may_sea_creature values (21);
insert into acnh_sep1_sea_creature values (21);
insert into acnh_sep2_sea_creature values (21);
insert into acnh_oct_sea_creature values (21);
insert into acnh_nov_sea_creature values (21);
insert into acnh_may_sea_creature values (22);
insert into acnh_jun_sea_creature values (22);
insert into acnh_jul_sea_creature values (22);
insert into acnh_aug1_sea_creature values (22);
insert into acnh_aug2_sea_creature values (22);
insert into acnh_mar_sea_creature values (23);
insert into acnh_apr_sea_creature values (23);
insert into acnh_may_sea_creature values (23);
insert into acnh_jun_sea_creature values (23);
insert into acnh_jun_sea_creature values (24);
insert into acnh_jul_sea_creature values (24);
insert into acnh_aug1_sea_creature values (24);
insert into acnh_aug2_sea_creature values (24);
insert into acnh_sep1_sea_creature values (24);
insert into acnh_sep2_sea_creature values (24);
insert into acnh_oct_sea_creature values (24);
insert into acnh_nov_sea_creature values (24);
insert into acnh_jan_sea_creature values (25);
insert into acnh_feb_sea_creature values (25);
insert into acnh_mar_sea_creature values (25);
insert into acnh_apr_sea_creature values (25);
insert into acnh_may_sea_creature values (25);
insert into acnh_nov_sea_creature values (25);
insert into acnh_dec_sea_creature values (25);
insert into acnh_jan_sea_creature values (26);
insert into acnh_feb_sea_creature values (26);
insert into acnh_mar_sea_creature values (26);
insert into acnh_apr_sea_creature values (26);
insert into acnh_nov_sea_creature values (26);
insert into acnh_dec_sea_creature values (26);
insert into acnh_jan_sea_creature values (27);
insert into acnh_feb_sea_creature values (27);
insert into acnh_mar_sea_creature values (27);
insert into acnh_nov_sea_creature values (27);
insert into acnh_dec_sea_creature values (27);
insert into acnh_jan_sea_creature values (28);
insert into acnh_feb_sea_creature values (28);
insert into acnh_mar_sea_creature values (28);
insert into acnh_apr_sea_creature values (28);
insert into acnh_may_sea_creature values (28);
insert into acnh_jun_sea_creature values (28);
insert into acnh_jul_sea_creature values (28);
insert into acnh_aug1_sea_creature values (28);
insert into acnh_aug2_sea_creature values (28);
insert into acnh_sep1_sea_creature values (28);
insert into acnh_sep2_sea_creature values (28);
insert into acnh_oct_sea_creature values (28);
insert into acnh_nov_sea_creature values (28);
insert into acnh_dec_sea_creature values (28);
insert into acnh_mar_sea_creature values (29);
insert into acnh_apr_sea_creature values (29);
insert into acnh_jun_sea_creature values (30);
insert into acnh_jul_sea_creature values (30);
insert into acnh_aug1_sea_creature values (30);
insert into acnh_aug2_sea_creature values (30);
insert into acnh_sep1_sea_creature values (30);
insert into acnh_sep2_sea_creature values (30);
insert into acnh_jan_sea_creature values (31);
insert into acnh_feb_sea_creature values (31);
insert into acnh_sep1_sea_creature values (31);
insert into acnh_sep2_sea_creature values (31);
insert into acnh_oct_sea_creature values (31);
insert into acnh_nov_sea_creature values (31);
insert into acnh_dec_sea_creature values (31);
insert into acnh_jan_sea_creature values (32);
insert into acnh_feb_sea_creature values (32);
insert into acnh_mar_sea_creature values (32);
insert into acnh_apr_sea_creature values (32);
insert into acnh_may_sea_creature values (32);
insert into acnh_jun_sea_creature values (32);
insert into acnh_jul_sea_creature values (32);
insert into acnh_aug1_sea_creature values (32);
insert into acnh_aug2_sea_creature values (32);
insert into acnh_sep1_sea_creature values (32);
insert into acnh_sep2_sea_creature values (32);
insert into acnh_oct_sea_creature values (32);
insert into acnh_nov_sea_creature values (32);
insert into acnh_dec_sea_creature values (32);
insert into acnh_oct_sea_creature values (33);
insert into acnh_nov_sea_creature values (33);
insert into acnh_dec_sea_creature values (33);
insert into acnh_jan_sea_creature values (34);
insert into acnh_apr_sea_creature values (34);
insert into acnh_may_sea_creature values (34);
insert into acnh_jun_sea_creature values (34);
insert into acnh_dec_sea_creature values (34);
insert into acnh_jul_sea_creature values (35);
insert into acnh_aug1_sea_creature values (35);
insert into acnh_aug2_sea_creature values (35);
insert into acnh_sep1_sea_creature values (35);
insert into acnh_sep2_sea_creature values (35);
insert into acnh_oct_sea_creature values (35);
insert into acnh_jul_sea_creature values (36);
insert into acnh_aug1_sea_creature values (36);
insert into acnh_aug2_sea_creature values (36);
insert into acnh_sep1_sea_creature values (36);
insert into acnh_sep2_sea_creature values (36);
insert into acnh_apr_sea_creature values (37);
insert into acnh_may_sea_creature values (37);
insert into acnh_jun_sea_creature values (37);
insert into acnh_jul_sea_creature values (37);
insert into acnh_aug1_sea_creature values (37);
insert into acnh_aug2_sea_creature values (37);
insert into acnh_may_sea_creature values (38);
insert into acnh_jun_sea_creature values (38);
insert into acnh_jul_sea_creature values (38);
insert into acnh_aug1_sea_creature values (38);
insert into acnh_aug2_sea_creature values (38);
insert into acnh_sep1_sea_creature values (38);
insert into acnh_sep2_sea_creature values (38);
insert into acnh_oct_sea_creature values (38);
insert into acnh_aug1_sea_creature values (39);
insert into acnh_aug2_sea_creature values (39);
insert into acnh_sep1_sea_creature values (39);
insert into acnh_sep2_sea_creature values (39);
insert into acnh_jan_sea_creature values (40);
insert into acnh_feb_sea_creature values (40);
insert into acnh_oct_sea_creature values (40);
insert into acnh_nov_sea_creature values (40);
insert into acnh_dec_sea_creature values (40);
drop table if exists acnh_table;
create table acnh_table ("Table" varchar(63));
insert into acnh_table values ('accessory'), ('art'), ('bag'), ('bottom'), ('dress'), ('fencing'), ('fish'), ('flooring'), ('fossil'), ('headwear'), ('houseware'), ('hybrid'), ('insect'), ('misc'), ("other_clothing"), ('photo'), ('poster'), ('recipe'), ('rug'), ("sea_creature"), ('shoe'), ('sock'), ('song'), ('tool'), ('top'), ('umbrella'), ('wall_mounted'), ('wallpaper');
insert into acnh_accessory values(223, 0, 'Nook Inc. snorkel', 'unorderable', '2500', 'Nook Miles Shop', 'Active');
insert into acnh_accessory values(224, 0, 'pirate beard', 'unorderable', '245', 'Gullivarrr', 'Cool');
insert into acnh_accessory values(225, 0, 'pirate eye patch', 'unorderable', '70', 'Gullivarrr', 'Cool');
insert into acnh_accessory values(226, 0, 'snorkel mask (Black)', 'orderable', '700', 'Nintendo; Able Sisters', 'Active');
insert into acnh_accessory values(227, 0, 'snorkel mask (Red)', 'orderable', '700', 'Nintendo; Able Sisters', 'Active');
insert into acnh_accessory values(228, 0, 'snorkel mask (Pink)', 'orderable', '700', 'Nintendo; Able Sisters', 'Active');
insert into acnh_accessory values(229, 0, 'snorkel mask (Orange)', 'orderable', '700', 'Nintendo; Able Sisters', 'Active');
insert into acnh_accessory values(230, 0, 'snorkel mask (Green)', 'orderable', '700', 'Nintendo; Able Sisters', 'Active');
insert into acnh_accessory values(231, 0, 'snorkel mask (Blue)', 'orderable', '700', 'Nintendo; Able Sisters', 'Active');
insert into acnh_bottom values(727, 0, 'pirate pants', 'unorderable', '800', 'Gullivarrr', 'Cool');
insert into acnh_dress values(912, 0, 'wedding dress', 'unorderable', '5000', 'Cyrus', 'Elegant');
insert into acnh_dress values(913, 0, 'mermaid fishy dress (Pink)', 'unorderable', '1000', 'Pascal', 'Cute');
insert into acnh_dress values(914, 0, 'mermaid fishy dress (Light blue)', 'unorderable', '1000', 'Pascal', 'Cute');
insert into acnh_dress values(915, 0, 'mermaid princess dress (Pink)', 'unorderable', '1500', 'Pascal', 'Cute');
insert into acnh_dress values(916, 0, 'mermaid princess dress (Light blue)', 'unorderable', '1500', 'Pascal', 'Cute');
insert into acnh_dress values(917, 0, 'pirate dress (Black)', 'unorderable', '630', 'Gullivarrr', 'Cool');
insert into acnh_dress values(918, 0, 'pirate dress (Red)', 'unorderable', '630', 'Gullivarrr', 'Cool');
insert into acnh_dress values(919, 0, 'pirate dress (Blue)', 'unorderable', '630', 'Gullivarrr', 'Cool');
insert into acnh_dress values(920, 0, 'pirate outfit (Black)', 'unorderable', '750', 'Gullivarrr', 'Cool');
insert into acnh_dress values(921, 0, 'pirate outfit (Red)', 'unorderable', '750', 'Gullivarrr', 'Cool');
insert into acnh_dress values(922, 0, 'pirate outfit (Blue)', 'unorderable', '750', 'Gullivarrr', 'Cool');
insert into acnh_dress values(923, 0, 'pirate-treasure robe', 'unorderable', '3000', 'Gullivarrr', 'Gorgeous');
insert into acnh_dress values(924, 0, 'wedding tuxedo', 'unorderable', '3000', 'Cyrus', 'Elegant');
insert into acnh_headwear values(696, 0, 'bridal veil', 'unorderable', '1150', 'Cyrus', 'Elegant');
insert into acnh_headwear values(697, 0, 'handmade crown', 'unorderable', '75', 'Nook Shopping Seasonal', 'Active');
insert into acnh_headwear values(698, 0, 'mermaid tiara', 'unorderable', '1250', 'Pascal', 'Cute');
insert into acnh_headwear values(699, 0, 'pirate bandanna (Black)', 'unorderable', '200', 'Gullivarrr', 'Cool');
insert into acnh_headwear values(700, 0, 'pirate bandanna (Red)', 'unorderable', '200', 'Gullivarrr', 'Cool');
insert into acnh_headwear values(701, 0, 'pirate bandanna (Blue)', 'unorderable', '200', 'Gullivarrr', 'Cool');
insert into acnh_headwear values(702, 0, 'pirate-treasure crown', 'unorderable', '2500', 'Gullivarrr', 'Gorgeous');
insert into acnh_headwear values(703, 0, 'pirate''s hat', 'unorderable', '860', 'Gullivarrr', 'Cool');
insert into acnh_headwear values(704, 0, 'summer-solstice crown', 'unorderable', '390', 'Nook Shopping Seasonal', 'Active');
insert into acnh_shoe values(453, 0, 'mermaid shoes (Pink)', 'unorderable', '450', 'Pascal', 'Cute');
insert into acnh_shoe values(454, 0, 'mermaid shoes (Light blue)', 'unorderable', '450', 'Pascal', 'Cute');
insert into acnh_shoe values(455, 0, 'pirate boots', 'unorderable', '660', 'Gullivarrr', 'Cool');
insert into acnh_shoe values(456, 0, 'wedding pumps', 'unorderable', '750', 'Cyrus', 'Elegant');
insert into acnh_shoe values(457, 0, 'wedding shoes', 'unorderable', '750', 'Cyrus', 'Elegant');
insert into acnh_top values(1118, 0, 'Coral Nook Inc. aloha shirt', 'unorderable', '3000', 'Nook Miles Shop', 'Simple');
insert into acnh_top values(1119, 0, 'Green Nook Inc. aloha shirt', 'unorderable', '3000', 'Nook Miles Shop', 'Simple');
insert into acnh_top values(1120, 0, 'handmade cape', 'unorderable', '125', 'Nook Shopping Seasonal', 'Active');
insert into acnh_top values(1121, 0, 'sea captain''s coat (Black)', 'unorderable', '1200', 'Gullivarrr', 'Cool');
insert into acnh_top values(1122, 0, 'sea captain''s coat (Red)', 'unorderable', '1200', 'Gullivarrr', 'Cool');
insert into acnh_top values(1123, 0, 'sea captain''s coat (Blue)', 'unorderable', '1200', 'Gullivarrr', 'Cool');
insert into acnh_top values(1124, 0, 'winter-solstice sweater', 'unorderable', '300', 'Nook Shopping Seasonal', 'Simple');
insert into acnh_fencing values(18, 0, 'hedge', '55', 'Crafting');
insert into acnh_fencing values(19, 0, 'wedding fence', '411', 'Crafting');
insert into acnh_flooring values(174, 0, 'brown wedding flooring', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_flooring values(175, 0, 'green wedding flooring', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_flooring values(176, 0, 'mermaid flooring', 'unorderable', '20975', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_flooring values(177, 0, 'pirate flooring', 'unorderable', '750', 'Gullivarrr', 'ocean', 'expensive', 'pirate');
insert into acnh_flooring values(178, 0, 'white wedding flooring', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1409, 0, 'bamboo grass', 'unorderable', '770', 'Nook Shopping Seasonal', 'zen-style', 'folk art', 'None');
insert into acnh_houseware values(1410, 0, 'mermaid bed', 'unorderable', '22400', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1411, 0, 'mermaid chair', 'unorderable', '11140', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1412, 0, 'mermaid closet', 'unorderable', '22500', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1413, 0, 'mermaid dresser', 'unorderable', '22400', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1414, 0, 'mermaid lamp', 'unorderable', '13850', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1415, 0, 'mermaid screen', 'unorderable', '23300', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1416, 0, 'mermaid shelf', 'unorderable', '12900', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1417, 0, 'mermaid sofa', 'unorderable', '11200', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1418, 0, 'mermaid table', 'unorderable', '10480', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1419, 0, 'mermaid vanity', 'unorderable', '12650', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_houseware values(1420, 0, 'pirate barrel', 'unorderable', '200', 'Gullivarrr', 'ocean', 'garage', 'pirate');
insert into acnh_houseware values(1421, 0, 'pirate-ship cannon', 'unorderable', '455', 'Gullivarrr', 'ocean', 'horror', 'pirate');
insert into acnh_houseware values(1422, 0, 'pirate-ship helm', 'unorderable', '280', 'Gullivarrr', 'ocean', 'None', 'pirate');
insert into acnh_houseware values(1423, 0, 'pirate-treasure chest', 'unorderable', '20000', 'Gullivarrr', 'ocean', 'expensive', 'pirate');
insert into acnh_houseware values(1424, 0, 'sideways pirate barrel', 'unorderable', '200', 'Gullivarrr', 'ocean', 'garage', 'pirate');
insert into acnh_houseware values(1425, 0, 'wedding arch (Cute)', 'unorderable', '5000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1426, 0, 'wedding arch (Chic)', 'unorderable', '5000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1427, 0, 'wedding arch (Garden)', 'unorderable', '5000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1428, 0, 'wedding bench (Cute)', 'unorderable', '875', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1429, 0, 'wedding bench (Chic)', 'unorderable', '875', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1430, 0, 'wedding bench (Garden)', 'unorderable', '875', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1431, 0, 'wedding chair (Cute)', 'unorderable', '500', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1432, 0, 'wedding chair (Chic)', 'unorderable', '500', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1433, 0, 'wedding chair (Garden)', 'unorderable', '500', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1434, 0, 'wedding flower stand (Cute)', 'unorderable', '1000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1435, 0, 'wedding flower stand (Chic)', 'unorderable', '1000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1436, 0, 'wedding flower stand (Garden)', 'unorderable', '1000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1437, 0, 'wedding head table (Cute)', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1438, 0, 'wedding head table (Chic)', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1439, 0, 'wedding head table (Garden)', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1440, 0, 'wedding pipe organ (White)', 'unorderable', '25000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1441, 0, 'wedding pipe organ (Dark brown)', 'unorderable', '25000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1442, 0, 'wedding pipe organ (Natural)', 'unorderable', '25000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1443, 0, 'wedding table (Cute)', 'unorderable', '1500', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1444, 0, 'wedding table (Chic)', 'unorderable', '1500', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1445, 0, 'wedding table (Garden)', 'unorderable', '1500', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1446, 0, 'wedding welcome board (Cute)', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1447, 0, 'wedding welcome board (Cute)', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1448, 0, 'wedding welcome board (Chic)', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1449, 0, 'wedding welcome board (Chic)', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1450, 0, 'wedding welcome board (Garden)', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_houseware values(1451, 0, 'wedding welcome board (Garden)', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(865, 0, 'Reese & Cyrus photo plate', 'unorderable', '100', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(866, 0, 'Rover''s briefcase', 'unorderable', '2000', 'Rover', 'living room', 'None', 'None');
insert into acnh_misc values(867, 0, 'thank-you Dad mug', 'unorderable', '150', 'Nook Shopping Seasonal', 'living room', 'den', 'None');
insert into acnh_misc values(868, 0, 'thank-you Mom mug', 'unorderable', '150', 'Nook Shopping Seasonal', 'living room', 'fancy', 'None');
insert into acnh_misc values(869, 0, 'wedding cake (Cute)', 'unorderable', '1000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(870, 0, 'wedding cake (Chic)', 'unorderable', '1000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(871, 0, 'wedding cake (Garden)', 'unorderable', '1000', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(872, 0, 'wedding candle set (Cute)', 'unorderable', '300', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(873, 0, 'wedding candle set (Chic)', 'unorderable', '300', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_misc values(874, 0, 'wedding candle set (Garden)', 'unorderable', '300', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wall_mounted values(313, 0, 'bug plaque', 'unorderable', '300', 'International Museum Day', 'expensive', 'den', 'None');
insert into acnh_wall_mounted values(314, 0, 'fish plaque', 'unorderable', '300', 'International Museum Day', 'expensive', 'den', 'None');
insert into acnh_wall_mounted values(315, 0, 'fossil plaque', 'unorderable', '300', 'International Museum Day', 'expensive', 'den', 'None');
insert into acnh_wall_mounted values(316, 0, 'mermaid wall clock', 'unorderable', '12290', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_wall_mounted values(317, 0, 'wedding decoration (Cute)', 'unorderable', '250', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wall_mounted values(318, 0, 'wedding decoration (Chic)', 'unorderable', '250', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wall_mounted values(319, 0, 'wedding decoration (Garden)', 'unorderable', '250', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wall_mounted values(320, 0, 'world map (Pacific Ocean)', 'orderable', '640', 'Nintendo; Nook Shopping', 'child''s room', 'den', 'None');
insert into acnh_wall_mounted values(321, 0, 'world map (Atlantic Ocean)', 'orderable', '640', 'Nintendo; Nook Shopping', 'child''s room', 'den', 'None');
insert into acnh_wallpaper values(244, 0, 'brown wedding wall', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wallpaper values(245, 0, 'green wedding wall', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wallpaper values(246, 0, 'mermaid wall', 'unorderable', '23520', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_wallpaper values(247, 0, 'pirate wall', 'unorderable', '750', 'Gullivarrr', 'ocean', 'none', 'pirate');
insert into acnh_wallpaper values(248, 0, 'wedding-party wall', 'unorderable', '437', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_wallpaper values(249, 0, 'white wedding wall', 'unorderable', '750', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_rug values(129, 0, 'Bell-bag rug', 'unorderable', '6000', 'Nintendo; Nook Miles Shop', 'expensive', 'None', 'None');
insert into acnh_rug values(130, 0, 'blue wedding rug', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_rug values(131, 0, 'mermaid rug', 'unorderable', '10360', 'Crafting', 'ocean', 'fancy', 'mermaid');
insert into acnh_rug values(132, 0, 'pirate rug', 'unorderable', '375', 'Gullivarrr', 'ocean', 'none', 'pirate');
insert into acnh_rug values(133, 0, 'red wedding rug', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_rug values(134, 0, 'white wedding rug', 'unorderable', '375', 'Cyrus', 'party', 'expensive', 'wedding');
insert into acnh_recipe values(594, 0, 'hedge', '10 clump of weeds, 5 tree branch, 2 stone', 'Tom Nook');
insert into acnh_recipe values(595, 0, 'mermaid bed', '2 pearl, 2 giant clam, 5 sand dollar', 'Pascal');
insert into acnh_recipe values(596, 0, 'mermaid chair', '1 pearl, 1 giant clam, 2 sand dollar', 'Pascal');
insert into acnh_recipe values(597, 0, 'mermaid closet', '2 pearl, 1 giant clam, 2 coral, 5 sand dollar', 'Pascal');
insert into acnh_recipe values(598, 0, 'mermaid dresser', '2 pearl, 1 giant clam, 3 coral', 'Pascal');
insert into acnh_recipe values(599, 0, 'mermaid flooring', '2 pearl, 5 sand dollar, 5 Stone', 'Pascal');
insert into acnh_recipe values(600, 0, 'mermaid lamp', '1 pearl, 3 conch, 2 coral, 2 iron nugget', 'Pascal');
insert into acnh_recipe values(601, 0, 'mermaid rug', '1 pearl, 3 sand dollar', 'Pascal');
insert into acnh_recipe values(602, 0, 'mermaid screen', '2 pearl, 3 giant clam, 5 sand dollar', 'Pascal');
insert into acnh_recipe values(603, 0, 'mermaid shelf', '1 pearl, 1 giant clam, 4 coral', 'Pascal');
insert into acnh_recipe values(604, 0, 'mermaid sofa', '1 pearl, 10 sand dollar', 'Pascal');
insert into acnh_recipe values(605, 0, 'mermaid table', '1 pearl, 4 sand dollar', 'Pascal');
insert into acnh_recipe values(606, 0, 'mermaid vanity', '1 pearl, 1 giant clam, 2 coral, 2 iron nugget', 'Pascal');
insert into acnh_recipe values(607, 0, 'mermaid wall', '2 pearl, 2 sea snail, 2 sand dollar, 2 coral, 2 giant clam, 2 cowrie', 'Pascal');
insert into acnh_recipe values(608, 0, 'mermaid wall clock', '1 pearl, 3 sea snail, 2 coral, 2 iron nugget', 'Pascal');
insert into acnh_recipe values(609, 0, 'wedding fence', '5 iron nugget, 3 softwood', 'Harvey');
insert into acnh_recipe values(610, 0, 'wedding wand', '1 wedding flower stand, 3 star fragment', 'Cyrus');
drop table if exists acnh_tool;
create table acnh_tool ("Index" int, Selected int, Name varchar(255), "From" varchar(63));
insert into acnh_tool values(1, 0, 'axe', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(2, 0, 'bamboo wand', 'Crafting');
insert into acnh_tool values(3, 0, 'bug wand', 'Bug-Off');
insert into acnh_tool values(4, 0, 'Bunny Day wand', 'Crafting');
insert into acnh_tool values(5, 0, 'cherry-blossom wand', 'Crafting');
insert into acnh_tool values(6, 0, 'colorful fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(7, 0, 'colorful net', 'Nook''s Cranny');
insert into acnh_tool values(8, 0, 'colorful shovel', 'Nook''s Cranny');
insert into acnh_tool values(9, 0, 'colorful slingshot', 'Nook''s Cranny');
insert into acnh_tool values(10, 0, 'colorful watering can', 'Nook''s Cranny');
insert into acnh_tool values(11, 0, 'cosmos wand', 'Crafting');
insert into acnh_tool values(12, 0, 'elephant watering can', 'Nook''s Cranny');
insert into acnh_tool values(13, 0, 'fish fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(14, 0, 'fish wand', 'Fishing Tourney');
insert into acnh_tool values(15, 0, 'fishing rod', 'Crafting');
insert into acnh_tool values(16, 0, 'flimsy axe', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(17, 0, 'flimsy fishing rod', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(18, 0, 'flimsy net', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(19, 0, 'flimsy shovel', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(20, 0, 'flimsy watering can', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(21, 0, 'golden axe', 'Crafting');
insert into acnh_tool values(22, 0, 'golden net', 'Crafting');
insert into acnh_tool values(23, 0, 'golden rod', 'Crafting');
insert into acnh_tool values(24, 0, 'golden shovel', 'Crafting');
insert into acnh_tool values(25, 0, 'golden slingshot', 'Crafting');
insert into acnh_tool values(26, 0, 'golden wand', 'Crafting');
insert into acnh_tool values(27, 0, 'golden watering can', 'Crafting');
insert into acnh_tool values(28, 0, 'hyacinth wand', 'Crafting');
insert into acnh_tool values(29, 0, 'ice wand', 'Crafting');
insert into acnh_tool values(30, 0, 'iron wand', 'Crafting');
insert into acnh_tool values(31, 0, 'ladder', 'Crafting');
insert into acnh_tool values(32, 0, 'light stick', 'Crafting');
insert into acnh_tool values(33, 0, 'lily wand', 'Crafting');
insert into acnh_tool values(34, 0, 'mums wand', 'Crafting');
insert into acnh_tool values(35, 0, 'mushroom wand', 'Crafting');
insert into acnh_tool values(36, 0, 'net', 'Crafting');
insert into acnh_tool values(37, 0, 'Nook Inc. uchiwa fan', 'Nook Miles Shop');
insert into acnh_tool values(38, 0, 'ocarina', 'Crafting');
insert into acnh_tool values(39, 0, 'outdoorsy fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(40, 0, 'outdoorsy net', 'Nook''s Cranny');
insert into acnh_tool values(41, 0, 'outdoorsy shovel', 'Nook''s Cranny');
insert into acnh_tool values(42, 0, 'outdoorsy slingshot', 'Nook''s Cranny');
insert into acnh_tool values(43, 0, 'outdoorsy watering can', 'Nook''s Cranny');
insert into acnh_tool values(44, 0, 'pan flute', 'Crafting');
insert into acnh_tool values(45, 0, 'pansy wand', 'Crafting');
insert into acnh_tool values(46, 0, 'party popper', 'Nook''s Cranny');
insert into acnh_tool values(47, 0, 'printed-design shovel', 'Nook''s Cranny');
insert into acnh_tool values(48, 0, 'rose wand', 'Crafting');
insert into acnh_tool values(49, 0, 'shell wand', 'Crafting');
insert into acnh_tool values(50, 0, 'shovel', 'Crafting');
insert into acnh_tool values(51, 0, 'slingshot', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(52, 0, 'star net', 'Nook''s Cranny');
insert into acnh_tool values(53, 0, 'star wand', 'Crafting');
insert into acnh_tool values(54, 0, 'stone axe', 'Crafting');
insert into acnh_tool values(55, 0, 'tambourine', 'Nook''s Cranny');
insert into acnh_tool values(56, 0, 'timer', 'Nook''s Cranny');
insert into acnh_tool values(57, 0, 'tree-branch wand', 'Crafting');
insert into acnh_tool values(58, 0, 'tulip wand', 'Crafting');
insert into acnh_tool values(59, 0, 'vaulting pole', 'Crafting');
insert into acnh_tool values(60, 0, 'wand', 'Crafting');
insert into acnh_tool values(61, 0, 'watering can', 'Crafting');
insert into acnh_tool values(62, 0, 'windflower wand', 'Crafting');
insert into acnh_tool values(63, 0, 'wedding wand', 'Crafting');
insert into acnh_tool values(64, 0, 'worn axe', 'May Day Tour');