insert into acnl_wallpaper values(75, 0, 'Mushroom Mural (#1)', 'unorderable', 'Fortune Cookie');
insert into acnl_carpet values(11, 0, 'Block Floor (#2)', 'unorderable', 'Fortune Cookie');
insert into acnl_shirt values(216, 0, 'Hero''s Clothes (#3)', 'unorderable', 'Fortune Cookie', 'green', 'green');
insert into acnl_bottom values(61, 0, 'Hero''s Pants (#5)', 'unorderable', 'Fortune Cookie', 'white', 'white');
insert into acnl_tool values(27, 0, 'Peach''s Parasol (#7)', 'Fortune Cookie');
insert into acnl_hat values(83, 0, 'Hero''s Cap (#8)', 'unorderable', 'Fortune Cookie', 'green', 'green');
insert into acnl_hat values(99, 0, 'Majora''s Mask (#9)', 'unorderable', 'Fortune Cookie', 'colorful', 'colorful');
insert into acnl_hat values(156, 0, 'Samus Mask (#10)', 'unorderable', 'Fortune Cookie', 'orange', 'orange');
insert into acnl_hat values(105, 0, 'Midna''s Mask (#11)', 'unorderable', 'Fortune Cookie', 'gray', 'gray');
insert into acnl_hat values(183, 0, 'Toad Hat (#12)', 'unorderable', 'Fortune Cookie', 'red', 'white');
insert into acnl_hat values(141, 0, 'Red Pikmin (#13)', 'unorderable', 'Fortune Cookie', 'green', 'red');
insert into acnl_hat values(23, 0, 'Blue Pikmin (#14)', 'unorderable', 'Fortune Cookie', 'blue', 'white');
insert into acnl_hat values(201, 0, 'Yellow Pikmin (#15)', 'unorderable', 'Fortune Cookie', 'yellow', 'white');
insert into acnl_furniture values(97, 0, 'Block (#17)', 'unorderable', 'Fortune Cookie', 'brown', 'brown');
insert into acnl_furniture values(227, 0, 'Coin (#18)', 'unorderable', 'Fortune Cookie', 'yellow', 'yellow');
insert into acnl_furniture values(395, 0, 'Goal Pole (#19)', 'unorderable', 'Fortune Cookie', 'brown', 'white');
insert into acnl_furniture values(354, 0, 'Fire Flower (#20)', 'unorderable', 'Fortune Cookie', 'colorful', 'white');
insert into acnl_furniture values(1070, 0, 'Super Mushroom (#21)', 'unorderable', 'Fortune Cookie', 'red', 'orange');
insert into acnl_furniture values(446, 0, 'Green Shell (#22)', 'unorderable', 'Fortune Cookie', 'green', 'green');
insert into acnl_furniture values(1071, 0, 'Super Star (#23)', 'unorderable', 'Fortune Cookie', 'yellow', 'yellow');
insert into acnl_furniture values(2, 0, '1-Up Mushroom (#24)', 'unorderable', 'Fortune Cookie', 'green', 'orange');
insert into acnl_furniture values(1, 0, '? Block (#25)', 'unorderable', 'Fortune Cookie', 'orange', 'brown');
insert into acnl_furniture values(781, 0, 'Pipe (#26)', 'unorderable', 'Fortune Cookie', 'green', 'green');
insert into acnl_furniture values(353, 0, 'Fire Bar (#27)', 'unorderable', 'Fortune Cookie', 'red', 'brown');
insert into acnl_furniture values(83, 0, 'Bill Blaster (#28)', 'unorderable', 'Fortune Cookie', 'black', 'black');
insert into acnl_furniture values(1200, 0, 'Yoshi''s Egg (#29)', 'unorderable', 'Fortune Cookie', 'green', 'white');
insert into acnl_furniture values(1131, 0, 'Triple Red Shells (#31)', 'unorderable', 'Fortune Cookie', 'red', 'red');
insert into acnl_furniture values(533, 0, 'Kart (#32)', 'unorderable', 'Fortune Cookie', 'red', 'black');
insert into acnl_furniture values(774, 0, 'Pikmin (#33)', 'unorderable', 'Fortune Cookie', 'colorful', 'brown');
insert into acnl_furniture values(109, 0, 'Blue Falcon (#34)', 'unorderable', 'Fortune Cookie', 'blue', 'blue');
insert into acnl_furniture values(620, 0, 'Master Sword (#35)', 'unorderable', 'Fortune Cookie', 'blue', 'gray');
insert into acnl_furniture values(27, 0, 'Arwing (#36)', 'unorderable', 'Fortune Cookie', 'blue', 'gray');
insert into acnl_furniture values(1129, 0, 'Triforce (#37)', 'unorderable', 'Fortune Cookie', 'yellow', 'yellow');
insert into acnl_furniture values(907, 0, 'S.S. Dolphin (#39)', 'unorderable', 'Fortune Cookie', 'white', 'white');
insert into acnl_furniture values(1161, 0, 'Virtual Boy (#40)', 'unorderable', 'Fortune Cookie', 'red', 'black');
insert into acnl_furniture values(1192, 0, 'Wii Balance Board (#41)', 'unorderable', 'Fortune Cookie', 'white', 'white');
insert into acnl_bottom values(115, 0, 'Varia Suit Pants (#42)', 'unorderable', 'Fortune Cookie', 'orange', 'orange');
insert into acnl_feet values(86, 0, 'Varia Suit Shoes (#43)', 'unorderable', 'Fortune Cookie', 'orange', 'orange');
insert into acnl_accessory values(3, 0, 'Bad Bro''s Stache (#44)', 'unorderable', 'Fortune Cookie', 'red', 'black');
insert into acnl_accessory values(7, 0, 'Big Bro''s Mustache (#45)', 'unorderable', 'Fortune Cookie', 'brown', 'brown');
insert into acnl_shirt values(424, 0, 'Varia Suit (#46)', 'unorderable', 'Fortune Cookie', 'orange', 'orange');
insert into acnl_furniture values(639, 0, 'Metroid (#47)', 'unorderable', 'Fortune Cookie', 'blue', 'gray');
insert into acnl_furniture values(1130, 0, 'Triple Bananas (#48)', 'unorderable', 'Fortune Cookie', 'yellow', 'yellow');
insert into acnl_feet values(47, 0, 'Hero''s Boots (#49)', 'unorderable', 'Fortune Cookie', 'brown', 'brown');
insert into acnl_hat values(57, 0, 'Fi Mask (#50)', 'unorderable', 'Fortune Cookie', 'aqua', 'aqua');
insert into acnl_furniture values(1685, 0, 'Wii U console (#51 white and #52 black)', 'unorderable', '(Welcome Amiibo) Celeste''s RV, Cyrus'' RV, Digby''s RV, Hopkins'' RV, Isabelle''s RV, K.K''s RV, Kapp''n''s RV, Kicks'' RV, Lottie''s RV, Mabel''s RV, Reese''s RV, Resetti''s RV, Rover''s RV, Timmy & Tommy''s RV, Tom Nook''s RV, Villager''s RV, Fortune cookie #51, Fortune cookie #52', 'unknown', 'unknown');
insert into acnl_furniture values(1276, 0, 'Chihuahua ornament (#53)', 'unorderable', '(Welcome Amiibo) Fortune cookie #53', 'unknown', 'unknown');
insert into acnl_furniture values(1303, 0, 'Dalmatian ornament (#54)', 'unorderable', '(Welcome Amiibo) Fortune cookie #54', 'unknown', 'unknown');
insert into acnl_furniture values(1301, 0, 'Dachshund ornament (#55)', 'unorderable', '(Welcome Amiibo) Fortune cookie #55', 'unknown', 'unknown');
insert into acnl_furniture values(1440, 0, 'Labrador ornament (#56)', 'unorderable', '(Welcome Amiibo) Fortune cookie #56', 'unknown', 'unknown');
insert into acnl_furniture values(1504, 0, 'New Nintendo 3DS (#57)', 'unorderable', '(Welcome Amiibo) Blathers'' RV, Celeste''s RV, Cyrus'' RV, Digby''s RV, Kapp''n''s RV, Kicks'' RV, Reese''s RV, Resetti''s RV, Rover''s RV, Tom Nook''s RV, Fortune cookie #57', 'unknown', 'unknown');
