drop table if exists acgc_furniture;
create table acgc_furniture ("Index" int, Selected int, Name varchar(255), Price varchar(15), "From" varchar(63), Series varchar(63), Color varchar(31));
insert into acgc_furniture values(1, 0, 'blue bed', '2100', 'Redd''s', 'Blue Series', 'none');
insert into acgc_furniture values(2, 0, 'blue bench', '1900', 'Tom Nook''s Shop (Group A)', 'Blue Series', 'none');
insert into acgc_furniture values(3, 0, 'blue bookcase', '1900', 'Tom Nook''s Shop (Group B)', 'Blue Series', 'none');
insert into acgc_furniture values(4, 0, 'blue bureau', '2160', 'Tom Nook''s Shop (Group B)', 'Blue Series', 'none');
insert into acgc_furniture values(5, 0, 'blue cabinet', '2400', 'Tom Nook''s Shop (Group A)', 'Blue Series', 'none');
insert into acgc_furniture values(6, 0, 'blue chair', '1200', 'Tom Nook''s Shop (Group C)', 'Blue Series', 'none');
insert into acgc_furniture values(7, 0, 'blue clock', '1600', 'Tom Nook''s Shop (Group C)', 'Blue Series', 'none');
insert into acgc_furniture values(8, 0, 'blue dresser', '2100', 'Tom Nook''s Lottery', 'Blue Series', 'Red');
insert into acgc_furniture values(9, 0, 'blue table', '1800', 'Redd''s', 'Blue Series', 'Yellow');
insert into acgc_furniture values(10, 0, 'blue wardrobe', '1920', 'Tom Nook''s Shop (Group A)', 'Blue Series', 'none');
insert into acgc_furniture values(11, 0, 'cabana armchair', '1800', 'Tom Nook''s Lottery', 'Cabana Series', 'none');
insert into acgc_furniture values(12, 0, 'cabana bed', '2200', 'Redd''s', 'Cabana Series', 'none');
insert into acgc_furniture values(13, 0, 'cabana bookcase', '2400', 'Tom Nook''s Shop (Group B)', 'Cabana Series', 'none');
insert into acgc_furniture values(14, 0, 'cabana chair', '1600', 'Redd''s', 'Cabana Series', 'none');
insert into acgc_furniture values(15, 0, 'cabana dresser', '2400', 'Tom Nook''s Shop (Group A)', 'Cabana Series', 'none');
insert into acgc_furniture values(16, 0, 'cabana lamp', '1700', 'Tom Nook''s Shop (Group B)', 'Cabana Series', 'none');
insert into acgc_furniture values(17, 0, 'cabana screen', '2000', 'Tom Nook''s Shop (Group C)', 'Cabana Series', 'none');
insert into acgc_furniture values(18, 0, 'cabana table', '1800', 'Tom Nook''s Shop (Group C)', 'Cabana Series', 'none');
insert into acgc_furniture values(19, 0, 'cabana vanity', '1800', 'Tom Nook''s Shop (Group A)', 'Cabana Series', 'none');
insert into acgc_furniture values(20, 0, 'cabana wardrobe', '2240', 'Tom Nook''s Shop (Group B)', 'Cabana Series', 'none');
insert into acgc_furniture values(21, 0, 'cabin armchair', '2280', 'Tom Nook''s Shop (Group B)', 'Cabin Series', 'none');
insert into acgc_furniture values(22, 0, 'cabin bed', '2400', 'Tom Nook''s Shop (Group A)', 'Cabin Series', 'Red');
insert into acgc_furniture values(23, 0, 'cabin bookcase', '2300', 'Tom Nook''s Lottery', 'Cabin Series', 'none');
insert into acgc_furniture values(24, 0, 'cabin chair', '1700', 'Redd''s', 'Cabin Series', 'none');
insert into acgc_furniture values(25, 0, 'cabin clock', '2000', 'Tom Nook''s Shop (Group C)', 'Cabin Series', 'none');
insert into acgc_furniture values(26, 0, 'cabin couch', '2480', 'Tom Nook''s Shop (Group C)', 'Cabin Series', 'none');
insert into acgc_furniture values(27, 0, 'cabin dresser', '2160', 'Redd''s', 'Cabin Series', 'none');
insert into acgc_furniture values(28, 0, 'cabin low table', '2100', 'Tom Nook''s Shop (Group A)', 'Cabin Series', 'none');
insert into acgc_furniture values(29, 0, 'cabin table', '2100', 'Tom Nook''s Shop (Group B)', 'Cabin Series', 'Red');
insert into acgc_furniture values(30, 0, 'cabin wardrobe', '2480', 'Tom Nook''s Shop (Group C)', 'Cabin Series', 'none');
insert into acgc_furniture values(31, 0, 'classic bed', '2520', 'Tom Nook''s Shop (Group B)', 'Classic Series', 'none');
insert into acgc_furniture values(32, 0, 'classic cabinet', '2560', 'Tom Nook''s Shop (Group B)', 'Classic Series', 'none');
insert into acgc_furniture values(33, 0, 'classic chair', '1800', 'Tom Nook''s Shop (Group C)', 'Classic Series', 'none');
insert into acgc_furniture values(34, 0, 'classic clock', '2180', 'Tom Nook''s Shop (Group C)', 'Classic Series', 'none');
insert into acgc_furniture values(35, 0, 'classic desk', '2200', 'Tom Nook''s Shop (Group A)', 'Classic Series', 'none');
insert into acgc_furniture values(36, 0, 'classic hutch', '3360', 'Tom Nook''s Lottery', 'Classic Series', 'none');
insert into acgc_furniture values(37, 0, 'classic sofa', '2240', 'Tom Nook''s Shop (Group C)', 'Classic Series', 'Yellow');
insert into acgc_furniture values(38, 0, 'classic table', '1600', 'Tom Nook''s Shop (Group A)', 'Classic Series', 'none');
insert into acgc_furniture values(39, 0, 'classic vanity', '2560', 'Redd''s', 'Classic Series', 'none');
insert into acgc_furniture values(40, 0, 'classic wardrobe', '2560', 'Redd''s', 'Classic Series', 'none');
insert into acgc_furniture values(41, 0, 'exotic bed', '2540', 'Redd''s', 'Exotic Series', 'none');
insert into acgc_furniture values(42, 0, 'exotic bench', '1900', 'Tom Nook''s Shop (Group A)', 'Exotic Series', 'none');
insert into acgc_furniture values(43, 0, 'exotic bureau', '2400', 'Tom Nook''s Shop (Group A)', 'Exotic Series', 'none');
insert into acgc_furniture values(44, 0, 'exotic chair', '1400', 'Tom Nook''s Shop (Group A)', 'Exotic Series', 'none');
insert into acgc_furniture values(45, 0, 'exotic chest', '1800', 'Tom Nook''s Shop (Group B)', 'Exotic Series', 'none');
insert into acgc_furniture values(46, 0, 'exotic end table', '1600', 'Tom Nook''s Shop (Group B)', 'Exotic Series', 'none');
insert into acgc_furniture values(47, 0, 'exotic lamp', '1800', 'Tom Nook''s Lottery', 'Exotic Series', 'Yellow');
insert into acgc_furniture values(48, 0, 'exotic screen', '2250', 'Tom Nook''s Shop (Group C)', 'Exotic Series', 'none');
insert into acgc_furniture values(49, 0, 'exotic table', '2300', 'Redd''s', 'Exotic Series', 'none');
insert into acgc_furniture values(50, 0, 'exotic wardrobe', '2180', 'Tom Nook''s Shop (Group C)', 'Exotic Series', 'none');
insert into acgc_furniture values(51, 0, 'green bed', '2160', 'Tom Nook''s Shop (Group B)', 'Green Series', 'Green');
insert into acgc_furniture values(52, 0, 'green bench', '1800', 'Tom Nook''s Shop (Group A)', 'Green Series', 'Green');
insert into acgc_furniture values(53, 0, 'green chair', '1200', 'Tom Nook''s Shop (Group C)', 'Green Series', 'Green');
insert into acgc_furniture values(54, 0, 'green counter', '2400', 'Tom Nook''s Shop (Group B)', 'Green Series', 'Green');
insert into acgc_furniture values(55, 0, 'green desk', '2000', 'Tom Nook''s Shop (Group C)', 'Green Series', 'Green');
insert into acgc_furniture values(56, 0, 'green dresser', '2320', 'Redd''s', 'Green Series', 'Green');
insert into acgc_furniture values(57, 0, 'green lamp', '1800', 'Tom Nook''s Shop (Group C)', 'Green Series', 'Green');
insert into acgc_furniture values(58, 0, 'green pantry', '2290', 'Tom Nook''s Lottery', 'Green Series', 'Green');
insert into acgc_furniture values(59, 0, 'green table', '1700', 'Tom Nook''s Shop (Group C)', 'Green Series', 'Green');
insert into acgc_furniture values(60, 0, 'green wardrobe', '2300', 'Redd''s', 'Green Series', 'Green');
insert into acgc_furniture values(61, 0, 'kiddie bed', '2100', 'Redd''s', 'Kiddie Series', 'none');
insert into acgc_furniture values(62, 0, 'kiddie bookcase', '1800', 'Tom Nook''s Shop', 'Kiddie Series', 'none');
insert into acgc_furniture values(63, 0, 'kiddie bureau', '2200', 'Tom Nook''s Shop (Group B)', 'Kiddie Series', 'none');
insert into acgc_furniture values(64, 0, 'kiddie chair', '1400', 'Tom Nook''s Shop (Group B)', 'Kiddie Series', 'none');
insert into acgc_furniture values(65, 0, 'kiddie clock', '1480', 'Redd''s', 'Kiddie Series', 'none');
insert into acgc_furniture values(66, 0, 'kiddie couch', '2200', 'Tom Nook''s Shop (Group B)', 'Kiddie Series', 'none');
insert into acgc_furniture values(67, 0, 'kiddie dresser', '2150', 'Tom Nook''s Shop (Group C)', 'Kiddie Series', 'none');
insert into acgc_furniture values(68, 0, 'kiddie stereo', '1900', 'Tom Nook''s Lottery', 'Kiddie Series', 'none');
insert into acgc_furniture values(69, 0, 'kiddie table', '2200', 'Tom Nook''s Shop (Group A)', 'Kiddie Series', 'none');
insert into acgc_furniture values(70, 0, 'kiddie wardrobe', '2180', 'Tom Nook''s Shop (Group C)', 'Kiddie Series', 'none');
insert into acgc_furniture values(71, 0, 'lovely armchair', '2000', 'Tom Nook''s Shop (Group A)', 'Lovely Series', 'none');
insert into acgc_furniture values(72, 0, 'lovely armoire', '2240', 'Redd''s', 'Lovely Series', 'none');
insert into acgc_furniture values(73, 0, 'lovely bed', '2000', 'Tom Nook''s Shop (Group A)', 'Lovely Series', 'none');
insert into acgc_furniture values(74, 0, 'lovely chair', '1600', 'Tom Nook''s Shop (Group B)', 'Lovely Series', 'none');
insert into acgc_furniture values(75, 0, 'lovely dresser', '2160', 'Tom Nook''s Shop (Group C)', 'Lovely Series', 'Red');
insert into acgc_furniture values(76, 0, 'lovely end table', '1800', 'Redd''s', 'Lovely Series', 'none');
insert into acgc_furniture values(77, 0, 'lovely kitchen', '2280', 'Tom Nook''s Lottery', 'Lovely Series', 'none');
insert into acgc_furniture values(78, 0, 'lovely lamp', '1600', 'Tom Nook''s Shop (Group B)', 'Lovely Series', 'Red');
insert into acgc_furniture values(79, 0, 'lovely table', '1800', 'Tom Nook''s Shop (Group C)', 'Lovely Series', 'none');
insert into acgc_furniture values(80, 0, 'lovely vanity', '2200', 'Tom Nook''s Shop (Group B)', 'Lovely Series', 'none');
insert into acgc_furniture values(81, 0, 'modern bed', '2320', 'Tom Nook''s Shop (Group C)', 'Modern Series', 'none');
insert into acgc_furniture values(82, 0, 'modern cabinet', '2580', 'Tom Nook''s Lottery', 'Modern Series', 'none');
insert into acgc_furniture values(83, 0, 'modern chair', '1500', 'Tom Nook''s Shop (Group B)', 'Modern Series', 'none');
insert into acgc_furniture values(84, 0, 'modern desk', '2480', 'Tom Nook''s Shop (Group B)', 'Modern Series', 'none');
insert into acgc_furniture values(85, 0, 'modern dresser', '2250', 'Tom Nook''s Shop (Group A)', 'Modern Series', 'none');
insert into acgc_furniture values(86, 0, 'modern end table', '1900', 'Redd''s', 'Modern Series', 'none');
insert into acgc_furniture values(87, 0, 'modern lamp', '1400', 'Tom Nook''s Shop (Group B)', 'Modern Series', 'none');
insert into acgc_furniture values(88, 0, 'modern sofa', '2620', 'Tom Nook''s Shop (Group C)', 'Modern Series', 'none');
insert into acgc_furniture values(89, 0, 'modern table', '1800', 'Tom Nook''s Shop (Group A)', 'Modern Series', 'none');
insert into acgc_furniture values(90, 0, 'modern wardrobe', '2560', 'Redd''s', 'Modern Series', 'none');
insert into acgc_furniture values(91, 0, 'ranch armchair', '2000', 'Tom Nook''s Shop (Group A)', 'Ranch Series', 'Green');
insert into acgc_furniture values(92, 0, 'ranch bed', '2300', 'Tom Nook''s Shop (Group C)', 'Ranch Series', 'Red');
insert into acgc_furniture values(93, 0, 'ranch bookcase', '2000', 'Tom Nook''s Shop (Group C)', 'Ranch Series', 'none');
insert into acgc_furniture values(94, 0, 'ranch chair', '1400', 'Redd''s', 'Ranch Series', 'none');
insert into acgc_furniture values(95, 0, 'ranch couch', '2400', 'Tom Nook''s Shop (Group C)', 'Ranch Series', 'Green');
insert into acgc_furniture values(96, 0, 'ranch dresser', '2720', 'Redd''s', 'Ranch Series', 'none');
insert into acgc_furniture values(97, 0, 'ranch hutch', '2560', 'Tom Nook''s Lottery', 'Ranch Series', 'none');
insert into acgc_furniture values(98, 0, 'ranch table', '1700', 'Tom Nook''s Shop (Group B)', 'Ranch Series', 'none');
insert into acgc_furniture values(99, 0, 'ranch tea table', '1800', 'Tom Nook''s Shop (Group B)', 'Ranch Series', 'none');
insert into acgc_furniture values(100, 0, 'ranch wardrobe', '3050', 'Tom Nook''s Shop (Group A)', 'Ranch Series', 'none');
insert into acgc_furniture values(101, 0, 'regal armoire', '3820', 'Tom Nook''s Shop (Group B)', 'Regal Series', 'none');
insert into acgc_furniture values(102, 0, 'regal bed', '3120', 'Redd''s', 'Regal Series', 'none');
insert into acgc_furniture values(103, 0, 'regal bookcase', '3120', 'Tom Nook''s Shop (Group C)', 'Regal Series', 'none');
insert into acgc_furniture values(104, 0, 'regal chair', '2100', 'Redd''s', 'Regal Series', 'none');
insert into acgc_furniture values(105, 0, 'regal cupboard', '3360', 'Tom Nook''s Lottery', 'Regal Series', 'none');
insert into acgc_furniture values(106, 0, 'regal dresser', '3520', 'Tom Nook''s Shop (Group C)', 'Regal Series', 'none');
insert into acgc_furniture values(107, 0, 'regal lamp', '2400', 'Tom Nook''s Shop (Group A)', 'Regal Series', 'none');
insert into acgc_furniture values(108, 0, 'regal sofa', '3100', 'Tom Nook''s Shop (Group A)', 'Regal Series', 'none');
insert into acgc_furniture values(109, 0, 'regal table', '2540', 'Tom Nook''s Shop (Group A)', 'Regal Series', 'none');
insert into acgc_furniture values(110, 0, 'regal vanity', '3200', 'Tom Nook''s Shop (Group B)', 'Regal Series', 'none');
insert into acgc_furniture values(111, 0, 'harvest bed', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(112, 0, 'harvest bureau', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(113, 0, 'harvest chair', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(114, 0, 'harvest clock', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(115, 0, 'harvest dresser', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(116, 0, 'harvest lamp', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(117, 0, 'harvest mirror', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(118, 0, 'harvest sofa', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(119, 0, 'harvest table', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(120, 0, 'harvest TV', 'Not for Sale', 'Franklin', 'Harvest Series', 'none');
insert into acgc_furniture values(121, 0, 'Jingle bed', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(122, 0, 'Jingle chair', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(123, 0, 'Jingle clock', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(124, 0, 'Jingle dresser', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(125, 0, 'Jingle lamp', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(126, 0, 'Jingle piano', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(127, 0, 'Jingle shelves', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(128, 0, 'Jingle sofa', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(129, 0, 'Jingle table', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(130, 0, 'Jingle wardrobe', 'Not for Sale', 'Jingle', 'Jingle Series', 'Red');
insert into acgc_furniture values(131, 0, 'Snowman bed', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(132, 0, 'Snowman chair', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(133, 0, 'Snowman clock', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(134, 0, 'Snowman dresser', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(135, 0, 'Snowman fridge', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(136, 0, 'Snowman lamp', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(137, 0, 'Snowman sofa', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(138, 0, 'Snowman table', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(139, 0, 'Snowman TV', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(140, 0, 'Snowman wardrobe', 'Not for Sale', 'Snowman', 'Snowman Series', 'none');
insert into acgc_furniture values(141, 0, 'spooky bed', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(142, 0, 'spooky bookcase', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(143, 0, 'spooky chair', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(144, 0, 'spooky clock', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(145, 0, 'spooky dresser', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(146, 0, 'spooky lamp', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(147, 0, 'spooky sofa', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(148, 0, 'spooky table', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(149, 0, 'spooky vanity', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(150, 0, 'spooky wardrobe', 'Not for Sale', 'Jack', 'Spooky Series', 'Orange');
insert into acgc_furniture values(151, 0, 'jack-in-the-box', 'Not for Sale', 'Special Event', 'Holiday Items', 'none');
insert into acgc_furniture values(152, 0, 'jack-o''-lantern', 'Not for Sale', 'Special Event', 'Holiday Items', 'Orange');
insert into acgc_furniture values(153, 0, 'backyard pool', '990', 'Redd''s', 'Backyard Theme', 'none');
insert into acgc_furniture values(154, 0, 'barbecue', '1760', 'Tom Nook''s Shop (Group B)', 'Backyard Theme', 'Red');
insert into acgc_furniture values(155, 0, 'bird bath', '1450', 'Tom Nook''s Shop (Group A)', 'Backyard Theme', 'Green');
insert into acgc_furniture values(156, 0, 'bird feeder', '1260', 'Tom Nook''s Shop (Group C)', 'Backyard Theme', 'none');
insert into acgc_furniture values(157, 0, 'birdhouse', '1620', 'Tom Nook''s Shop (Group B)', 'Backyard Theme', 'none');
insert into acgc_furniture values(158, 0, 'bug zapper', '1200', 'Tom Nook''s Shop (Group A)', 'Backyard Theme', 'none');
insert into acgc_furniture values(159, 0, 'garden gnome', '3380', 'Tom Nook''s Lottery', 'Backyard Theme', 'none');
insert into acgc_furniture values(160, 0, 'hammock', '1320', 'Tom Nook''s Shop (Group C)', 'Backyard Theme', 'none');
insert into acgc_furniture values(161, 0, 'lawn chair', '1180', 'Tom Nook''s Shop (Group A)', 'Backyard Theme', 'none');
insert into acgc_furniture values(162, 0, 'lawn mower', '2760', 'Redd''s', 'Backyard Theme', 'Red');
insert into acgc_furniture values(163, 0, 'Mr. Flamingo', '1530', 'Tom Nook''s Shop (Group A)', 'Backyard Theme', 'none');
insert into acgc_furniture values(164, 0, 'Mrs. Flamingo', '1530', 'Tom Nook''s Shop (Group A)', 'Backyard Theme', 'none');
insert into acgc_furniture values(165, 0, 'picnic table', '1390', 'Tom Nook''s Shop (Group C)', 'Backyard Theme', 'none');
insert into acgc_furniture values(166, 0, 'sprinkler', '1640', 'Tom Nook''s Shop (Group C)', 'Backyard Theme', 'Yellow');
insert into acgc_furniture values(167, 0, 'tiki torch', '870', 'Tom Nook''s Shop (Group B)', 'Backyard Theme', 'none');
insert into acgc_furniture values(168, 0, 'blue corner', '6800', 'Tom Nook''s Lottery', 'Boxing Theme', 'none');
insert into acgc_furniture values(169, 0, 'boxing barricade', '1050', 'Tom Nook''s Shop (Group C)', 'Boxing Theme', 'none');
insert into acgc_furniture values(170, 0, 'boxing mat', '1180', 'Tom Nook''s Shop (Group C)', 'Boxing Theme', 'none');
insert into acgc_furniture values(171, 0, 'judge''s bell', '1790', 'Redd''s', 'Boxing Theme', 'none');
insert into acgc_furniture values(172, 0, 'neutral corner', '5500', 'Tom Nook''s Shop (Group A)', 'Boxing Theme', 'none');
insert into acgc_furniture values(173, 0, 'red corner', '6800', 'Redd''s', 'Boxing Theme', 'Red');
insert into acgc_furniture values(174, 0, 'ringside table', '1320', 'Tom Nook''s Shop (Group A)', 'Boxing Theme', 'none');
insert into acgc_furniture values(175, 0, 'sandbag', '3190', 'Tom Nook''s Shop (Group B)', 'Boxing Theme', 'none');
insert into acgc_furniture values(176, 0, 'speed bag', '2990', 'Tom Nook''s Shop (Group A)', 'Boxing Theme', 'none');
insert into acgc_furniture values(177, 0, 'weight bench', '3590', 'Tom Nook''s Shop (Group C)', 'Boxing Theme', 'none');
insert into acgc_furniture values(178, 0, 'black bishop', '2800', 'Redd''s', 'Chess Theme', 'none');
insert into acgc_furniture values(179, 0, 'black king', '23200', 'Tom Nook''s Lottery', 'Chess Theme', 'none');
insert into acgc_furniture values(180, 0, 'black knight', '2800', 'Redd''s', 'Chess Theme', 'none');
insert into acgc_furniture values(181, 0, 'black pawn', '1000', 'Tom Nook''s Shop', 'Chess Theme', 'none');
insert into acgc_furniture values(182, 0, 'black queen', '23200', 'Tom Nook''s Lottery', 'Chess Theme', 'none');
insert into acgc_furniture values(183, 0, 'black rook', '2800', 'Redd''s', 'Chess Theme', 'none');
insert into acgc_furniture values(184, 0, 'white bishop', '2800', 'Redd''s', 'Chess Theme', 'none');
insert into acgc_furniture values(185, 0, 'white king', '23200', 'Tom Nook''s Lottery', 'Chess Theme', 'none');
insert into acgc_furniture values(186, 0, 'white knight', '2800', 'Redd''s', 'Chess Theme', 'none');
insert into acgc_furniture values(187, 0, 'white pawn', '1000', 'Tom Nook''s Shop', 'Chess Theme', 'none');
insert into acgc_furniture values(188, 0, 'white queen', '23200', 'Tom Nook''s Lottery', 'Chess Theme', 'none');
insert into acgc_furniture values(189, 0, 'white rook', '2800', 'Redd''s', 'Chess Theme', 'none');
insert into acgc_furniture values(190, 0, 'cement mixer', '1600', 'Tom Nook''s Lottery', 'Construction Theme', 'Orange');
insert into acgc_furniture values(191, 0, 'detour arrow', '600', 'Tom Nook''s Shop (Group A)', 'Construction Theme', 'Red');
insert into acgc_furniture values(192, 0, 'detour sign', '830', 'Tom Nook''s Shop (Group B)', 'Construction Theme', 'Orange');
insert into acgc_furniture values(193, 0, 'flagman sign', '850', 'Tom Nook''s Shop (Group B)', 'Construction Theme', 'Orange');
insert into acgc_furniture values(194, 0, 'green drum', '800', 'Tom Nook''s Shop (Group B)', 'Construction Theme', 'Green');
insert into acgc_furniture values(195, 0, 'handcart', '800', 'Tom Nook''s Shop (Group A)', 'Construction Theme', 'none');
insert into acgc_furniture values(196, 0, 'haz-mat barrel', '830', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'Red');
insert into acgc_furniture values(197, 0, 'iron frame', '1200', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'Red');
insert into acgc_furniture values(198, 0, 'jackhammer', '1880', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'none');
insert into acgc_furniture values(199, 0, 'jersey barrier', '1050', 'Tom Nook''s Shop (Group B)', 'Construction Theme', 'none');
insert into acgc_furniture values(200, 0, 'manhole cover', '1000', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'none');
insert into acgc_furniture values(201, 0, 'men at work sign', '850', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'Orange');
insert into acgc_furniture values(202, 0, 'merge sign', '850', 'Tom Nook''s Shop (Group A)', 'Construction Theme', 'Orange');
insert into acgc_furniture values(203, 0, 'oil drum', '840', 'Tom Nook''s Shop (Group A)', 'Construction Theme', 'Orange');
insert into acgc_furniture values(204, 0, 'orange cone', '600', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'Red');
insert into acgc_furniture values(205, 0, 'saw horse', '900', 'Tom Nook''s Shop (Group C)', 'Construction Theme', 'none');
insert into acgc_furniture values(206, 0, 'speed sign', '870', 'Tom Nook''s Shop (Group B)', 'Construction Theme', 'none');
insert into acgc_furniture values(207, 0, 'steam roller', '4500', 'Redd''s', 'Construction Theme', 'Yellow');
insert into acgc_furniture values(208, 0, 'traffic cone', '800', 'Tom Nook''s Shop (Group A)', 'Construction Theme', 'Red');
insert into acgc_furniture values(209, 0, 'wet roadway sign', '850', 'Tom Nook''s Shop (Group B)', 'Construction Theme', 'Orange');
insert into acgc_furniture values(210, 0, 'deer scare', '1800', 'Redd''s', 'Mossy Garden Theme', 'Green');
insert into acgc_furniture values(211, 0, 'garden pond', '2580', 'Tom Nook''s Lottery', 'Mossy Garden Theme', 'none');
insert into acgc_furniture values(212, 0, 'low lantern', '2100', 'Tom Nook''s Shop (Group A)', 'Mossy Garden Theme', 'none');
insert into acgc_furniture values(213, 0, 'pond lantern', '1980', 'Tom Nook''s Shop (Group C)', 'Mossy Garden Theme', 'none');
insert into acgc_furniture values(214, 0, 'shrine lantern', '1980', 'Tom Nook''s Shop (Group A)', 'Mossy Garden Theme', 'none');
insert into acgc_furniture values(215, 0, 'tall lantern', '1980', 'Tom Nook''s Shop (Group B)', 'Mossy Garden Theme', 'none');
insert into acgc_furniture values(216, 0, '? block', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(217, 0, 'brick block', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(218, 0, 'cannon', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(219, 0, 'coin', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(220, 0, 'fire flower', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(221, 0, 'flagpole', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(222, 0, 'green pipe', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(223, 0, 'koopa shell', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(224, 0, 'starman', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(225, 0, 'super mushroom', 'Not for Sale', 'Nintendo Power', 'Mario Items', 'none');
insert into acgc_furniture values(226, 0, 'dark stone', '2200', 'Tom Nook''s Shop (Group C)', 'Rock Garden', 'none');
insert into acgc_furniture values(227, 0, 'garden stone', '1900', 'Tom Nook''s Shop (Group C)', 'Rock Garden', 'none');
insert into acgc_furniture values(228, 0, 'leaning stone', '2100', 'Tom Nook''s Shop (Group B)', 'Rock Garden', 'none');
insert into acgc_furniture values(229, 0, 'mossy stone', '2160', 'Tom Nook''s Shop (Group A)', 'Rock Garden', 'none');
insert into acgc_furniture values(230, 0, 'standing stone', '2500', 'Tom Nook''s Shop (Group B)', 'Rock Garden', 'none');
insert into acgc_furniture values(231, 0, 'stone couple', '2380', 'Tom Nook''s Shop (Group A)', 'Rock Garden', 'none');
insert into acgc_furniture values(232, 0, 'teacher''s chair', '1440', 'Tom Nook''s Shop (Group C)', 'School Theme', 'none');
insert into acgc_furniture values(233, 0, 'chalk board', '1400', 'Tom Nook''s Shop (Group C)', 'School Theme', 'Green');
insert into acgc_furniture values(234, 0, 'cubby hole', '2200', 'Tom Nook''s Shop (Group B)', 'School Theme', 'none');
insert into acgc_furniture values(235, 0, 'flip-top desk', '1320', 'Tom Nook''s Shop (Group A)', 'School Theme', 'none');
insert into acgc_furniture values(236, 0, 'school desk', '1320', 'Tom Nook''s Shop (Group C)', 'School Theme', 'none');
insert into acgc_furniture values(237, 0, 'folding chair', '600', 'Tom Nook''s Shop (Group A)', 'School Theme', 'none');
insert into acgc_furniture values(238, 0, 'lefty desk', '1240', 'Tom Nook''s Shop (Group A)', 'School Theme', 'none');
insert into acgc_furniture values(239, 0, 'righty desk', '1240', 'Tom Nook''s Shop (Group B)', 'School Theme', 'none');
insert into acgc_furniture values(240, 0, 'letter cubby', '2300', 'Redd''s', 'School Theme', 'none');
insert into acgc_furniture values(241, 0, 'hamster cage', '2290', 'Tom Nook''s Lottery', 'School Theme', 'Red');
insert into acgc_furniture values(242, 0, 'mop', '900', 'Tom Nook''s Shop (Group A)', 'School Theme', 'none');
insert into acgc_furniture values(243, 0, 'science table', '1900', 'Tom Nook''s Shop (Group C)', 'School Theme', 'none');
insert into acgc_furniture values(244, 0, 'teacher''s desk', '1580', 'Tom Nook''s Shop (Group B)', 'School Theme', 'none');
insert into acgc_furniture values(245, 0, 'vaulting horse', '1200', 'Tom Nook''s Shop (Group B)', 'School Theme', 'none');
insert into acgc_furniture values(246, 0, 'asteroid', '1800', 'Tom Nook''s Shop (Group A)', 'Space Theme', 'none');
insert into acgc_furniture values(247, 0, 'flying saucer', '2400', 'Tom Nook''s Shop (Group C)', 'Space Theme', 'none');
insert into acgc_furniture values(248, 0, 'lunar lander', '3200', 'Tom Nook''s Shop (Group B)', 'Space Theme', 'none');
insert into acgc_furniture values(249, 0, 'lunar rover', '2560', 'Tom Nook''s Shop (Group A)', 'Space Theme', 'none');
insert into acgc_furniture values(250, 0, 'rocket', '2400', 'Tom Nook''s Shop (Group B)', 'Space Theme', 'none');
insert into acgc_furniture values(251, 0, 'satellite', '2600', 'Tom Nook''s Shop (Group C)', 'Space Theme', 'none');
insert into acgc_furniture values(252, 0, 'space shuttle', '2780', 'Tom Nook''s Shop (Group A)', 'Space Theme', 'none');
insert into acgc_furniture values(253, 0, 'space station', '2800', 'Tom Nook''s Shop (Group B)', 'Space Theme', 'none');
insert into acgc_furniture values(254, 0, 'Spaceman Sam', '2800', 'Tom Nook''s Shop (Group C)', 'Space Theme', 'none');
insert into acgc_furniture values(255, 0, 'covered wagon', '3800', 'Tom Nook''s Lottery', 'Western Theme', 'none');
insert into acgc_furniture values(256, 0, 'cow skull', '1020', 'Tom Nook''s Shop (Group A)', 'Western Theme', 'none');
insert into acgc_furniture values(257, 0, 'desert cactus', '890', 'Tom Nook''s Shop (Group B)', 'Western Theme', 'Green');
insert into acgc_furniture values(258, 0, 'saddle fence', '2180', 'Redd''s', 'Western Theme', 'none');
insert into acgc_furniture values(259, 0, 'storefront', '3680', 'Tom Nook''s Shop (Group C)', 'Western Theme', 'none');
insert into acgc_furniture values(260, 0, 'tumbleweed', '520', 'Tom Nook''s Shop (Group C)', 'Western Theme', 'none');
insert into acgc_furniture values(261, 0, 'wagon wheel', '1230', 'Tom Nook''s Shop (Group B)', 'Western Theme', 'none');
insert into acgc_furniture values(262, 0, 'watering trough', '1100', 'Tom Nook''s Shop (Group B)', 'Western Theme', 'none');
insert into acgc_furniture values(263, 0, 'well', '2700', 'Redd''s', 'Western Theme', 'none');
insert into acgc_furniture values(264, 0, 'western fence', '880', 'Tom Nook''s Shop (Group A)', 'Western Theme', 'none');
insert into acgc_furniture values(265, 0, 'apple clock', '1200', 'Tom Nook''s Shop (Group C)', 'Apple Set', 'none');
insert into acgc_furniture values(266, 0, 'apple TV', '1600', 'Tom Nook''s Shop (Group A)', 'Apple Set', 'none');
insert into acgc_furniture values(267, 0, 'Baby bear', '800', 'Tom Nook''s Shop (Group C)', 'Bear Set', 'none');
insert into acgc_furniture values(268, 0, 'Mama bear', '1600', 'Tom Nook''s Shop (Group B)', 'Bear Set', 'none');
insert into acgc_furniture values(269, 0, 'Papa bear', '2200', 'Tom Nook''s Shop (Group A)', 'Bear Set', 'none');
insert into acgc_furniture values(270, 0, 'mugho bonsai', '1800', 'Tom Nook''s Shop (Group B)', 'Bonsai Set', 'Green');
insert into acgc_furniture values(271, 0, 'pine bonsai', '1800', 'Tom Nook''s Shop (Group A)', 'Bonsai Set', 'Green');
insert into acgc_furniture values(272, 0, 'ponderosa bonsai', '1800', 'Tom Nook''s Shop (Group C)', 'Bonsai Set', 'Green');
insert into acgc_furniture values(273, 0, 'cactus', '1700', 'Tom Nook''s Shop (Group A)', 'Cactus Set', 'Green');
insert into acgc_furniture values(274, 0, 'round cactus', '1700', 'Tom Nook''s Shop (Group C)', 'Cactus Set', 'Green');
insert into acgc_furniture values(275, 0, 'tall cactus', '1700', 'Tom Nook''s Shop (Group B)', 'Cactus Set', 'none');
insert into acgc_furniture values(276, 0, 'grapefruit table', '1500', 'Tom Nook''s Shop (Group C)', 'Citrus Set', 'Red');
insert into acgc_furniture values(277, 0, 'lemon table', '1500', 'Tom Nook''s Shop (Group B)', 'Citrus Set', 'Yellow');
insert into acgc_furniture values(278, 0, 'lime chair', '1300', 'Tom Nook''s Shop (Group A)', 'Citrus Set', 'Green');
insert into acgc_furniture values(279, 0, 'orange chair', '1300', 'Tom Nook''s Shop', 'Citrus Set', 'Orange');
insert into acgc_furniture values(280, 0, 'daffodil table', '1400', 'Tom Nook''s Shop (Group B)', 'Yellow Flower Set', 'none');
insert into acgc_furniture values(281, 0, 'daffodil chair', '1400', 'Tom Nook''s Shop (Group C)', 'Yellow Flower Set', 'none');
insert into acgc_furniture values(282, 0, 'iris chair', '1400', 'Tom Nook''s Shop (Group A)', 'Iris Flower Set', 'none');
insert into acgc_furniture values(283, 0, 'iris table', '1900', 'Tom Nook''s Shop (Group C)', 'Iris Flower Set', 'none');
insert into acgc_furniture values(284, 0, 'tulip chair', '1400', 'Tom Nook''s Shop (Group B)', 'Red Flower Set', 'none');
insert into acgc_furniture values(285, 0, 'tulip table', '1900', 'Tom Nook''s Shop (Group A)', 'Red Flower Set', 'none');
insert into acgc_furniture values(286, 0, 'conga drum', '1600', 'Tom Nook''s Shop (Group A)', 'Drum Set', 'none');
insert into acgc_furniture values(287, 0, 'djimbe drum', '1900', 'Tom Nook''s Shop (Group C)', 'Drum Set', 'none');
insert into acgc_furniture values(288, 0, 'timpano drum', '2100', 'Redd''s', 'Drum Set', 'none');
insert into acgc_furniture values(289, 0, 'Aiko figurine', '800', 'Tom Nook''s Shop (Group B)', 'Figurine Set', 'none');
insert into acgc_furniture values(290, 0, 'Emi figurine', '800', 'Tom Nook''s Shop (Group C)', 'Figurine Set', 'none');
insert into acgc_furniture values(291, 0, 'Keiko figurine', '800', 'Tom Nook''s Shop (Group A)', 'Figurine Set', 'none');
insert into acgc_furniture values(292, 0, 'Maki figurine', '800', 'Tom Nook''s Shop (Group C)', 'Figurine Set', 'none');
insert into acgc_furniture values(293, 0, 'Naomi figurine', '800', 'Tom Nook''s Shop (Group A)', 'Figurine Set', 'none');
insert into acgc_furniture values(294, 0, 'Yoko figurine', '800', 'Tom Nook''s Shop (Group B)', 'Figurine Set', 'none');
insert into acgc_furniture values(295, 0, 'Yuki figurine', '800', 'Tom Nook''s Shop (Group B)', 'Figurine Set', 'none');
insert into acgc_furniture values(296, 0, 'froggy chair', '1200', 'Tom Nook''s Shop (Group B)', 'Frog Set', 'Green');
insert into acgc_furniture values(297, 0, 'lily-pad table', '1600', 'Tom Nook''s Shop (Group A)', 'Frog Set', 'Green');
insert into acgc_furniture values(298, 0, 'folk guitar', '1600', 'Tom Nook''s Shop (Group A)', 'Guitar Set', 'none');
insert into acgc_furniture values(299, 0, 'country guitar', '1700', 'Tom Nook''s Shop (Group B)', 'Guitar Set', 'none');
insert into acgc_furniture values(300, 0, 'rock guitar', '1800', 'Tom Nook''s Shop (Group C)', 'Guitar Set', 'none');
insert into acgc_furniture values(301, 0, 'Luigi trophy', '7000', 'Redd''s', 'Lucky Nintendo Set', 'none');
insert into acgc_furniture values(302, 0, 'Mario trophy', '7000', 'Tom Nook''s Lottery', 'Lucky Nintendo Set', 'none');
insert into acgc_furniture values(303, 0, 'melon chair', '1300', 'Tom Nook''s Shop (Group B)', 'Melon Set', 'Yellow');
insert into acgc_furniture values(304, 0, 'watermelon chair', '1300', 'Tom Nook''s Shop (Group A)', 'Melon Set', 'Red');
insert into acgc_furniture values(305, 0, 'watermelon table', '1800', 'Tom Nook''s Shop (Group C)', 'Melon Set', 'Red');
insert into acgc_furniture values(306, 0, 'Arwing', '25600', 'Tom Nook''s Lottery', 'Nintendo Set', 'none');
insert into acgc_furniture values(307, 0, 'G logo', '2500', 'Tom Nook''s Shop (Group A)', 'Nintendo Set', 'none');
insert into acgc_furniture values(308, 0, 'Master Sword', '2800', 'Tom Nook''s Shop (Group B)', 'Nintendo Set', 'none');
insert into acgc_furniture values(309, 0, 'N logo', '2400', 'Tom Nook''s Shop (Group C)', 'Nintendo Set', 'none');
insert into acgc_furniture values(310, 0, 'office chair', '1100', 'Tom Nook''s Shop (Group A)', 'Office Set', 'none');
insert into acgc_furniture values(311, 0, 'office desk', '1600', 'Tom Nook''s Shop (Group C)', 'Office Set', 'none');
insert into acgc_furniture values(312, 0, 'office locker', '1200', 'Tom Nook''s Shop (Group B)', 'Office Set', 'none');
insert into acgc_furniture values(313, 0, 'pear dresser', '1600', 'Tom Nook''s Shop (Group A)', 'Pear Set', 'none');
insert into acgc_furniture values(314, 0, 'pear wardrobe', '1400', 'Tom Nook''s Shop (Group B)', 'Pear Set', 'none');
insert into acgc_furniture values(315, 0, 'pine chair', '1800', 'Tom Nook''s Shop (Group A)', 'Pine Wood Set', 'none');
insert into acgc_furniture values(316, 0, 'pine table', '2280', 'Tom Nook''s Shop (Group C)', 'Pine Wood Set', 'none');
insert into acgc_furniture values(317, 0, 'robo-clock', '1400', 'Redd''s', 'Robot Set', 'none');
insert into acgc_furniture values(318, 0, 'robo-stereo', '2200', 'Tom Nook''s Lottery', 'Robot Set', 'none');
insert into acgc_furniture values(319, 0, 'bass (instrument)', '2400', 'Redd''s', 'String Instrument Set', 'none');
insert into acgc_furniture values(320, 0, 'cello', '1800', 'Tom Nook''s Shop (Group B)', 'String Instrument Set', 'none');
insert into acgc_furniture values(321, 0, 'violin', '2200', 'Tom Nook''s Shop (Group A)', 'String Instrument Set', 'none');
insert into acgc_furniture values(322, 0, 'bear pole', '1400', 'Tom Nook''s Shop (Group C)', 'Totem Pole Set', 'none');
insert into acgc_furniture values(323, 0, 'eagle pole', '1400', 'Tom Nook''s Shop (Group A)', 'Totem Pole Set', 'none');
insert into acgc_furniture values(324, 0, 'frog woman pole', '1400', 'Redd''s', 'Totem Pole Set', 'none');
insert into acgc_furniture values(325, 0, 'raven pole', '1400', 'Tom Nook''s Shop (Group B)', 'Totem Pole Set', 'none');
insert into acgc_furniture values(326, 0, 'blue vase', '2500', 'Tom Nook''s Shop (Group A)', 'Vase Set', 'none');
insert into acgc_furniture values(327, 0, 'red vase', '2450', 'Tom Nook''s Shop (Group C)', 'Vase Set', 'none');
insert into acgc_furniture values(328, 0, 'tea vase', '2400', 'Tom Nook''s Shop (Group B)', 'Vase Set', 'none');
insert into acgc_furniture values(329, 0, 'candy machine', '2200', 'Tom Nook''s Shop (Group C)', 'Vending Machine Set', 'none');
insert into acgc_furniture values(330, 0, 'coffee machine', '2100', 'Tom Nook''s Shop (Group A)', 'Vending Machine Set', 'none');
insert into acgc_furniture values(331, 0, 'pop machine', '3250', 'Tom Nook''s Lottery', 'Vending Machine Set', 'none');
insert into acgc_furniture values(332, 0, 'soda machine', '1700', 'Tom Nook''s Shop (Group B)', 'Vending Machine Set', 'none');
insert into acgc_furniture values(333, 0, 'globe', '1200', 'Tom Nook''s Shop (Group A)', 'Study Set', 'none');
insert into acgc_furniture values(334, 0, 'writing chair', '1000', 'Tom Nook''s Shop (Group B)', 'Study Set', 'none');
insert into acgc_furniture values(335, 0, 'writing desk', '1900', 'Tom Nook''s Shop (Group C)', 'Study Set', 'none');
insert into acgc_furniture values(336, 0, 'barber''s pole', '1600', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(337, 0, 'birdcage', '1700', 'Tom Nook''s Shop (Group B)', 'Household Items', 'Red');
insert into acgc_furniture values(338, 0, 'bus stop', '820', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(339, 0, 'extinguisher', '1300', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(340, 0, 'fan', '1200', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(341, 0, 'garbage can', '500', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(342, 0, 'trash bin', '500', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(343, 0, 'tea set', '300', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(344, 0, 'glass-top table', '2200', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(345, 0, 'orange box', '80', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(346, 0, 'pineapple bed', '1990', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(347, 0, 'potbelly stove', '2000', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(348, 0, 'radiator', '2380', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(349, 0, 'rocking chair', '1400', 'Tom Nook''s Shop (Group A)', 'Chairs and Sofas', 'none');
insert into acgc_furniture values(350, 0, 'scale', '1200', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(351, 0, 'sewing machine', '1350', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(352, 0, 'space heater', '1700', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(353, 0, 'refrigerator', '1200', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(354, 0, 'stove', '1980', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(355, 0, 'mochi pestle', '1400', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(356, 0, 'biwa lute', '1800', 'Tom Nook''s Shop (Group B)', 'Musical Instruments', 'none');
insert into acgc_furniture values(357, 0, 'taiko drum', '1300', 'Tom Nook''s Shop (Group C)', 'Musical Instruments', 'none');
insert into acgc_furniture values(358, 0, 'chess table', '2200', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(359, 0, 'table tennis', '1800', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(360, 0, 'billiard table', '1800', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(361, 0, 'executive toy', '1100', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(362, 0, 'slot machine', '777', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(363, 0, 'water bird', '1400', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(364, 0, 'wobbelina', '700', 'Tom Nook''s Shop (Group A)', 'Household Items', 'none');
insert into acgc_furniture values(365, 0, 'computer', '1820', 'Redd''s', 'Household Items', 'none');
insert into acgc_furniture values(366, 0, 'toilet', '1800', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(367, 0, 'super toilet', '1980', 'Redd''s', 'Household Items', 'none');
insert into acgc_furniture values(368, 0, 'daffodil', '680', 'Tom Nook''s Shop (Group C)', 'Arranged Flowers', 'none');
insert into acgc_furniture values(369, 0, 'gerbera', '780', 'Tom Nook''s Shop (Group A)', 'Arranged Flowers', 'Orange');
insert into acgc_furniture values(370, 0, 'sunflower', '980', 'Tom Nook''s Shop (Group B)', 'Arranged Flowers', 'Yellow');
insert into acgc_furniture values(371, 0, 'hinaningyo', '2560', 'Redd''s', 'Household Items', 'none');
insert into acgc_furniture values(372, 0, 'samurai suit', '4500', 'Tom Nook''s Lottery', 'Household Items', 'none');
insert into acgc_furniture values(373, 0, 'tanabata palm', '1925', 'Redd''s', 'Household Items', 'none');
insert into acgc_furniture values(374, 0, 'elephant slide', '1200', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(375, 0, 'train set', '1600', 'Tom Nook''s Shop (Group C)', 'Household Items', 'Green');
insert into acgc_furniture values(376, 0, 'retro TV', '1600', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(377, 0, 'wide-screen TV', '2200', 'Redd''s', 'Household Items', 'none');
insert into acgc_furniture values(378, 0, 'big festive tree', '2480', 'Tom Nook''s Shop', 'Holiday Items', 'none');
insert into acgc_furniture values(379, 0, 'festive tree', '1300', 'Tom Nook''s Shop', 'Holiday Items', 'none');
insert into acgc_furniture values(380, 0, 'festive candle', '1600', 'Tom Nook''s Shop', 'Holiday Items', 'none');
insert into acgc_furniture values(381, 0, 'festive flag', '680', 'Tom Nook''s Shop', 'Holiday Items', 'none');
insert into acgc_furniture values(382, 0, 'metronome', '1000', 'Tom Nook''s Shop (Group B)', 'Musical Instruments', 'none');
insert into acgc_furniture values(383, 0, 'harp', '1700', 'Tom Nook''s Shop (Group C)', 'Musical Instruments', 'none');
insert into acgc_furniture values(384, 0, 'vibraphone', '1900', 'Tom Nook''s Shop (Group A)', 'Musical Instruments', 'none');
insert into acgc_furniture values(385, 0, 'ebony piano', '3800', 'Redd''s', 'Musical Instruments', 'none');
insert into acgc_furniture values(386, 0, 'ivory piano', '3500', 'Tom Nook''s Lottery', 'Musical Instruments', 'none');
insert into acgc_furniture values(387, 0, 'barrel', '800', 'Tom Nook''s Shop (Group B)', 'Household Items', 'none');
insert into acgc_furniture values(388, 0, 'keg', '800', 'Tom Nook''s Shop (Group C)', 'Household Items', 'none');
insert into acgc_furniture values(389, 0, 'blue golf bag', '1600', 'Tom Nook''s Shop (Group C)', 'Golf Bags', 'none');
insert into acgc_furniture values(390, 0, 'green golf bag', '1600', 'Tom Nook''s Shop (Group A)', 'Golf Bags', 'none');
insert into acgc_furniture values(391, 0, 'white golf bag', '1600', 'Tom Nook''s Shop (Group B)', 'Golf Bags', 'none');
insert into acgc_furniture values(392, 0, 'Nook''s portrait', '480', 'Tom Nook''s Lottery', 'Household Items', 'none');
insert into acgc_furniture values(393, 0, 'cream sofa', '2000', 'Tom Nook''s Shop (Group B)', 'Chairs and Sofas', 'none');
insert into acgc_furniture values(394, 0, 'red sofa', '2050', 'Tom Nook''s Shop (Group C)', 'Chairs and Sofas', 'Red');
insert into acgc_furniture values(395, 0, 'red armchair', '1800', 'Tom Nook''s Shop (Group A)', 'Chairs and Sofas', 'Red');
insert into acgc_furniture values(396, 0, 'gold econo-chair', '800', 'Tom Nook''s Shop (Group B)', 'Chairs and Sofas', 'Yellow');
insert into acgc_furniture values(397, 0, 'jade econo-chair', '800', 'Tom Nook''s Shop (Group C)', 'Chairs and Sofas', 'Green');
insert into acgc_furniture values(398, 0, 'ruby econo-chair', '800', 'Tom Nook''s Shop (Group A)', 'Chairs and Sofas', 'Orange');
insert into acgc_furniture values(399, 0, 'alarm clock', '1000', 'Tom Nook''s Shop (Group B)', 'Clocks', 'none');
insert into acgc_furniture values(400, 0, 'antique clock', '2350', 'Tom Nook''s Shop (Group A)', 'Clocks', 'none');
insert into acgc_furniture values(401, 0, 'cube clock', '1100', 'Tom Nook''s Shop (Group B)', 'Clocks', 'none');
insert into acgc_furniture values(402, 0, 'glow clock', '1500', 'Tom Nook''s Shop (Group B)', 'Clocks', 'none');
insert into acgc_furniture values(403, 0, 'kitschy clock', '1800', 'Tom Nook''s Shop (Group A)', 'Clocks', 'none');
insert into acgc_furniture values(404, 0, 'odd clock', '1800', 'Tom Nook''s Shop (Group C)', 'Clocks', 'none');
insert into acgc_furniture values(405, 0, 'owl clock', '1300', 'Tom Nook''s Shop (Group A)', 'Clocks', 'none');
insert into acgc_furniture values(406, 0, 'red clock', '1300', 'Tom Nook''s Shop (Group C)', 'Clocks', 'none');
insert into acgc_furniture values(407, 0, 'azalea bonsai', '1500', 'Tom Nook''s Shop (Group B)', 'Bonsai Trees', 'Green');
insert into acgc_furniture values(408, 0, 'hawthorn bonsai', '1800', 'Tom Nook''s Shop (Group C)', 'Bonsai Trees', 'Green');
insert into acgc_furniture values(409, 0, 'holly bonsai', '1600', 'Tom Nook''s Shop (Group B)', 'Bonsai Trees', 'Green');
insert into acgc_furniture values(410, 0, 'jasmine bonsai', '1700', 'Tom Nook''s Shop (Group A)', 'Bonsai Trees', 'Green');
insert into acgc_furniture values(411, 0, 'maple bonsai', '1700', 'Tom Nook''s Shop (Group C)', 'Bonsai Trees', 'Orange');
insert into acgc_furniture values(412, 0, 'quince bonsai', '1600', 'Tom Nook''s Shop (Group A)', 'Bonsai Trees', 'Red');
insert into acgc_furniture values(413, 0, 'plum bonsai', '1900', 'Tom Nook''s Lottery', 'Bonsai Trees', 'Red');
insert into acgc_furniture values(414, 0, 'aloe', '1200', 'Tom Nook''s Shop (Group B)', 'House Plants', 'Green');
insert into acgc_furniture values(415, 0, 'bromeliaceae', '1300', 'Tom Nook''s Shop (Group B)', 'House Plants', 'Green');
insert into acgc_furniture values(416, 0, 'caladium', '1300', 'Tom Nook''s Shop (Group A)', 'House Plants', 'Green');
insert into acgc_furniture values(417, 0, 'coconut palm', '1200', 'Tom Nook''s Shop (Group B)', 'House Plants', 'Green');
insert into acgc_furniture values(418, 0, 'corn plant', '1300', 'Tom Nook''s Shop (Group C)', 'House Plants', 'Green');
insert into acgc_furniture values(419, 0, 'croton', '1300', 'Tom Nook''s Shop (Group C)', 'House Plants', 'Green');
insert into acgc_furniture values(420, 0, 'dracaena', '2000', 'Tom Nook''s Lottery', 'House Plants', 'none');
insert into acgc_furniture values(421, 0, 'fan palm', '1300', 'Tom Nook''s Shop (Group C)', 'House Plants', 'Green');
insert into acgc_furniture values(422, 0, 'lady palm', '1200', 'Tom Nook''s Shop (Group A)', 'House Plants', 'Green');
insert into acgc_furniture values(423, 0, 'pachira', '1200', 'Tom Nook''s Shop (Group C)', 'House Plants', 'Green');
insert into acgc_furniture values(424, 0, 'pothos', '1300', 'Tom Nook''s Shop (Group A)', 'House Plants', 'Green');
insert into acgc_furniture values(425, 0, 'rubber tree', '1300', 'Tom Nook''s Shop (Group B)', 'House Plants', 'Green');
insert into acgc_furniture values(426, 0, 'snake plant', '1200', 'Tom Nook''s Shop (Group A)', 'House Plants', 'Green');
insert into acgc_furniture values(427, 0, 'weeping fig', '1200', 'Tom Nook''s Shop (Group C)', 'House Plants', 'Green');
insert into acgc_furniture values(428, 0, 'tape deck', '700', 'Tom Nook''s Shop (Group A)', 'Stereo Systems', 'none');
insert into acgc_furniture values(429, 0, 'red boom box', '1500', 'Tom Nook''s Shop (Group C)', 'Stereo Systems', 'Red');
insert into acgc_furniture values(430, 0, 'white boom box', '1500', 'Tom Nook''s Shop (Group B)', 'Stereo Systems', 'none');
insert into acgc_furniture values(431, 0, 'CD player', '1600', 'Tom Nook''s Shop (Group B)', 'Stereo Systems', 'none');
insert into acgc_furniture values(432, 0, 'phonograph', '1840', 'Tom Nook''s Shop (Group A)', 'Stereo Systems', 'none');
insert into acgc_furniture values(433, 0, 'jukebox', '3850', 'Tom Nook''s Lottery', 'Stereo Systems', 'none');
insert into acgc_furniture values(434, 0, 'turntable', '2580', 'Redd''s', 'Stereo Systems', 'none');
insert into acgc_furniture values(435, 0, 'retro stereo', '2160', 'Tom Nook''s Shop (Group C)', 'Stereo Systems', 'none');
insert into acgc_furniture values(436, 0, 'high-end stereo', '2750', 'Redd''s', 'Stereo Systems', 'none');
insert into acgc_furniture values(437, 0, 'reel-to-reel', '2000', 'Tom Nook''s Shop (Group C)', 'Stereo Systems', 'none');
insert into acgc_furniture values(438, 0, 'gold stereo', '2640', 'Tom Nook''s Shop (Group B)', 'Stereo Systems', 'none');
insert into acgc_furniture values(439, 0, 'lovely stereo', '1980', 'Redd''s', 'Stereo Systems', 'none');
insert into acgc_furniture values(440, 0, 'dice stereo', '2150', 'Redd''s', 'Stereo Systems', 'none');
insert into acgc_furniture values(441, 0, 'hi-fi stereo', '24000', 'Tom Nook''s Lottery', 'Stereo Systems', 'none');
insert into acgc_furniture values(442, 0, 'classic painting', '1960', 'Tom Nook''s Shop (Group C)', 'Paintings', 'none');
insert into acgc_furniture values(443, 0, 'fine painting', '1960', 'Tom Nook''s Shop (Group B)', 'Paintings', 'none');
insert into acgc_furniture values(444, 0, 'perfect painting', '1960', 'Tom Nook''s Shop (Group A)', 'Paintings', 'none');
insert into acgc_furniture values(445, 0, 'rare painting', '1960', 'Tom Nook''s Shop (Group B)', 'Paintings', 'none');
insert into acgc_furniture values(446, 0, 'strange painting', '1960', 'Tom Nook''s Shop (Group A)', 'Paintings', 'none');
insert into acgc_furniture values(447, 0, 'worthy painting', '1960', 'Tom Nook''s Shop (Group C)', 'Paintings', 'none');
insert into acgc_furniture values(448, 0, 'amazing painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(449, 0, 'basic painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(450, 0, 'common painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(451, 0, 'dainty painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(452, 0, 'famous painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(453, 0, 'flowery painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(454, 0, 'moving painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(455, 0, 'quaint painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(456, 0, 'scary painting', '1960', 'Redd''s', 'Paintings', 'none');
insert into acgc_furniture values(457, 0, 'chowder', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(458, 0, 'crab stew', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(459, 0, 'fireplace', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'Red');
insert into acgc_furniture values(460, 0, 'sleigh', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(461, 0, 'snow bunny', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(462, 0, 'snowboard', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(463, 0, 'backpack', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(464, 0, 'bonfire', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(465, 0, 'campfire', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(466, 0, 'cooler', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(467, 0, 'kayak', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'Yellow');
insert into acgc_furniture values(468, 0, 'lantern', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'Red');
insert into acgc_furniture values(469, 0, 'mountain bike', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(470, 0, 'propane stove', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(471, 0, 'sleeping bag', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'none');
insert into acgc_furniture values(472, 0, 'beach chair', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(473, 0, 'beach table', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(474, 0, 'Diver Dan', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(475, 0, 'life ring', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(476, 0, 'snowcone machine', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(477, 0, 'surfboard', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(478, 0, 'treasure chest', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(479, 0, 'ukulele', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(480, 0, 'wave breaker', 'Not for Sale', 'Animal Island', 'Island Items', 'none');
insert into acgc_furniture values(481, 0, 'Arc De Triomphe', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(482, 0, 'Chinese lion', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(483, 0, 'Chinese lioness', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(484, 0, 'compass', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(485, 0, 'fishing bear', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(486, 0, 'Lady Liberty', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(487, 0, 'Manekin Pis', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(488, 0, 'matryoshka', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(489, 0, 'Merlion', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(490, 0, 'mermaid statue', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(491, 0, 'Moai statue', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(492, 0, 'Mouth of Truth', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(493, 0, 'pagoda', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(494, 0, 'plate armor', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(495, 0, 'shogi piece', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(496, 0, 'stone coin', 'Not for Sale', 'Gulliver', 'World Icons', 'Red');
insert into acgc_furniture values(497, 0, 'tiger bobblehead', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(498, 0, 'Tokyo Tower', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(499, 0, 'Tower of Pisa', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(500, 0, 'tribal mask', 'Not for Sale', 'Gulliver', 'World Icons', 'none');
insert into acgc_furniture values(501, 0, 'Nintendo bench', 'Not for Sale', 'Tips & Tricks Magazine', 'Mementos and Models', 'none');
insert into acgc_furniture values(502, 0, 'birthday cake', 'Not for Sale', 'Special Event', 'Holiday Items', 'none');
insert into acgc_furniture values(503, 0, 'chocolates', 'Not for Sale', 'Tortimer', 'Mementos and Models', 'none');
insert into acgc_furniture values(504, 0, 'tissue', 'Not for Sale', 'Savings', 'Mementos and Models', 'none');
insert into acgc_furniture values(505, 0, 'piggy bank', 'Not for Sale', 'Savings', 'Mementos and Models', 'none');
insert into acgc_furniture values(506, 0, 'mailbox', 'Not for Sale', 'Savings', 'Mementos and Models', 'none');
insert into acgc_furniture values(507, 0, 'telescope', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(508, 0, 'aerobics radio', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(509, 0, 'angler trophy', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(510, 0, 'autumn medal', 'Not for Sale', 'Special Event', 'Mementos and Models', 'Special');
insert into acgc_furniture values(511, 0, 'spring medal', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(512, 0, 'bottle rocket', 'Not for Sale', 'Special Event', 'Holiday Items', 'none');
insert into acgc_furniture values(513, 0, 'bottled ship', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(514, 0, 'cornucopia', '1880', 'Special Event', 'Holiday Items', 'none');
insert into acgc_furniture values(515, 0, 'dolly', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(516, 0, 'fishing trophy', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(517, 0, 'lovely phone', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(518, 0, 'moon', 'Not for Sale', 'Tortimer', 'Mementos and Models', 'none');
insert into acgc_furniture values(519, 0, 'noisemaker', 'Not for Sale', 'Special Event', 'Mementos and Models', 'Red');
insert into acgc_furniture values(520, 0, 'Balloon Fight', '3000', 'Special Item', 'Classic NES Games', 'Yellow');
insert into acgc_furniture values(521, 0, 'Baseball', 'Not for Sale', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(522, 0, 'Clu Clu Land', '3000', 'Special Item', 'Classic NES Games', 'none');
insert into acgc_furniture values(523, 0, 'Clu Clu Land D', 'Not for Sale', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(524, 0, 'DK Jr MATH', '3000', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(525, 0, 'Donkey Kong', '3000', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(526, 0, 'Donkey Kong 3', 'Not for Sale', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(527, 0, 'Donkey Kong Jr', 'Not for Sale', 'Nintendo Power', 'Classic NES Games', 'Red');
insert into acgc_furniture values(528, 0, 'Excitebike', '3000', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(529, 0, 'Golf', '3000', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(530, 0, 'Ice Climber', 'Not for Sale', 'Special Item', 'Classic NES Games', 'none');
insert into acgc_furniture values(531, 0, 'Legend of Zelda', 'Not for Sale', 'Special Item', 'Classic NES Games', 'none');
insert into acgc_furniture values(532, 0, 'Mario Bros.', 'Not for Sale', 'Special Item', 'Classic NES Games', 'none');
insert into acgc_furniture values(533, 0, 'NES', '3000', 'Redd''s', 'Classic NES Games', 'none');
insert into acgc_furniture values(534, 0, 'Pinball', '3000', 'Special Item', 'Classic NES Games', 'none');
insert into acgc_furniture values(535, 0, 'Punchout', 'Not for Sale', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(536, 0, 'Soccer', 'Not for Sale', 'Nintendo Power', 'Classic NES Games', 'Red');
insert into acgc_furniture values(537, 0, 'Super Tortimer', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(538, 0, 'Super Mario Bros.', 'Not for Sale', 'Special Item', 'Classic NES Games', 'none');
insert into acgc_furniture values(539, 0, 'cosmos model 1', '910', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(540, 0, 'Tennis', '3000', 'Special Item', 'Classic NES Games', 'Yellow');
insert into acgc_furniture values(541, 0, 'cosmos model 2', '910', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(542, 0, 'Wario''s Woods', 'Not for Sale', 'Special Item', 'Classic NES Games', 'Red');
insert into acgc_furniture values(543, 0, 'cosmos model 3', '910', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(544, 0, 'pansy model 1', '930', 'Special Event', 'Mementos and Models', 'Yellow');
insert into acgc_furniture values(545, 0, 'pansy model 2', '930', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(546, 0, 'pansy model 3', '930', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(547, 0, 'tulip model 1', '940', 'Special Event', 'Mementos and Models', 'Yellow');
insert into acgc_furniture values(548, 0, 'tulip model 2', '940', 'Special Event', 'Mementos and Models', 'Red');
insert into acgc_furniture values(549, 0, 'tulip model 3', '940', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(550, 0, 'dirt model', '1200', 'Tom Nook''s Shop (Group C)', 'Mementos and Models', 'none');
insert into acgc_furniture values(551, 0, 'grass model', '1200', 'Tom Nook''s Shop (Group A)', 'Mementos and Models', 'Green');
insert into acgc_furniture values(552, 0, 'weed model', '820', 'Special Event', 'Mementos and Models', 'Green');
insert into acgc_furniture values(553, 0, 'pink tree model', '1400', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(554, 0, 'tree model', '1400', 'Special Event', 'Mementos and Models', 'Green');
insert into acgc_furniture values(555, 0, 'snowy tree model', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(556, 0, 'igloo model', 'Not for Sale', 'Igloo Resident', 'Mementos and Models', 'none');
insert into acgc_furniture values(557, 0, 'Snowman', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(558, 0, 'tent model', 'Not for Sale', 'Summer Campers', 'Mementos and Models', 'Yellow');
insert into acgc_furniture values(559, 0, 'track model', '1400', 'Tom Nook''s Shop (Group B)', 'Mementos and Models', 'none');
insert into acgc_furniture values(560, 0, 'locomotive model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(561, 0, 'train car model', '2500', 'Tom Nook''s Shop (Group B)', 'Mementos and Models', 'none');
insert into acgc_furniture values(562, 0, 'miniature car', 'Not for Sale', 'Special Event', 'Mementos and Models', 'Red');
insert into acgc_furniture values(563, 0, 'dump model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(564, 0, 'well model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(565, 0, 'Katrina''s tent', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(566, 0, 'market model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'Green');
insert into acgc_furniture values(567, 0, 'police model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(568, 0, 'shop model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(569, 0, 'post model', 'Not for Sale', 'Savings', 'Mementos and Models', 'none');
insert into acgc_furniture values(570, 0, 'tailor model', 'Not for Sale', 'Special Event', 'Mementos and Models', 'Red');
insert into acgc_furniture values(571, 0, 'lighthouse model', 'Not for Sale', 'Tortimer', 'Mementos and Models', 'none');
insert into acgc_furniture values(572, 0, 'house model', 'Not for Sale', 'HRA', 'Mementos and Models', 'none');
insert into acgc_furniture values(573, 0, 'manor model', 'Not for Sale', 'HRA', 'Mementos and Models', 'none');
insert into acgc_furniture values(574, 0, 'museum model', 'Not for Sale', 'Blathers', 'Mementos and Models', 'none');
insert into acgc_furniture values(575, 0, 'station model 1', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(576, 0, 'station model 2', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(577, 0, 'station model 3', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(578, 0, 'station model 4', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(579, 0, 'station model 5', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(580, 0, 'station model 6', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(581, 0, 'station model 7', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(582, 0, 'station model 8', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(583, 0, 'station model 9', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(584, 0, 'station model 10', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(585, 0, 'station model 11', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(586, 0, 'station model 12', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(587, 0, 'station model 13', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(588, 0, 'station model 14', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(589, 0, 'station model 15', 'Not for Sale', 'Special Event', 'Mementos and Models', 'none');
insert into acgc_furniture values(590, 0, 'blue diary', '880', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(591, 0, 'blue polka pad', '320', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(592, 0, 'calligraphy pad', '860', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(593, 0, 'captain''s log', '980', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(594, 0, 'college rule', 'Not for Sale', 'Special Item', 'Journals and Diaries', 'none');
insert into acgc_furniture values(595, 0, 'diary', '1450', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(596, 0, 'french notebook', '1250', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(597, 0, 'green plaid pad', '320', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(598, 0, 'journal', '280', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(599, 0, 'organizer', '1280', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(600, 0, 'pink diary', '870', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(601, 0, 'pink plaid pad', '320', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(602, 0, 'red polka pad', '320', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(603, 0, 'school pad', '200', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(604, 0, 'scroll', '1200', 'Tom Nook''s Shop', 'Journals and Diaries', 'none');
insert into acgc_furniture values(605, 0, 'yellow plaid pad', '320', 'Tom Nook''s Shop ', 'Journals and Diaries', 'none');
insert into acgc_shirt values(248, 0, 'Cherry Shirt', 'orderable', '?', '?');
insert into acgc_shirt values(249, 0, 'Bamboo Robe', '?', 'Nook Password', '?');
insert into acgc_shirt values(250, 0, 'Blue Puffy Vest', '?', 'Nook Password', '?');
insert into acgc_shirt values(251, 0, 'Blue Sweatsuit', '?', 'Nook Password', '?');
insert into acgc_shirt values(252, 0, 'Plum Kimono', '?', 'Nook Password', '?');
insert into acgc_shirt values(253, 0, 'Red Puffy Vest', '?', 'Nook Password', '?');
insert into acgc_shirt values(254, 0, 'Red Sweatsuit', '?', 'Nook Password', '?');
insert into acgc_shirt values(255, 0, 'Somber Robe', '?', 'Nook Password', '?');
insert into acgc_shirt values(256, 0, 'Summer Robe', '?', 'Nook Password', '?');
insert into acgc_wallpaper values(65, 0, 'Mushroom Mural', '?', 'Nook Password');
insert into acgc_wallpaper values(66, 0, 'Ringside Seating', 'unorderable', 'Wendell');
insert into acgc_wallpaper values(67, 0, 'Harvest Wall', 'unorderable', 'Franklin');
insert into acgc_carpet values(66, 0, 'Block Flooring', '?', 'Nook Password');
insert into acgc_carpet values(67, 0, 'Boxing Ring Mat', 'unorderable', 'Saharah');
insert into acgc_carpet values(68, 0, 'Harvest Rug', 'unorderable', 'Franklin');
update acgc_insect set "Times" = 'April through September, 8am to 4pm' where "Index" = 3;
insert into acgc_may_insect values (3);
insert into acgc_jun_insect values (3);
insert into acgc_jul_insect values (3);
insert into acgc_aug1_insect values (3);
insert into acgc_aug2_insect values (3);
insert into acgc_sep1_insect values (3);
insert into acgc_sep2_insect values (3);
insert into acgc_shirt values(257, 0, 'Houndstooth Knit', 'orderable', '?', 'winter');
update acgc_shirt set "Name" = 'Toad Print' where "Index" = 242;
insert into acgc_wallpaper values(68, 0, 'Backyard Fence', 'orderable', '?');
update acnh_wall_mounted set "Name" = 'light switch (Gray)' where "Index" = 236;
update acnh_wall_mounted set "Name" = 'light switch (Brown)' where "Index" = 237;
update acnh_wall_mounted set "Name" = 'light switch (White)' where "Index" = 238;
update acnh_wall_mounted set "Name" = 'light switch (Wood grain)' where "Index" = 239;