update acww_fish set "Times" = 'March through June and September through November, all day (best time is March and April)' where "Index" = 23;
update acww_fish set "Times" = 'March through June and September through November, 4am to 9am and 4pm to 9pm' where "Index" = 24;
update acww_fish set "Times" = 'March through June and September through November, all day (best time is March through May)' where "Index" = 25;
insert into acww_sep1_fish values (23), (24), (25);
insert into acww_sep2_fish values (23), (24), (25);
insert into acww_oct_fish values (23), (24), (25);
insert into acww_nov_fish values (23), (24), (25);
update acnh_recipe set "From" = 'Fall' where "From" = 'Balloon/Bottle/Villager (Fall)';
update acnh_recipe set "From" = 'Spring' where "From" = 'Balloon/Bottle/Villager (Spring)';
update acnh_recipe set "From" = 'Festive Season' where "From" = 'Balloon/Bottle/Villager (Festive Season)';
update acnh_recipe set "From" = 'Cherry-Blossom Season' where "From" = 'Balloon/Bottle/Villager (Cherry-Blossom Season)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Zipper for collecting all 6 egg types (Bunny Day)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Villager (Bunny Day)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Egg message bottle';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Zipper after crafting toy (Bunny Day)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Collecting 11 earth eggs (Bunny Day)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Learning all egg outfit DIYs (Bunny Day)';
update acnh_recipe set "From" = 'Mushroom Season' where "From" = 'Balloon/Bottle/Villager (Mushroom Season)';
update acnh_recipe set "From" = 'Winter' where "From" = 'Balloon/Bottle/Villager (Winter)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Collecting 12 leaf eggs (Bunny Day)';
update acnh_recipe set "From" = 'Festive Season' where "From" = 'Isabelle (Festive Season)';
update acnh_recipe set "From" = 'Festive Season' where "From" = 'Isabelle (Festive season)';
update acnh_recipe set "From" = 'Tom Nook' where "From" = 'Tom Nook (Story)';
update acnh_recipe set "From" = 'Summer' where "From" = 'Balloon/Bottle/Villager (Summer)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Collecting 9 sky eggs (Bunny Day)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Collecting 17 stone eggs (Bunny Day)';
update acnh_recipe set "From" = 'Fall' where "From" = 'Isabelle (Fall)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Collecting 13 water eggs (Bunny Day)';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Zipper for crafting all Bunny Day recipes';
update acnh_recipe set "From" = 'Bunny Day' where "From" = 'Collecting 22 wood eggs (Bunny Day)';
update acnh_recipe set "From" = 'Fishing up trash' where "From" = 'Fishing up an old tire';
update acnh_recipe set "From" = 'Fishing up trash' where "From" = 'Fishing up all 3 trash items';
update acnh_song set "From" = 'Nook Shopping Catalog or K.K. Concert' where "From" = 'K.K. concert, Nook Shopping Catalog';
update acnh_song set "From" = 'Request only' where "From" = 'K.K. concert';